/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ABAddressBook.h"

@interface ABAddressBook (BrowserExtras)
- (BOOL)openAddressBookWithURLString:(id)fp8;
- (BOOL)openAddressBook;
- (BOOL)openAddressBookToPerson:(id)fp8 andEdit:(BOOL)fp12;
- (BOOL)editMeCard;
@end

