/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SheetWithTableController.h"

@class NSArray, NSButton, NSSearchField, NSTableColumn;

@interface AcceptedCookies : SheetWithTableController
{
    NSArray *cookies;
    NSTableColumn *sortColumn;
    NSSearchField *searchField;
    NSButton *doneButton;
}

- (void *)sortFunction;
- (id)selection;
- (void)setSelection:(id)fp8;
- (void)setCookies:(id)fp8;
- (id)searchWordsFromString:(id)fp8;
- (BOOL)matchCookie:(id)fp8 stringArray:(id)fp12;
- (id)getMatches:(id)fp8 query:(id)fp12;
- (void)updateCookieData;
- (void)setSortColumn:(id)fp8;
- (void)awakeFromNib;
- (void)dealloc;
- (void)removeSelectedItems:(id)fp8;
- (BOOL)confirmRemoveAllItems;
- (void)removeAllItems:(id)fp8;
- (void)showSheetInWindow:(id)fp8;
- (void)hideSheet:(id)fp8;
- (int)numberOfRowsInTableView:(id)fp8;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (void)tableView:(id)fp8 didClickTableColumn:(id)fp12;
- (void)cookiesChangedNotificationHandler:(id)fp8;
- (void)registerForCookieChangeNotifications;
- (void)unregisterForCookieChangeNotifications;
- (void)search:(id)fp8;
- (BOOL)control:(id)fp8 textView:(id)fp12 doCommandBySelector:(SEL)fp16;

@end

