/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AcceptedDatabases.h"

@interface AcceptedDatabases (FileInternal)
- (void)_chooseQuotaFromMenuItem:(id)fp8;
- (BOOL)_confirmRemoveForAllItems:(BOOL)fp8;
- (void)_didModifyDatabase:(id)fp8;
- (void)_didModifySecurityOrigin:(id)fp8;
- (id)_outlineView;
- (void)_refreshAllDataNow;
- (void)_refreshAllDataSoon;
- (void)_willPopUpMenuFromCell:(id)fp8;
@end

