/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AccessibilityChildInfo.h"

@interface AccessibilityButtonInfo : AccessibilityChildInfo
{
}

+ (id)infoWithParent:(id)fp8 identifier:(unsigned int)fp12;
- (id)initWithParent:(id)fp8 identifier:(unsigned int)fp12;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (id)accessibilityActionNames;
- (id)accessibilityActionDescription:(id)fp8;
- (void)accessibilityPerformAction:(id)fp8;

@end

