/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface AccessibilityChildInfo : NSObject
{
    NSString *_role;
    id _parent;
    unsigned int _identifier;
}

+ (id)infoWithRole:(id)fp8 parent:(id)fp12 identifier:(unsigned int)fp16;
- (id)accessibilityAttributeNames;
- (id)initWithRole:(id)fp8 parent:(id)fp12 identifier:(unsigned int)fp16;
- (void)dealloc;
- (unsigned int)identifier;
- (BOOL)isEqual:(id)fp8;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (void)accessibilitySetValue:(id)fp8 forAttribute:(id)fp12;
- (id)accessibilityActionNames;
- (id)accessibilityActionDescription:(id)fp8;
- (void)accessibilityPerformAction:(id)fp8;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityHitTest:(struct _NSPoint)fp8;
- (id)accessibilityFocusedUIElement;

@end

