/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "ReopensAtLaunch-Protocol.h"

@class NSColor, NSFont, NSImage, NSMutableArray, NSMutableSet, NSPanel, OutlineViewPlus;

@interface ActivityViewer : NSWindowController <ReopensAtLaunch>
{
    OutlineViewPlus *outlineView;
    NSPanel *activityPanel;
    NSMutableArray *_topLevelItems;
    NSMutableSet *_pendingReloadDeepItems;
    NSMutableSet *_pendingReloadFlatItems;
    NSMutableSet *_pendingExpansionItems;
    BOOL _nibLoaded;
    BOOL _reloadPending;
    NSColor *_successColor;
    NSColor *_failureColor;
    NSColor *_neutralColor;
    NSImage *_stopImage;
    NSImage *_stopPressedImage;
    NSFont *_fontForTopLevelItems;
    NSFont *_fontForAllOtherItems;
}

+ (id)sharedActivityViewer;
+ (void)reopen;
- (id)init;
- (void)dealloc;
- (id)_stopImage;
- (id)_stopPressedImage;
- (id)outlineView:(id)fp8 child:(int)fp12 ofItem:(id)fp16;
- (BOOL)outlineView:(id)fp8 isItemExpandable:(id)fp12;
- (int)outlineView:(id)fp8 numberOfChildrenOfItem:(id)fp12;
- (id)outlineView:(id)fp8 objectValueForTableColumn:(id)fp12 byItem:(id)fp16;
- (BOOL)canCancelActivity:(id)fp8;
- (id)selectedActivitiesThatCanBeCancelled;
- (void)outlineView:(id)fp8 willDisplayCell:(id)fp12 forTableColumn:(id)fp16 item:(id)fp20;
- (void)_cancelClickedItem:(id)fp8;
- (void)_goToClickedItem:(id)fp8;
- (BOOL)outlineView:(id)fp8 selectionShouldChangeFromMouseDownInRow:(int)fp12 tableColumn:(id)fp16;
- (void)setShouldExpand:(BOOL)fp8 fromExpandCollapseNotification:(id)fp12;
- (void)outlineViewItemDidExpand:(id)fp8;
- (void)outlineViewItemDidCollapse:(id)fp8;
- (void)sortAll;
- (void)_reloadNow;
- (void)_startPendingReloadIfNecessary;
- (void)_reloadItemSoonDeep:(id)fp8;
- (void)_reloadItemSoonFlat:(id)fp8;
- (void)flatChangeMadeToActivity:(id)fp8;
- (void)deepChangeMadeToActivity:(id)fp8;
- (void)removedChildrenOfActivity:(id)fp8;
- (void)cut:(id)fp8;
- (BOOL)canCopy;
- (void)copy:(id)fp8;
- (void)paste:(id)fp8;
- (void)delete:(id)fp8;
- (BOOL)canCancel;
- (void)stopLoading:(id)fp8;
- (void)cancel:(id)fp8;
- (BOOL)validateUserInterfaceItem:(id)fp8;
- (void)windowWillClose:(id)fp8;
- (struct _NSRect)windowWillUseStandardFrame:(id)fp8 defaultFrame:(struct _NSRect)fp12;
- (void)_setUpWindow;
- (void)_ensureNibLoaded;
- (void)expandPendingItems;
- (void)showActivity:(id)fp8;
- (void)addTopLevelActivity:(id)fp8;
- (void)removeTopLevelActivity:(id)fp8;

@end

