/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface AddressBookMatch : NSObject
{
    NSString *value;
    NSString *property;
    NSString *key;
    NSString *identifier;
}

- (id)initWithValue:(id)fp8 property:(id)fp12 key:(id)fp16 identifier:(id)fp20;
- (id)description;
- (void)dealloc;

@end

