/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PreferencesModule.h"

@class NSButton, NSComboBox, NSPopUpButton, NSTextField;

@interface AdvancedPreferences : PreferencesModule
{
    NSPopUpButton *styleSheetPopUp;
    NSButton *minFontSizeCheckbox;
    NSComboBox *minFontSizeComboBox;
    NSButton *tabToAllButton;
    NSTextField *tabToAllOptionHint;
    NSButton *openProxyPreferencesButton;
    NSButton *includeDevelopMenuButton;
}

- (id)highResolutionImageName;
- (void)sendNetworkPrefEventsToPSN:(struct ProcessSerialNumber)fp8;
- (void)didLaunchApplication:(id)fp8;
- (void)openProxyPreferences:(id)fp8;
- (void)setStyleSheetPathPreference:(id)fp8;
- (id)styleSheetPathPreference;
- (void)updateStyleSheetMenu;
- (void)takeStyleSheetFromMenuItem:(id)fp8;
- (void)disableUserStyleSheet:(id)fp8;
- (void)choseStyleSheetFromPanel:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)chooseStyleSheetFromFileBrowser:(id)fp8;
- (void)awakeFromNib;
- (void)updateMinFontSizeViews;
- (void)updateTabToAllViews;
- (void)keyboardUIModeDidChange:(id)fp8;
- (void)updateProxiesButton;
- (void)toggleUseMinimumFontSize:(id)fp8;
- (int)sanityCheckMinimumFontSize:(int)fp8;
- (void)takeMinimumFontSizeFrom:(id)fp8;
- (void)comboBoxSelectionDidChange:(id)fp8;
- (void)control:(id)fp8 didFailToValidatePartialString:(id)fp12 errorDescription:(id)fp16;
- (void)toggleTabToAll:(id)fp8;
- (void)toggleIncludeDevelopMenu:(id)fp8;
- (void)updateIncludeDevelopMenuButton;
- (void)initializeFromDefaults;
- (BOOL)isResizable;
- (void)moduleWillBeRemoved;
- (void)moduleWasInstalled;
- (id)helpAnchor;

@end

