/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AppController.h"

@interface AppController (DeveloperExtras)
- (void)showSnippetEditor:(id)fp8;
- (void)toggleCachesDisabled:(id)fp8;
- (BOOL)validate_toggleCachesDisabled:(id)fp8;
- (void)toggleImagesDisabled:(id)fp8;
- (BOOL)validate_toggleImagesDisabled:(id)fp8;
- (void)toggleStylesDisabled:(id)fp8;
- (BOOL)validate_toggleStylesDisabled:(id)fp8;
- (void)toggleJavaScriptDisabled:(id)fp8;
- (BOOL)validate_toggleJavaScriptDisabled:(id)fp8;
- (void)toggleRunawayJavaScriptTimerDisabled:(id)fp8;
- (BOOL)validate_toggleRunawayJavaScriptTimerDisabled:(id)fp8;
- (void)toggleSiteSpecificHacksDisabled:(id)fp8;
- (BOOL)validate_toggleSiteSpecificHacksDisabled:(id)fp8;
@end

