/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AppController.h"

@interface AppController (DebugExtras)
- (void)toggleUseATSUForAllTextDrawing:(id)fp8;
- (void)toggleUnsubmittedFormTextConfirmationsDisabled:(id)fp8;
- (BOOL)validate_toggleUnsubmittedFormTextConfirmationsDisabled:(id)fp8;
- (void)toggleClickCreatesTab:(id)fp8;
- (BOOL)validate_toggleClickCreatesTab:(id)fp8;
- (BOOL)validate_toggleWebClipWidgetDebugMode:(id)fp8;
- (void)toggleWebClipWidgetDebugMode:(id)fp8;
- (void)toggleLogJavaScriptExceptions:(id)fp8;
- (BOOL)validate_toggleLogJavaScriptExceptions:(id)fp8;
@end

