/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSUserInterfaceValidations-Protocol.h"

@class BrowserSessionPersistentState, BrowserWindowPersistentState, NSMenu, NSMenuItem, NSTimer;

@interface AppController : NSObject <NSUserInterfaceValidations>
{
    NSMenu *historyMenu;
    NSMenuItem *bookmarksMenuItem;
    NSMenuItem *windowMenuItem;
    NSMenuItem *textEncodingMenuItem;
    NSMenuItem *releaseNotesMenuItem;
    NSMenu *_dockMenu;
    NSMenuItem *_shiftedCloseMenuItem;
    NSMenuItem *_shiftedCloseAllMenuItem;
    BrowserWindowPersistentState *_lastClosedWindowState;
    BrowserSessionPersistentState *_lastSessionState;
    NSTimer *_saveSessionStateTimer;
    BOOL _closeKeyEquivalentClosesTab;
    BOOL _textEncodingMenuLoaded;
    BOOL _awaitingModalCloseAllConfirmation;
    BOOL _isTerminating;
    BOOL _lastSessionStateComputed;
    BOOL _startingBonjourSearch;
    int _bookmarksMenuItemIndex;
    BOOL _antiPhishingServiceInitialized;
}

+ (id)sharedAppController;
+ (BOOL)hasAppleIPAddress;
+ (void)initialize;
+ (void)muteAudio:(BOOL)fp8;
+ (id)webWidgetIdentifier;
- (void)awakeFromNib;
- (void)dealloc;
- (void)applicationDidBecomeActive:(id)fp8;
- (BOOL)applicationShouldOpenUntitledFile:(id)fp8;
- (BOOL)applicationOpenUntitledFile:(id)fp8;
- (void)applicationDidFinishLaunching:(id)fp8;
- (void)showReleaseNotes:(id)fp8;
- (unsigned int)applicationShouldTerminate:(id)fp8;
- (void)applicationWillTerminate:(id)fp8;
- (BOOL)isTerminating;
- (BOOL)application:(id)fp8 openFile:(id)fp12;
- (void)application:(id)fp8 runTest:(unsigned int)fp12 duration:(double)fp16;
- (BOOL)applicationShouldHandleReopen:(id)fp8 hasVisibleWindows:(BOOL)fp12;
- (id)applicationDockMenu:(id)fp8;
- (void)menuNeedsUpdate:(id)fp8;
- (BOOL)menuHasKeyEquivalent:(id)fp8 forEvent:(id)fp12 target:(id *)fp16 action:(SEL *)fp20;
- (BOOL)validateUserInterfaceItem:(id)fp8;
- (void)addBookmarksForTabs:(id)fp8;
- (void)confirmEmptyCache:(id)fp8;
- (void)confirmResetSafari:(id)fp8;
- (void)exportBookmarks:(id)fp8;
- (void)importBookmarks:(id)fp8;
- (void)consolidateTabsAndWindows:(id)fp8;
- (void)reopenLastSession:(id)fp8;
- (void)reopenLastWindow:(id)fp8;
- (void)showAcknowledgments:(id)fp8;
- (void)showActivity:(id)fp8;
- (void)showDownloads:(id)fp8;
- (void)showPlugins:(id)fp8;
- (void)showPreferences:(id)fp8;
- (void)showShortcuts:(id)fp8;
- (void)toggleJavaScriptCanNotOpenWindows:(id)fp8;
- (void)togglePrivateBrowsing:(id)fp8;
- (void)togglePrivateBrowsingWithoutConfirmation:(id)fp8;
- (void)browserWindowWillClose:(id)fp8;
- (void)sessionStateDidChange;
- (BOOL)authorizeParent;
- (BOOL)setParentalControlsEnabled:(BOOL)fp8;
- (id)parentalControlsAuthorizationWithFlags:(unsigned long)fp8;
- (BOOL)commandClickMakesTabs;
- (void)setCommandClickMakesTabs:(BOOL)fp8;
- (void)setCloseKeyEquivalentClosesTab:(BOOL)fp8;
- (id)cachesDirectoryPath;
- (BOOL)confirmClosingAllWindows;
- (id)displayNameForURL:(id)fp8 withTitle:(id)fp12;
- (void)emptyCache;
- (id)localizedHelpBookName;
- (void)resetTextEncodingMenu;
- (id)settingsDirectoryPath;
- (id)windowMenuItem;
- (void)initializeAntiPhishingServiceIfNeeded;

@end

