/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "AppController.h"

@interface AppController (FileInternal)
+ (id)_appSubdirectoryForUserDirectory:(unsigned int)fp8 useBundleIdentifier:(BOOL)fp12;
+ (id)_settingsDirectoryPath;
- (BOOL)_openUntitledFileWhileLaunching:(BOOL)fp8;
- (void)_cancelModalCloseAllConfirmation;
- (id)_closeCurrentTabMenuItem;
- (id)_closeInactiveTabsMenuItem;
- (id)_closeMenuItem;
- (id)_closeAllMenuItem;
- (void)_computeLastSessionStateIfNecessary;
- (BOOL)_confirmStealthMode;
- (void)_parentalControlsDidChange;
- (void)_defaultsDidChange;
- (id)_editMenu;
- (void)_enableStealthMode;
- (id)_fileMenu;
- (void)_handleURLEvent:(id)fp8 withReplyEvent:(id)fp12;
- (void)_hideBookmarksMenu;
- (id)_lastSessionFile;
- (id)_lastSessionState;
- (void)_newWindowFromDock:(id)fp8;
- (BOOL)_OKToCloseBrowserWindowsForExplicitCloseAllCommand:(BOOL)fp8;
- (void)_performDelayedLaunchOperations;
- (void)_savePendingData:(id)fp8;
- (void)_saveSessionNow;
- (void)_reopenWindows;
- (void)_setKeyEquivalentForMenuItem:(id)fp8 toIncludeShiftKey:(BOOL)fp12;
- (void)_showBookmarksMenu;
- (void)_showHTMLResourceFile:(id)fp8;
- (void)_showResourceFileWithName:(id)fp8 extension:(id)fp12;
- (void)_startBonjourSearchIfNecessary;
- (void)_togglePrivateBrowsingSuppressingConfirmation:(BOOL)fp8;
- (void)_updateCloseKeyEquivalents;
- (BOOL)_updateLastClosedWindowStateForWindow:(id)fp8;
- (void)_updateTextEncodingMenu;
- (BOOL)_userHasEmptyHomePage;
@end

