/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PreferencesModule.h"

@class NSButton, NSPopUpButton, NSTextField;

@interface AppearancePreferences : PreferencesModule
{
    NSTextField *standardFontSample;
    NSTextField *monospacedFontSample;
    NSButton *selectStandardFontButton;
    NSButton *selectMonospacedFontButton;
    NSButton *displayImagesCheckbox;
    NSPopUpButton *defaultCharacterSetMenu;
}

- (void)updateFontSampleField:(int)fp8;
- (void)updateFontSampleFields;
- (void)chooseFont:(int)fp8;
- (void)chooseStandardFont:(id)fp8;
- (void)chooseMonospacedFont:(id)fp8;
- (unsigned int)validModesForFontPanel:(id)fp8;
- (void)changeFont:(id)fp8;
- (void)updateDefaultCharacterSetPopup;
- (void)takeDefaultCharacterSetFrom:(id)fp8;
- (void)toggleDisplayImages:(id)fp8;
- (void)initializeFromDefaults;
- (void)awakeFromNib;
- (void)moduleWillBeRemoved;
- (BOOL)isResizable;
- (id)helpAnchor;

@end

