/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PreferencesModule.h"

@class MiscFormsDataEditor, NSButton, PasswordsEditor;

@interface AutoFillPreferences : PreferencesModule
{
    NSButton *autoFillAddressFieldsCheckBox;
    NSButton *autoFillPasswordsCheckBox;
    NSButton *autoFillOtherFormsCheckBox;
    NSButton *editMyCardButton;
    NSButton *editPasswordsButton;
    NSButton *editOtherFormDataButton;
    MiscFormsDataEditor *miscFormsDataEditor;
    PasswordsEditor *passwordsEditor;
}

- (void)updateViews;
- (void)toggleAutoFillAddressFields:(id)fp8;
- (void)toggleAutoFillPasswords:(id)fp8;
- (void)toggleAutoFillOtherForms:(id)fp8;
- (void)editMyCard:(id)fp8;
- (void)editPasswords:(id)fp8;
- (void)editOtherFormData:(id)fp8;
- (void)initializeFromDefaults;
- (BOOL)isResizable;
- (id)helpAnchor;

@end

