/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "Banner.h"

@interface Banner (FileInternal)
- (void)_advanceAnimation;
- (struct _NSRect)_computeAnimationEnclosingRect;
- (id)_createBannerView;
- (void)_moveBannerIntoPlace:(BOOL)fp8 withAnimation:(BOOL)fp12;
- (void)_populateBannerViewFromNib:(id)fp8;
- (void)_setViewBelowBanner:(id)fp8;
@end

