/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "Banner.h"

@class FadingOverlay, NSAnimation, WebView;

@interface BannerWithOverlay : Banner
{
    FadingOverlay *_overlay;
    WebView *_webView;
    BOOL _overlayDisabled;
    BOOL _overlayRemovedWhileWebViewOffscreen;
    NSAnimation *_fadeInAnimation;
}

+ (BOOL)overlayAppearsAutomatically;
+ (BOOL)overlayIgnoresMouseEvents;
+ (Class)overlayViewClass;
- (void)dealloc;
- (id)init;
- (id)initWithWebView:(id)fp8;
- (void)webViewDidMoveToWindow;
- (void)viewBelowBannerWasResizedFromFrame:(struct _NSRect)fp8 animationProgress:(float)fp24 installing:(BOOL)fp28;
- (void)animationDidEnd:(id)fp8;
- (void)barBackgroundDidEndLiveResize:(id)fp8;
- (void)barBackgroundWillStartLiveResize:(id)fp8;
- (void)detachWebView;
- (void)fadingOverlayNeedsUpdateInRect:(struct _NSRect)fp8;
- (void)hideOverlay;
- (BOOL)isOverlayDisabled;
- (BOOL)isShowingFadingOverlay;
- (id)overlay;
- (void)setOverlayDisabled:(BOOL)fp8;
- (BOOL)showOverlay;
- (void)willAttachOverlay;
- (void)willDetachOverlay;
- (void)startFadeIn;
- (id)webView;

@end

