/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BannerWithOverlay.h"

@interface BannerWithOverlay (FileInternal)
- (void)_animateFadeIn:(id)fp8;
- (id)_fadingOverlayTargetView;
@end

