/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BonjourController.h"

@interface BonjourController (FileInternal)
- (BOOL)_addServicesFromCategory:(id)fp8 toMenu:(id)fp12;
- (void)_goToContentItem:(id)fp8 windowPolicy:(int)fp12 tabLocation:(id)fp16;
- (id)_goToURL:(id)fp8 windowPolicy:(int)fp12 tabLocation:(id)fp16;
- (BOOL)_multipleNonEmptyCategories;
- (id)_nameToDisplayForService:(id)fp8;
- (void)_reportErrorForServiceName:(id)fp8;
- (void)_serviceMenuItemSelected:(id)fp8;
- (void)_setServiceToVisit:(id)fp8 windowPolicy:(int)fp12 tabLocation:(id)fp16;
- (void)_setTabLocationForServiceToVisit:(id)fp8;
- (id)_titleForCategory:(id)fp8;
- (void)_updateInterface;
- (void)_setInitiallyCollapsed:(BOOL)fp8 forCategory:(id)fp12;
- (id)_keyForCollapsedPreferenceForCategory:(id)fp8;
@end

