/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "BookmarkSource-Protocol.h"

@class NSMutableDictionary, NSMutableSet;

@interface BookmarkSource : NSObject <BookmarkSource>
{
    NSMutableSet *_updatedBookmarkSourceMenus;
    NSMutableDictionary *_tabLocationsForBookmarkSourceMenus;
}

- (void)dealloc;
- (void)addBookmarkSourceMenu:(id)fp8 withTabLocation:(id)fp12;
- (id)tabLocationForMenu:(id)fp8;
- (void)removeBookmarkSourceMenu:(id)fp8;
- (void)setAllMenusNeedRealUpdate;
- (void)setMenu:(id)fp8 needsRealUpdate:(BOOL)fp12;
- (BOOL)menuNeedsRealUpdate:(id)fp8;
- (void)refreshContents;
- (BOOL)canCopyContents;
- (BOOL)canDeleteContents;
- (void)deleteContentItems:(id)fp8 withUndoManager:(id)fp12;
- (BOOL)contentItemCanHaveChildren:(id)fp8;
- (id)child:(unsigned int)fp8 ofContentItem:(id)fp12;
- (unsigned int)numberOfChildrenOfContentItem:(id)fp8;
- (id)parentOfContentItem:(id)fp8;
- (void)didCollapseContentItem:(id)fp8;
- (void)didExpandContentItem:(id)fp8;
- (id)contentItemsToInitiallyExpand;
- (id)contentItemsToExpandOnReload;
- (id)bookmarkFromContentItem:(id)fp8;
- (void)goToContentItem:(id)fp8 tabLocation:(id)fp12;
- (void)goToContentItemInNewWindow:(id)fp8;
- (void)goToContentItemInNewTab:(id)fp8 tabLocation:(id)fp12;
- (void)goToChildrenOfContentItemInTabs:(id)fp8 tabLocation:(id)fp12;
- (BOOL)canGoToContentItem:(id)fp8;
- (id)bookmarksFromContentItems:(id)fp8;
- (id)bookmarkSourceImage;
- (id)addressStringForContentItem:(id)fp8;
- (id)titleStringForContentItem:(id)fp8;
- (id)imageForContentItem:(id)fp8;
- (BOOL)shouldShowRSSLabelForContentItem:(id)fp8;
- (BOOL)isFilteredFromOtherSources;
- (id)bookmarkSourceMenuTitle;

@end

