/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "FileLockerDelegate-Protocol.h"
#import "SafariSyndicationDelegate-Protocol.h"
#import "SpotlightDataSource-Protocol.h"

@class FileLocker, NSMenu, NSMenuItem, NSMutableSet, WebBookmark, WebBookmarkGroup;

@interface BookmarksController : NSObject <FileLockerDelegate, SafariSyndicationDelegate, SpotlightDataSource>
{
    WebBookmarkGroup *_bookmarks;
    WebBookmark *_bookmarksBarCollection;
    WebBookmark *_bookmarksMenuCollection;
    WebBookmark *_historyCollection;
    NSMenu *_bookmarksMenu;
    BOOL _menuGood;
    BOOL _menuIncludesBonjour;
    BOOL _menuIncludesAddressBook;
    BOOL _menuIncludesBookmarksBar;
    BOOL _collectionsIncludeBonjour;
    BOOL _collectionsIncludeAddressBook;
    BOOL _RSSBookmarksInMenuAreSubscribed;
    BOOL _RSSBookmarksInBarAreSubscribed;
    BOOL _sendRSSUpdates;
    BOOL _RSSUpdatePending;
    FileLocker *_fileLocker;
    struct timespec _bookmarksFileDate;
    long long _bookmarksFileSize;
    BOOL _reloading;
    BOOL _savePending;
    NSMutableSet *_parentalControlDomains;
    NSMutableSet *_pendingSpotlightCacheAdditions;
    NSMutableSet *_pendingSpotlightCacheDeletions;
    struct timespec _bookmarksFileDateForSpotlight;
    long long _bookmarksFileSizeForSpotlight;
    NSMenuItem *_lastBuiltInBookmarksMenuItem;
}

+ (id)sharedController;
+ (id)_favoritesTitle;
+ (id)_bookmarksMenuCollectionTitle;
+ (id)historyProxyTitle;
+ (id)addressBookProxyTitle;
+ (id)bonjourProxyTitle;
+ (id)RSSProxyTitle;
+ (id)smallImageForBookmarkList;
+ (id)imageForBookmark:(id)fp8;
+ (id)bookmarkSourceForProxyIdentifier:(id)fp8;
- (id)_standardBookmarksFilePath;
- (void)_removeAllBookmarksFromMenu;
- (void)addChildrenOfBookmark:(id)fp8 withTabLocation:(id)fp12 toMenu:(id)fp16 includeUnreadRSSCounts:(BOOL)fp20;
- (id)_addMenuItemForBookmark:(id)fp8 withTabLocation:(id)fp12 toMenu:(id)fp16 includeUnreadRSSCount:(BOOL)fp20;
- (id)addMenuItemForBookmark:(id)fp8 withTabLocation:(id)fp12 toMenu:(id)fp16 includeUnreadRSSCount:(BOOL)fp20;
- (void)goToNthFavoriteLeaf:(int)fp8;
- (void)addSubmenuForBookmarkSource:(id)fp8;
- (void)addFavoritesSubmenu;
- (void)addSpecialBookmarkSourcesToMenu;
- (void)_addBookmarksToMenu;
- (void)menuNeedsUpdate:(id)fp8;
- (BOOL)menuHasKeyEquivalent:(id)fp8 forEvent:(id)fp12 target:(id *)fp16 action:(SEL *)fp20;
- (BOOL)rememberBookmarksFileInfo;
- (BOOL)bookmarksFileHasChanged;
- (BOOL)reloadBookmarksFromFileIfChanged;
- (void)unlockFileLocker;
- (void)savePendingChanges;
- (int)fileLocker:(id)fp8 actionForApparentlyAbandonedLock:(id)fp12 onAttempt:(int)fp16;
- (void)fileLocker:(id)fp8 lockWasStolen:(id)fp12;
- (void)tellUserThatISyncWon;
- (void)tellUserThatExternalChangePreemptedLocalChange;
- (void)savePendingChangesWhenever;
- (BOOL)savePendingChangesSoon;
- (void)_resetMenu;
- (id)_feedBookmarksWithURLString:(id)fp8 ignoreFilter:(BOOL)fp12;
- (BOOL)_feedBookmarksMightBeAffectedByNotification:(id)fp8;
- (void)_receivedBookmarksChangedNotification:(id)fp8;
- (void)_receivedBookmarksWereReloadedNotification:(id)fp8;
- (void)_receivedDefaultsChangedNotification:(id)fp8;
- (void)mergeBookmarksFrom:(id)fp8 to:(id)fp12;
- (void)_updateDisplayedTitlesForBuiltInBookmarks:(id)fp8;
- (void)mergeBuiltInBookmarks;
- (void)exportBookmarks;
- (id)importBookmarksFrom:(id)fp8;
- (int)importFavoritesFrom:(id)fp8 intoBookmarksFolder:(id)fp12;
- (void)importIEFavorites;
- (id)_computeNetscapeAndMozillaBookmarksPath;
- (void)importNetscapeAndMozillaFavorites;
- (id)collectionNamed:(id)fp8;
- (id)uniqueUntitledCollectionName;
- (id)dateForImportFolderName;
- (id)uniqueImportFolderName;
- (BOOL)canImportBookmarks;
- (void)importBookmarks;
- (void)addBookmark:(id)fp8 title:(id)fp12;
- (void)addBookmarksForPagesInWhiteList:(id)fp8 thatAreNotInArray:(id)fp12;
- (id)bookmarkLeavesForBookmarks:(id)fp8;
- (id)initWithBookmarksMenu:(id)fp8;
- (id)allBookmarks;
- (id)bookmarksBarCollection;
- (id)bookmarksMenuCollection;
- (id)historyCollection;
- (void)dealloc;
- (BOOL)_menuContainsBookmark:(id)fp8;
- (BOOL)_favoritesContainsBookmark:(id)fp8;
- (void)_sendFavoritesChangedNotification;
- (BOOL)bookmark:(id)fp8 isFolderTitled:(id)fp12;
- (id)findOrCreateBookmarkSourceWithStoredTitle:(id)fp8 displayedTitle:(id)fp12 unlocalizedDisplayedTitle:(id)fp16 atIndex:(unsigned int)fp20;
- (void)updateBookmarkSources;
- (id)favoriteBookmarks;
- (void)addFavoriteBookmark:(id)fp8 atIndex:(int)fp12;
- (void)_bookmarksFileChangedNotification:(id)fp8;
- (BOOL)visitFavoriteBookmarkFromKeyEvent:(id)fp8;
- (void)_subscribeInMailToRSSBookmark:(id)fp8;
- (void)_newBookmarkSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (id)_addBookmarkLocation:(id)fp8 withTitle:(id)fp12 toMenu:(id)fp16;
- (void)recursivelyAddChildFoldersOf:(id)fp8 toMenu:(id)fp12 withIndentationLevel:(unsigned int)fp16;
- (void)_setUpPopUpMenuForNewBookmarksController:(id)fp8 favoritesOnly:(BOOL)fp12;
- (void)redisplayPage:(id)fp8;
- (void)redisplayPages:(id)fp8;
- (void)subscribe:(BOOL)fp8 toFeed:(id)fp12;
- (id)_treeOfSubscribedRSSBookmarks;
- (void)_passSubscribedBookmarksToSyndication;
- (void)setUpSyndicationDelegate;
- (BOOL)isBookmarkedURL:(id)fp8;
- (BOOL)shouldShowUnreadRSSCountsForCollection:(id)fp8;
- (void)_addLeafBookmark:(id)fp8 toSpotlightCacheArray:(id)fp12;
- (void)_addBookmarksFromArray:(id)fp8 toSpotlightCacheArray:(id)fp12;
- (void)_registerWithSpotlightCacheController;
- (id)itemsToAddForSpotlightDataType:(id)fp8;
- (id)itemsToDeleteForSpotlightDataType:(id)fp8;
- (id)allItemsForSpotlightDataType:(id)fp8;
- (void)resetAdditionsAndDeletionsForSpotlightDataType:(id)fp8;
- (void)updateWillBeginForSpotlightDataType:(id)fp8;
- (void)updateDidEndForSpotlightDataType:(id)fp8;
- (void)_displayNewBookmarksSheetForBookmark:(id)fp8 inWindow:(id)fp12 favoritesOnly:(BOOL)fp16 delegate:(id)fp20;
- (void)displayNewBookmarksSheetForBookmark:(id)fp8 inWindow:(id)fp12;
- (void)displayNewFavoritesSheetForBookmark:(id)fp8 inWindow:(id)fp12 delegate:(id)fp16;
- (BOOL)isChildAllowedToVisitURL:(id)fp8;
- (void)feed:(id)fp8 unreadCountChanged:(int)fp12;
- (void)bookmarkUUID:(id)fp8 unreadCountChanged:(int)fp12;
- (void)bookmarkFeed:(id)fp8;

@end

