/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSResponder.h"

#import "WebDocumentSearching-Protocol.h"

@class BrowserWebView, BrowserWindow, HistoryThumbnailView, NSControl, NSMutableArray, NSMutableDictionary, NSSet, NSString, NSTableColumn, NSUndoManager, OutlineViewPlus, SplitView, TableViewPlus, WebBookmark;

@interface BookmarksViewController : NSResponder <WebDocumentSearching>
{
    SplitView *tableAndOutlineSplitView;
    TableViewPlus *collectionsTableView;
    OutlineViewPlus *outlineView;
    SplitView *collectionsAndThumbnailSplitView;
    HistoryThumbnailView *thumbnailImageView;
    NSControl *newCollectionControl;
    NSControl *newContentsFolderControl;
    BrowserWebView *_parentWebView;
    BrowserWindow *_parentWindow;
    NSTableColumn *_hiddenAddressColumn;
    NSUndoManager *_undoManager;
    WebBookmark *_selectedCollection;
    BOOL _selectedCollectionInitialized;
    int _filterSearchScope;
    NSString *_filterSearchString;
    NSMutableArray *_filterSearchResults;
    NSSet *_filterSearchCachedTextMatches;
    NSMutableDictionary *_filterSearchCollections;
    BOOL _bookmarkChangeIsExpected;
    BOOL _isProgrammaticallyResizingTableAndOutlineSplitView;
    BOOL _nibIsLoaded;
    BOOL _setupComplete;
    BOOL _outlineViewWasFocused;
    BOOL _showUnreadRSSCountsInBar;
    BOOL _showUnreadRSSCountsInMenu;
}

+ (float)bottomGradientHeight;
+ (id)draggedBookmarks;
- (void)addCollection:(id)fp8;
- (void)addContentsFolder:(id)fp8;
- (void)copy:(id)fp8;
- (void)cut:(id)fp8;
- (void)delete:(id)fp8;
- (void)editSelectedBookmarkAddress:(id)fp8;
- (void)editSelectedBookmarkTitle:(id)fp8;
- (void)editSelectedCollectionTitle:(id)fp8;
- (void)newBookmarkFolder:(id)fp8;
- (void)paste:(id)fp8;
- (void)takeFilterSearchStringFrom:(id)fp8;
- (BOOL)searchFor:(id)fp8 direction:(BOOL)fp12 caseSensitive:(BOOL)fp16 wrap:(BOOL)fp20;
- (int)numberOfRowsInTableView:(id)fp8;
- (BOOL)tableView:(id)fp8 acceptDrop:(id)fp12 row:(int)fp16 dropOperation:(unsigned int)fp20;
- (void)tableView:(id)fp8 draggedImage:(id)fp12 endedAt:(struct _NSPoint)fp16 operation:(unsigned int)fp24;
- (unsigned int)tableView:(id)fp8 draggingSourceOperationMaskForLocal:(BOOL)fp12;
- (id)tableView:(id)fp8 namesOfPromisedFilesDroppedAtDestination:(id)fp12 forDraggedRowsWithIndexes:(id)fp16;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (void)tableView:(id)fp8 setObjectValue:(id)fp12 forTableColumn:(id)fp16 row:(int)fp20;
- (unsigned int)tableView:(id)fp8 validateDrop:(id)fp12 proposedRow:(int)fp16 proposedDropOperation:(unsigned int)fp20;
- (BOOL)tableView:(id)fp8 writeRowsWithIndexes:(id)fp12 toPasteboard:(id)fp16;
- (void)tableViewSelectionDidChange:(id)fp8;
- (BOOL)tableView:(id)fp8 keyDown:(id)fp12;
- (id)tableView:(id)fp8 menuForEvent:(id)fp12 inRow:(int)fp16 tableColumn:(id)fp20;
- (BOOL)tableView:(id)fp8 shouldEditOnDoubleClick:(id)fp12 inRow:(int)fp16 tableColumn:(id)fp20;
- (BOOL)tableView:(id)fp8 shouldEditOnSingleClick:(id)fp12 inRow:(int)fp16 tableColumn:(id)fp20;
- (BOOL)tableView:(id)fp8 shouldEditTableColumn:(id)fp12 row:(int)fp16;
- (BOOL)tableView:(id)fp8 shouldSelectRow:(int)fp12;
- (float)tableView:(id)fp8 heightOfRow:(int)fp12;
- (id)tableColumn:(id)fp8 dataCellForRow:(int)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forTableColumn:(id)fp16 row:(int)fp20;
- (BOOL)outlineView:(id)fp8 acceptDrop:(id)fp12 item:(id)fp16 childIndex:(int)fp20;
- (id)outlineView:(id)fp8 child:(int)fp12 ofItem:(id)fp16;
- (void)outlineView:(id)fp8 draggedImage:(id)fp12 endedAt:(struct _NSPoint)fp16 operation:(unsigned int)fp24;
- (unsigned int)outlineView:(id)fp8 draggingSourceOperationMaskForLocal:(BOOL)fp12;
- (BOOL)outlineView:(id)fp8 isItemExpandable:(id)fp12;
- (id)outlineView:(id)fp8 namesOfPromisedFilesDroppedAtDestination:(id)fp12 forDraggedItems:(id)fp16;
- (int)outlineView:(id)fp8 numberOfChildrenOfItem:(id)fp12;
- (id)outlineView:(id)fp8 objectValueForTableColumn:(id)fp12 byItem:(id)fp16;
- (void)outlineView:(id)fp8 setObjectValue:(id)fp12 forTableColumn:(id)fp16 byItem:(id)fp20;
- (unsigned int)outlineView:(id)fp8 validateDrop:(id)fp12 proposedItem:(id)fp16 proposedChildIndex:(int)fp20;
- (BOOL)outlineView:(id)fp8 writeItems:(id)fp12 toPasteboard:(id)fp16;
- (id)outlineView:(id)fp8 dragImageForRowsWithIndexes:(id)fp12 tableColumns:(id)fp16 event:(id)fp20 offset:(struct _NSPoint *)fp24;
- (BOOL)outlineView:(id)fp8 shouldTypeSelectForEvent:(id)fp12 withCurrentSearchString:(id)fp16;
- (BOOL)outlineView:(id)fp8 keyDown:(id)fp12;
- (id)outlineView:(id)fp8 menuForEvent:(id)fp12 inRow:(int)fp16 tableColumn:(id)fp20;
- (BOOL)outlineView:(id)fp8 selectionShouldChangeFromMouseDownInRow:(int)fp12 tableColumn:(id)fp16;
- (BOOL)outlineView:(id)fp8 shouldEditOnDoubleClick:(id)fp12 inRow:(int)fp16 tableColumn:(id)fp20;
- (BOOL)outlineView:(id)fp8 shouldEditOnSingleClick:(id)fp12 inRow:(int)fp16 tableColumn:(id)fp20;
- (BOOL)outlineView:(id)fp8 shouldEditTableColumn:(id)fp12 item:(id)fp16;
- (void)outlineView:(id)fp8 willDisplayCell:(id)fp12 forTableColumn:(id)fp16 item:(id)fp20;
- (void)outlineViewItemDidCollapse:(id)fp8;
- (void)outlineViewItemDidExpand:(id)fp8;
- (void)outlineViewSelectionDidChange:(id)fp8;
- (void)splitViewDidResizeSubviews:(id)fp8;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)splitView:(id)fp8 constrainMinCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (void)splitView:(id)fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (void)detachWebView;
- (void)switchedIntoView;
- (void)willSwitchOutOfView;
- (id)outlineView;
- (id)undoManager;
- (void)setUndoManager:(id)fp8;
- (id)viewBelowFindBanner;
- (BOOL)revealFavorite:(id)fp8 expandChildren:(BOOL)fp12;
- (void)removeBookmarks:(id)fp8;
- (BOOL)revealCollection:(id)fp8;
- (unsigned int)searchResultsCount;
- (void)_insertBorderLineBeneathScrollView:(id)fp8;
- (void)awakeFromNib;
- (void)dealloc;
- (BOOL)validateUserInterfaceItem:(id)fp8;

@end

