/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BookmarkURLConfirmer.h"

@interface BookmarkURLConfirmer (FileInternal)
+ (BOOL)_bookmarkRequiresConfirmation:(id)fp8 inWindow:(id)fp12;
+ (void)_performCallbackWithDelegate:(id)fp8 didEndSelector:(SEL)fp12 bookmark:(id)fp16 result:(BOOL)fp20 contextInfo:(void *)fp24;
- (void)_beginConfirmationModalForWindow:(id)fp8;
- (id)_initWithBookmark:(id)fp8 modalDelegate:(id)fp12 didEndSelector:(SEL)fp16 contextInfo:(void *)fp20;
- (void)_performCallbackWithResult:(BOOL)fp8;
- (void)_URLConfirmationAlertDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
@end

