/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserCoachMark.h"

@interface BrowserCoachMark (FileInternal)
- (void)_animateFadeOut;
- (void)_animatePulse;
- (void)_startPulse;
- (void)_startFadeOut:(id)fp8;
@end

