/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserWebView.h"

@interface BrowserWebView (FileInternal)
+ (void)_addWebViewToClose:(id)fp8;
+ (void)_closeNextWebViewBatch;
+ (void)_decrementLoadingCount;
+ (void)_dequeueRequest;
- (void)_addFavoriteForParentControlledPageInFrame:(id)fp8;
- (BOOL)_canParentalControlledChildNavigateToURL:(id)fp8 withAction:(id)fp12;
- (void)_closeDataSources:(id)fp8;
- (BOOL)_confirmIncreaseInQuotaWithMessage:(id)fp8 informativeText:(id)fp12;
- (void)_confirmSendSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (BOOL)_contentsPrecludeChangingTextSize;
- (void)_decidePolicyForAction:(id)fp8 request:(id)fp12 frame:(id)fp16 newFrameName:(id)fp20 decisionListener:(id)fp24;
- (BOOL)_displayRequestedSheetSoonIfAppropriate;
- (void)_displayRequestedSheetNow;
- (void)_displayUIForAbortedLoadAttemptForURL:(id)fp8 withTitle:(id)fp12 message:(id)fp16;
- (void)_goBackFromParentalControlsErrorPage;
- (void)_goToURL:(id)fp8 withFallbackURLs:(id)fp12;
- (void)_hideBanner:(id)fp8 allowingAnimation:(BOOL)fp12;
- (void)_informDecisionListener:(id)fp8 ofPolicyDecision:(int)fp12;
- (id)_javaScriptDialogTitleForFrame:(id)fp8;
- (void)_loadBookmarksNibIfNecessary;
- (id)_mouseoverTextForElement:(id)fp8 modifierFlags:(unsigned int)fp12;
- (void)_openFileExternallyWithRequest:(id)fp8 inFrame:(id)fp12;
- (BOOL)_openURLExternallyWithRequest:(id)fp8 inFrame:(id)fp12 displayError:(BOOL)fp16;
- (void)_queueRequest:(id)fp8;
- (id)_removeRequestFromQueue;
- (void)_revealInFinderWithRequest:(id)fp8 inFrame:(id)fp12;
- (void)_searchGoogleWithTextFromErrorPage;
- (void)_selectTabAndOrderFront;
- (void)_setAbortedLoadSheetRequestWithTitle:(id)fp8 message:(id)fp12;
- (void)_setFallbackURLs:(id)fp8;
- (void)_sheetRequestConditionsChanged:(id)fp8;
- (BOOL)_shouldDisplayRequestedSheet;
- (BOOL)_canUseTabWithFeatures:(id)fp8;
- (void)_showBanner:(id)fp8 allowingAnimation:(BOOL)fp12;
- (void)_showErrorPageForURL:(id)fp8 withErrorPageHTML:(id)fp12 inFrame:(id)fp16;
- (void)_showParentalControlsErrorPageForURL:(id)fp8;
- (void)_startObservingNotificationsThatDisplayRequestedSheet;
- (void)_stopObservingNotificationsThatDisplayRequestedSheet;
- (void)_tellListenerToIgnoreContentPolicyAndRelease:(id)fp8;
- (void)_tellListenerToUseContentPolicyAndRelease:(id)fp8;
- (void)_updateProgressBar:(BOOL)fp8;
- (void)_updateStatusInBrowserWindow;
- (id)_userVisibleBundleVersionFromFullVersion:(id)fp8;
@end

