/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface BrowserWindowPersistentState : NSObject
{
    NSMutableArray *_tabURLStrings;
    NSMutableArray *_tabLabels;
    unsigned int _selectedTabIndex;
    struct _NSRect _windowContentRect;
    BOOL _locationBarHidden;
    BOOL _favoritesBarHidden;
    BOOL _tabBarHidden;
    BOOL _statusBarHidden;
    BOOL _isMiniaturized;
}

- (id)init;
- (id)initWithBrowserWindowController:(id)fp8;
- (void)dealloc;
- (BOOL)containsAnyURLs;
- (BOOL)containsAnyRestorableURLs;
- (void)restoreBrowserWindow;
- (id)dictionaryRepresentation;
- (id)initFromDictionaryRepresentation:(id)fp8;

@end

