/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "Window.h"

@class ExtendedValidationCertificateButton, NSString, RolloverImageButton, TitleBarButton;

@interface BrowserWindow : Window
{
    BOOL logAfterNextRedisplay;
    BOOL ignoresOrderFront;
    TitleBarButton *_titleBarButton;
    RolloverImageButton *_lockButton;
    ExtendedValidationCertificateButton *_extendedValidationCertificateButton;
    NSString *_title;
    BOOL _isCapturingMiniWindowImage;
}

+ (id)_lockImage;
- (void)_setTitleBarButton;
- (void)awakeFromNib;
- (void)keyDown:(id)fp8;
- (void)updateCGSWindowTitle;
- (void)_commonAwake;
- (struct _NSRect)_adjustedFrameForSaving:(struct _NSRect)fp8;
- (struct _NSRect)adjustedFrameForCascade:(struct _NSRect)fp8 fromWindow:(id)fp24;
- (BOOL)performKeyEquivalent:(id)fp8;
- (BOOL)willHandleKeyEvent:(id)fp8;
- (void)logFirstPageLoadedAfterNextRedisplay;
- (void)logFirstWindowDrawnAfterNextRedisplay;
- (void)logFirstPageLoaded;
- (void)display;
- (void)displayIfNeeded;
- (void)updateTitle;
- (void)resizeTitleAndExtendedValidationCertificateButton;
- (void)close;
- (void)setTitle:(id)fp8;
- (id)title;
- (BOOL)isKeyWindow;
- (void)setIsCapturingMiniWindowImage:(BOOL)fp8;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (void)setWindowController:(id)fp8;
- (void)flushWindow;
- (BOOL)ignoresOrderFront;
- (void)setIgnoresOrderFront:(BOOL)fp8;
- (void)orderFront:(id)fp8;
- (BOOL)makeFirstResponder:(id)fp8;
- (void)_updateLockButton;
- (void)_updateExtendedValidationCertificateButton;
- (void)_updateSecurityButtons;
- (void)_setUpLockButton;
- (void)_setUpExtendedValidationCertificateButton;
- (void)_setUpSecurityButtons;
- (void)certificateSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_securityButtonClicked:(id)fp8;
- (BOOL)_showingLockButton;
- (BOOL)_showingExtendedValidationCertificateButton;
- (void)setShowingSecurityButtons:(BOOL)fp8;
- (id)accessibilityHitTest:(struct _NSPoint)fp8;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)canBecomeKeyWindow;
- (BOOL)canBecomeMainWindow;
- (id)currentTabViewItem;
- (void)setCurrentTabViewItem:(id)fp8;
- (id)orderedTabViewItems;
- (void)insertInOrderedTabViewItems:(id)fp8;
- (void)insertInOrderedTabViewItems:(id)fp8 atIndex:(unsigned int)fp12;
- (void)replaceInOrderedTabViewItems:(id)fp8 atIndex:(unsigned int)fp12;
- (void)removeFromOrderedTabViewItemsAtIndex:(unsigned int)fp8;
- (BOOL)rolloverTrackingButton:(id)fp8 shouldUseRolloverAppearance:(BOOL)fp12;

@end

