/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSToolbar.h"

@interface BrowserToolbar : NSToolbar
{
}

- (BOOL)_allowsDisplayMode:(unsigned int)fp8;
- (BOOL)_allowsSizeMode:(unsigned int)fp8;
- (id)_customMetrics;
- (BOOL)_drawsBackground;

@end

