/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTabViewItem.h"

@class BrowserWebView, NSString, TabBarView, TabButton;

@interface BrowserTabViewItem : NSTabViewItem
{
    TabBarView *_tabBarView;
    TabButton *_button;
    NSString *_searchFieldText;
    NSString *_urlFromScript;
    BrowserWebView *_webView;
}

- (id)initWithTabBarView:(id)fp8;
- (void)dealloc;
- (void)setView:(id)fp8;
- (void)setLabel:(id)fp8;
- (void)setButton:(id)fp8;
- (id)button;
- (id)webView;
- (void)setSearchFieldText:(id)fp8;
- (id)searchFieldText;
- (void)updateLabel;
- (id)objectSpecifier;
- (void)handleCloseScriptCommand:(id)fp8;
- (id)title;
- (unsigned int)orderedIndex;
- (BOOL)isVisible;
- (void)rememberCurrentURLString;
- (id)URLString;
- (void)setURLString:(id)fp8;
- (id)source;
- (id)text;
- (id)aeDescByEvaluatingJavaScriptFromString:(id)fp8;
- (void)mailPageContents;

@end

