/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface BrowserCoachMarkController : NSObject
{
    NSMutableArray *_coachMarks;
}

- (id)init;
- (void)dealloc;
- (void)addCoachMarksWithSelectionRect:(struct _NSRect)fp8 textRects:(id)fp24 contentImage:(id)fp28 forView:(id)fp32 selfDestruct:(BOOL)fp36;
- (void)cancelCurrentCoachMarks;
- (void)coachMarkExpired:(id)fp8;
- (id)currentCoachMarksEnumerator;

@end

