/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTableColumn.h"

@interface BrowserTableColumn : NSTableColumn
{
    id _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)dataCellForRow:(int)fp8;

@end

