/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserWindowPersistentState.h"

@interface BrowserWindowPersistentState (FileInternal)
- (BOOL)_canRestoreURL:(id)fp8;
- (BOOL)_containsAnyURLsIncludingUnrestorable:(BOOL)fp8;
@end

