/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class BrowserCoachMark, NSImage;

@interface BrowserCoachMarkView : NSView
{
    BrowserCoachMark *_coach;
    NSImage *_contentImage;
    struct _NSPoint _imageOffset;
}

+ (BOOL)coachMarksWouldOverlapUsingTextRects:(id)fp8;
- (void)dealloc;
- (id)initWithCoach:(id)fp8 contentRect:(struct _NSRect)fp12 contentImage:(id)fp28 contentImageOffset:(struct _NSPoint)fp32;
- (id)roundedRect:(struct _NSRect)fp8 withRadius:(float)fp24;
- (struct _NSRect)contentRect;
- (void)_drawGradientInRect:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (float)leftBorder;
- (float)topBorder;
- (float)rightBorder;
- (float)bottomBorder;

@end

