/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserDocument.h"

@interface BrowserDocument (DebugExtras)
- (void)showRenderTree:(id)fp8;
- (BOOL)validate_showRenderTree:(id)fp8;
- (void)showViewTree:(id)fp8;
- (void)forceRepaint:(id)fp8;
- (BOOL)validate_forceRepaint:(id)fp8;
- (void)toggleBackForwardCacheDisabled:(id)fp8;
- (BOOL)validate_toggleBackForwardCacheDisabled:(id)fp8;
- (void)toggleTransparentWindow:(id)fp8;
- (BOOL)validate_toggleTransparentWindow:(id)fp8;
- (void)goToAboutBlankSoon:(id)fp8;
- (void)toggleDOMPasteAllowed:(id)fp8;
- (BOOL)validate_toggleDOMPasteAllowed:(id)fp8;
@end

