/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface BrowserSessionPersistentState : NSObject
{
    NSMutableArray *_windowStates;
}

- (id)init;
- (id)initFromCurrentSession;
- (id)initFromFile:(id)fp8;
- (void)dealloc;
- (BOOL)containsAnyRestorableURLs;
- (BOOL)containsAnyURLs;
- (void)restoreSession;
- (BOOL)writeToFile:(id)fp8;

@end

