/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserWebView.h"

@interface BrowserWebView (BrowserWebViewPrinting)
- (void)webView:(id)fp8 printFrameView:(id)fp12;
- (float)webViewHeaderHeight:(id)fp8;
- (float)webViewFooterHeight:(id)fp8;
- (void)drawLeftString:(id)fp8 rightString:(id)fp12 inRect:(struct _NSRect)fp16 atBaseline:(float)fp32 withFont:(id)fp36;
- (void)webView:(id)fp8 drawHeaderInRect:(struct _NSRect)fp12;
- (void)webView:(id)fp8 drawFooterInRect:(struct _NSRect)fp12;
@end

