/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDocumentController.h"

@interface BrowserDocumentController : NSDocumentController
{
}

+ (id)sharedDocumentController;
- (unsigned int)maximumRecentDocumentCount;
- (id)_openDocumentWithContentsOfRequest:(id)fp8 behind:(BOOL)fp12 display:(BOOL)fp16 frameName:(id)fp20;
- (id)openDocumentWithContentsOfRequest:(id)fp8 behind:(BOOL)fp12 display:(BOOL)fp16;
- (id)openDocumentWithContentsOfURL:(id)fp8 display:(BOOL)fp12;
- (id)URLFromShortcutFile:(id)fp8;
- (BOOL)anyInactiveTabs;
- (id)frontmostBrowserDocument;
- (id)frontmostBrowserDocumentAllowingAttachedSheets:(BOOL)fp8;
- (BOOL)browserDocumentIsAvailable:(id)fp8 usingWindowPolicy:(int)fp12;
- (id)_frontmostBrowserDocumentIfAvailableUsingWindowPolicy:(int)fp8;
- (id)_URLToVisitFromURL:(id)fp8;
- (BOOL)_tab:(id)fp8 isAutoSelectableWithURL:(id)fp12;
- (id)_findAutoSelectableTabWithURL:(id)fp8 usingWindowPolicy:(int)fp12 tabLocation:(id)fp16;
- (void)reuseWebView:(id)fp8 forRequest:(id)fp12;
- (id)_goToEachRequest:(id)fp8 tabLabels:(id)fp12 windowPolicy:(int)fp16 tabLocation:(id)fp20 frameName:(id)fp24;
- (id)_openableFileExtensions;
- (void)openDocument:(id)fp8;
- (id)_createEmptyBrowserDocumentAndDisplay:(BOOL)fp8;
- (id)createHiddenEmptyBrowserDocument;
- (id)openEmptyBrowserDocument;
- (id)activateFrontmostBrowserDocumentIfAvailable;
- (id)findOrCreateFrontmostBrowserDocument;
- (BOOL)canGoHome;
- (void)goHome:(id)fp8;
- (BOOL)canShowInputFields;
- (void)openLocation:(id)fp8;
- (void)searchWeb:(id)fp8;
- (void)showHistoryInBookmarksView:(id)fp8;
- (void)toggleShowBookmarks:(id)fp8;
- (void)newBookmarkFolder:(id)fp8;
- (void)editTitleOfBookmarksCollection:(id)fp8;
- (void)reportBugToApple:(id)fp8;
- (void)newTab:(id)fp8;
- (id)goToURL:(id)fp8 windowPolicy:(int)fp12 tabLocation:(id)fp16;
- (id)goToURL:(id)fp8 windowPolicy:(int)fp12;
- (id)goToRequest:(id)fp8 tabLabel:(id)fp12 windowPolicy:(int)fp16 tabLocation:(id)fp20 frameName:(id)fp24;
- (void)tryMultipleURLs:(id)fp8 windowPolicy:(int)fp12;
- (void)reloadTabsMatchingURLs:(id)fp8;
- (id)openHTMLSourceDocumentWithDataSource:(id)fp8;
- (id)openHTMLSourceDocumentWithResource:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (BOOL)validateUserInterfaceItem:(id)fp8;

@end

