/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserDocument.h"

@interface BrowserDocument (DeveloperExtras)
- (void)openPageWithApplication:(id)fp8;
- (BOOL)validate_openPageWithApplication:(id)fp8;
- (void)setUserAgent:(id)fp8;
- (BOOL)validate_setUserAgent:(id)fp8;
- (void)resetUserAgent:(id)fp8;
- (BOOL)validate_resetUserAgent:(id)fp8;
- (void)setUserDefinedUserAgent:(id)fp8;
- (BOOL)validate_setUserDefinedUserAgent:(id)fp8;
- (void)showOtherUserAgentSheet:(id)fp8;
- (BOOL)validate_showOtherUserAgentSheet:(id)fp8;
- (void)otherUserAgentSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)showWebInspector:(id)fp8;
- (BOOL)validate_showWebInspector:(id)fp8;
- (void)showErrorConsole:(id)fp8;
- (BOOL)validate_showErrorConsole:(id)fp8;
- (void)showNetworkTimeline:(id)fp8;
- (BOOL)validate_showNetworkTimeline:(id)fp8;
@end

