/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class BrowserCoachMarkView, NSAnimation, NSTimer, NSWindow;

@interface BrowserCoachMark : NSObject
{
    NSWindow *_coachMarkWindow;
    BrowserCoachMarkView *_coachMarkView;
    struct CGAffineTransform _prePulseTransform;
    NSAnimation *_pulseAnimation;
    NSTimer *_startFadeOutTimer;
    NSAnimation *_fadeOutAnimation;
    BOOL _expired;
}

- (void)_targetViewDidMoveOrChangeSize:(id)fp8;
- (id)initWithContentRect:(struct _NSRect)fp8 contentImage:(id)fp24 contentImageOffset:(struct _NSPoint)fp28 forView:(id)fp36 selfDestruct:(BOOL)fp40;
- (void)dealloc;
- (void)expire;
- (struct _NSRect)rectOnScreen;
- (void)animationDidEnd:(id)fp8;

@end

