/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BrowserParentalControls.h"

@interface BrowserParentalControls (BrowserParentalControlsInternal)
- (BOOL)_parentalControlsEnabled;
- (void)_updateParentalControlsEnabled;
- (void *)_familyControlsFramework;
- (BOOL)_isManagedUser;
- (BOOL)_userHasWebSiteRestrictions;
- (void)_mcxPreferencesChanged:(id)fp8;
- (id)init;
- (void)dealloc;
@end

