/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextView.h"

@interface BugReportTextView : NSTextView
{
}

- (void)insertTab:(id)fp8;
- (void)insertBacktab:(id)fp8;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;

@end

