/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSButton, NSPopUpButton, NSString, NSTabView, NSTextField, NSTextView;

@interface BugReportController : NSWindowController
{
    NSTextField *URLField;
    NSTextView *descriptionTextView;
    NSPopUpButton *bugTypePopUp;
    NSButton *screenShotCheckBox;
    NSButton *sourceCheckBox;
    NSButton *submitButton;
    NSButton *disclosureButton;
    NSTabView *extras;
    NSString *_initialURLString;
    BOOL _isExpanded;
}

+ (id)customBugReportServerURLString;
- (id)initWithURLString:(id)fp8;
- (void)dealloc;
- (id)windowNibName;
- (void)toggleWindowSizeWithAnimation:(BOOL)fp8;
- (void)updateSubmitButton;
- (void)updateDisclosureButton;
- (void)windowDidLoad;
- (void)controlTextDidChange:(id)fp8;
- (void)textDidChange:(id)fp8;
- (void)submitBug:(id)fp8;
- (void)cancel:(id)fp8;
- (void)toggleWindowSize:(id)fp8;
- (id)bugURLString;
- (id)bugDescription;
- (int)bugType;
- (BOOL)shouldSendScreenShot;
- (BOOL)shouldSendSource;
- (void)sendBugReportToAppleWithScreenShot:(id)fp8 source:(id)fp12;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailLoadingWithError:(id)fp12;

@end

