/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSButton.h"

@interface ButtonWithMenu : NSButton
{
    id _menuProvider;
    SEL _menuSelector;
}

- (id)menuProvider;
- (void)setMenuProvider:(id)fp8;
- (SEL)menuSelector;
- (void)setMenuSelector:(SEL)fp8;
- (id)menu;
- (void)popUpMenu;
- (void)moveDown:(id)fp8;
- (void)moveUp:(id)fp8;
- (void)mouseDown:(id)fp8;

@end

