/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMenu.h"

@class NSButton;

@interface ButtonHighlightingMenu : NSMenu
{
    NSButton *_button;
}

+ (id)menuWithButton:(id)fp8;
- (void)dealloc;

@end

