/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "ReopensAtLaunch-Protocol.h"

@class NSMatrix;

@interface CacheController : NSWindowController <ReopensAtLaunch>
{
    NSMatrix *webCoreStatisticsMatrix;
    NSMatrix *webFoundationStatisticsMatrix;
    NSMatrix *javaScriptStatisticsMatrix;
    NSMatrix *javaScriptClassesMatrix;
    NSMatrix *siteIconStatisticsMatrix;
}

+ (id)sharedCacheController;
+ (void)reopen;
- (id)windowNibName;
- (void)windowDidLoad;
- (void)showWindow:(id)fp8;
- (void)emptyWebCoreCaches:(id)fp8;
- (void)emptyWebFoundationCaches:(id)fp8;
- (void)setStat:(int)fp8 toKey:(id)fp12 fromDict:(id)fp16;
- (void)setTotal:(int)fp8 fromDict:(id)fp12;
- (void)refreshWebCoreStatisticsMatrix;
- (void)refreshWebFoundationStatisticsMatrix;
- (void)refreshJavaScriptStatisticsMatrix;
- (void)refreshSiteIconStatisticsMatrix;
- (void)refreshStatistics:(id)fp8;
- (void)toggleDisableWebCoreCaches:(id)fp8;
- (void)garbageCollectJavaScriptObjects:(id)fp8;

@end

