/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@class NSWindow, SnippetEditorDelegate;

struct AliasRecord;

struct CGAffineTransform {
    float a;
    float b;
    float c;
    float d;
    float tx;
    float ty;
};

struct CGColor;

struct CGImage;

struct CGPoint {
    float x;
    float y;
};

struct OpaqueJSContext;

struct OpaqueSecCertificateRef;

struct OpaqueSecPolicyRef;

struct OpaqueSecTrustRef;

struct OpaqueSecureDownload;

struct OwnPtr<SObjCNotifier> {
    struct SObjCNotifier *m_ptr;
};

struct ProcessSerialNumber {
    unsigned int highLongOfPSN;
    unsigned int lowLongOfPSN;
};

struct RefPtr<SafeBrowsingLastUpdateObserver> {
    struct SafeBrowsingLastUpdateObserver *m_ptr;
};

struct RefPtr<SafeBrowsingObserverMac> {
    struct SafeBrowsingObserverMac *m_ptr;
};

struct RetainPtr<const __CFString*> {
    struct __CFString *_field1;
};

struct RetainPtr<objc_object*> {
    id m_ptr;
};

struct SNotification {
    struct SString _field1;
    void *_field2;
};

struct SObjCNotifier;

struct SString {
    struct RetainPtr<const __CFString*> _field1;
};

struct SWebFrameLoadDelegate {
    void **_field1;
    struct RetainPtr<objc_object*> _field2;
};

struct SafeBrowsingLastUpdateObserver {
    void **_field1;
    int _field2;
    id _field3;
};

struct SafeBrowsingObserverMac;

struct SearchParams {
    id _field1;
    int _field2;
    id *_field3;
    int _field4;
    id _field5;
    char _field6;
    char _field7;
    char _field8;
    id _field9;
    int _field10;
};

struct SnippetEditorController {
    struct OpaqueJSContext *_field1;
    NSWindow *_field2;
    SnippetEditorDelegate *_field3;
};

struct _BOMCopier;

struct _NSModalSession;

struct _NSPoint {
    float x;
    float y;
};

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _NSRect {
    struct _NSPoint origin;
    struct _NSSize size;
};

struct _NSSize {
    float width;
    float height;
};

struct _NSZone;

struct _TreeCursor {
    struct _TreeNode *_field1;
    char _field2;
    char _field3;
};

struct _TreeNode;

struct __CFDateFormatter;

struct __CFString;

struct __CFURL;

struct __DASession;

struct __SCDynamicStore;

struct __SKIndex;

struct cssm_data {
    unsigned int _field1;
    char *_field2;
};

struct timespec {
    int tv_sec;
    long tv_nsec;
};

typedef struct {
    unsigned int _field1;
    struct {
    } *_field2;
} CDAnonymousStruct1;

typedef struct {
    int nodes;
    int bytes;
} CDAnonymousStruct2;

