/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface CertificateUtilities : NSObject
{
}

+ (id)arrayWithLeafCertificateForTrustReference:(struct OpaqueSecTrustRef *)fp8;
+ (id)identitiesWithPolicy:(struct OpaqueSecPolicyRef *)fp8;
+ (id)labelForCertificates:(id)fp8;
+ (struct OpaqueSecPolicyRef *)sslPolicyForHost:(id)fp8 client:(BOOL)fp12;
+ (struct OpaqueSecTrustRef *)trustReferenceWithCertificates:(id)fp8 forPolicy:(struct OpaqueSecPolicyRef *)fp12;
+ (id)organizationNameForCertificate:(struct OpaqueSecCertificateRef *)fp8;
+ (id)_potentialEVChainWithCertificates:(id)fp8;
+ (struct OpaqueSecCertificateRef *)_rootCertificateWithSubjectOfCertificate:(struct OpaqueSecCertificateRef *)fp8;
+ (id)_allowedRootCertificatesForOidString:(id)fp8;
+ (struct cssm_data *)_copyFieldDataForOid:(struct cssm_data *)fp8 inCert:(struct cssm_data *)fp12 withHandle:(long)fp16;
+ (struct OpaqueSecPolicyRef *)_copyOcspPolicyWithOptions:(unsigned int)fp8;
+ (BOOL)_isRevocationServerMetaError:(int)fp8;
+ (id)_extendedValidationOrganizationNameForHost:(id)fp8 withCertificates:(id)fp12;
+ (id)_evCAOidDict;
+ (id)_decimalStringForOid:(struct cssm_data *)fp8;
+ (void)_freeFieldData:(struct cssm_data *)fp8 forOid:(struct cssm_data *)fp12 withHandle:(long)fp16;
+ (id)_hexStringForOid:(struct cssm_data *)fp8;
+ (id)_oidStringForCertificatePolicies:(const CDAnonymousStruct1 *)fp8;
+ (id)_certificateChainForTrustReference:(struct OpaqueSecTrustRef *)fp8;

@end

