/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ClippedNode.h"

@interface ClippedNode (FileInternal)
- (id)description;
- (id)_initWithNode:(id)fp8 clipRect:(struct _NSRect)fp12;
@end

