/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@interface ClippedItemsIndicatorCell : NSPopUpButtonCell
{
}

- (struct _NSRect)imageRectForBounds:(struct _NSRect)fp8;
- (BOOL)trackMouse:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 untilMouseUp:(BOOL)fp32;
- (void)drawImageWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

