/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class BrowserWebView, BrowserWindowController;

@interface ClosedWebViewHolder : NSObject
{
    BrowserWindowController *_browserWindowController;
    BrowserWebView *_lastClosedWebView;
}

- (id)initWithBrowserWindowController:(id)fp8;
- (void)dealloc;
- (id)lastClosedWebView;
- (void)setLastClosedWebView:(id)fp8;
- (void)_undoCloseTab:(id)fp8 atIndex:(unsigned int)fp12 andShow:(BOOL)fp16;
- (void)_closeTabWithoutConfirming:(id)fp8;

@end

