/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSColor;

@interface ColoredRect : NSView
{
    NSColor *_color;
}

- (id)standardBorderlineColor;
- (id)standardBorderlineHighlightColor;
- (void)dealloc;
- (void)drawRect:(struct _NSRect)fp8;
- (id)color;
- (void)setColor:(id)fp8;

@end

