/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class CompletionWindow, NSArray, NSString, NSTableView, NSWindow, WebDynamicScrollBarsView;

@interface CompletionController : NSObject
{
    NSWindow *_sourceWindow;
    CompletionWindow *_matchesWindow;
    NSTableView *_matchesTableView;
    WebDynamicScrollBarsView *_scrollView;
    NSString *_partialString;
    NSArray *_matches;
    int _selectedMatchIndex;
    BOOL _blockCompletion;
    BOOL _blockReflectSelection;
    BOOL _ignoreTextDidChange;
    BOOL _dropDownVisible;
    BOOL _showDropDownForSingleOverride;
    BOOL _replaceEntireField;
    BOOL _inProgrammaticChange;
}

+ (void)setAllCompletionsBlocked:(BOOL)fp8;
+ (id)currentCompletionController;
+ (void)setCurrentCompletionController:(id)fp8;
- (id)initWithPartialString:(id)fp8 inWindow:(id)fp12;
- (void)dealloc;
- (void)_selectMatchAtIndex:(int)fp8;
- (void)_deselectAllMatches;
- (id)scrollView;
- (void)buildUI;
- (struct _NSRect)windowFrame;
- (void)showMatchesWindow:(unsigned int)fp8;
- (void)hideMatchesWindow;
- (void)_sourceWindowWillResize:(id)fp8;
- (void)_sourceWindowWillMiniaturize:(id)fp8;
- (void)_sourceWindowWillClose:(id)fp8;
- (void)_abortCompletion:(id)fp8;
- (void)_clearMatches;
- (void)abortCompletion;
- (void)_sendMessageIgnoringTextChanges:(SEL)fp8;
- (id)selectedMatch;
- (id)currentMatches;
- (void)reflectSelectedRow;
- (void)reflectFinalSelectedRow;
- (unsigned int)maxStringLength;
- (BOOL)shouldSuppressAutocompleteForPartialString:(id)fp8;
- (void)_completeString:(id)fp8;
- (void)completeString;
- (BOOL)currentTextChangeIsProgrammatic;
- (id)sourceFieldFont;
- (id)deepestViewContainingSourceField;
- (id)sourceFieldString;
- (void)setSourceFieldString:(id)fp8;
- (struct _NSRect)sourceFieldFrame;
- (struct _NSRange)sourceFieldSelectedRange;
- (void)performSourceFieldAction;
- (void)replaceSourceFieldCharactersInRange:(struct _NSRange)fp8 withString:(id)fp16 selectingFromIndex:(int)fp20;
- (id)queryResultsForString:(id)fp8 startingMatch:(unsigned int *)fp12;
- (id)queryStringFromPartialString:(id)fp8;
- (id)intermediateMatchingStringForResult:(id)fp8;
- (id)finalMatchingStringForResult:(id)fp8;
- (BOOL)leavingFieldReflectsFinalString;
- (BOOL)returnDoesActionWhenShowingDropDown;
- (BOOL)showsDropDownForSingleMatch;
- (BOOL)canDeselectAllMatches;
- (void)_handleTextChangeWithDelay:(BOOL)fp8;
- (void)sourceFieldTextDidChange;
- (void)sourceFieldTextDidEndEditing;
- (void)_sourceFieldDidMove:(id)fp8;
- (BOOL)handleInsertNewline;
- (BOOL)sourceFieldIsEmpty;
- (BOOL)doSourceFieldCommandBySelector:(SEL)fp8;
- (void)_doubleClickedInMatchesList:(id)fp8;
- (void)tableViewSelectionDidChange:(id)fp8;
- (int)numberOfRowsInTableView:(id)fp8;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;

@end

