/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionController.h"

@class NSTextField;

@interface CompletionControllerForNSTextField : CompletionController
{
    NSTextField *_sourceField;
}

- (id)initWithSourceField:(id)fp8;
- (id)sourceField;
- (id)sourceFieldFont;
- (id)deepestViewContainingSourceField;
- (struct _NSRect)sourceFieldFrame;
- (id)sourceFieldString;
- (void)setSourceFieldString:(id)fp8;
- (struct _NSRange)sourceFieldSelectedRange;
- (void)performSourceFieldAction;
- (void)replaceSourceFieldCharactersInRange:(struct _NSRange)fp8 withString:(id)fp16 selectingFromIndex:(int)fp20;

@end

