/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CroppingOverlayView.h"

@interface CroppingOverlayView (FileInternal)
- (struct _NSRect)_constrainedCropRectFromUnconstrainedRect:(struct _NSRect)fp8 withResizeHandle:(int)fp24;
- (struct _NSRect)_convertRectFromTargetView:(struct _NSRect)fp8;
- (struct _NSRect)_convertRectToTargetView:(struct _NSRect)fp8;
- (BOOL)_cropRectIsValid;
- (int)_handleContainingPoint:(struct _NSPoint)fp8;
- (void)_invalidateCropRect;
- (BOOL)_moveCropRectWithMouseDownPoint:(struct _NSPoint)fp8;
- (void)_reconstrainCropRect;
- (struct _NSRect)_rectForHandle:(int)fp8;
- (BOOL)_resizeCropRectWithMouseDownPoint:(struct _NSPoint)fp8;
- (id)_targetDocumentView;
- (id)_targetView;
@end

