/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSButtonCell.h"

@class NSImage;

@interface CustomDisabledImageButtonCell : NSButtonCell
{
    NSImage *_disabledImage;
}

+ (id)updateCellForButton:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (void)setDisabledImage:(id)fp8;
- (id)disabledImage;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

