/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface DashboardWebClipController : NSObject
{
}

+ (id)sharedController;
- (void)createClipWithWebView:(id)fp8 element:(id)fp12 cropRect:(struct _NSRect)fp16;
- (struct _NSSize)minimumWebClipContentSize;

@end

