/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DashboardWebClipController.h"

@interface DashboardWebClipController (FileInternal)
- (id)_clipSignatureDictionaryFromDOMHTMLElement:(id)fp8 cropRectInMainDocumentView:(struct _NSRect)fp12;
- (id)_webWidgetURLWithParameters:(id)fp8;
@end

