/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ImageAndTextCell.h"

@class NSFont, NSMutableAttributedString, NSMutableDictionary;

@interface DateCell : ImageAndTextCell
{
    NSFont *_lastFont;
    NSFont *_smallerFont;
    NSMutableAttributedString *_lastDateString;
    double _lastDateInterval;
    NSMutableAttributedString *_ampmDesignator;
    NSMutableDictionary *_normalAttributes;
    BOOL _use24HourFormat;
    BOOL _okToUseYesterdayAndToday;
    BOOL _omitTime;
    float _detailLevelWidths[8];
    float _todayAndYesterdayWidths[4];
    float _lastWidth;
    int _dateDetailLevel;
}

+ (void)initialize;
+ (id)updateCellForColumn:(id)fp8 inView:(id)fp12;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)_updateDateColumnDetailLevels;
- (float)_widthOfLongestDateStringWithLevel:(int)fp8 format:(id)fp12;
- (void)_updateDateColumnDetailLevelWidths;
- (float)minimumWidth;
- (struct _NSRect)drawingRectForBounds:(struct _NSRect)fp8;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)setFont:(id)fp8;
- (void)setTimeOmitted:(BOOL)fp8;

@end

