/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSMenu, NSMutableArray, NSMutableDictionary, NSString, NSTimer, StressHUD, Watchdog;

@interface DebugUtilities : NSObject
{
    int sampleToolProcessID;
    int sampleToolPtyFD;
    int sharkToolProcessID;
    NSString *sampleToolOutputPath;
    NSString *sharkToolOutputBase;
    NSMenu *debugMenu;
    NSDate *stressTestStartTime;
    NSTimer *stressTestTimer;
    NSMutableArray *stressTestURLHistory;
    unsigned int stressResourceCount;
    StressHUD *stressHUD;
    Watchdog *watchdog;
    NSMutableDictionary *stopwatches;
    int numTestsLeftToComplete;
    BOOL shouldSuppressAlerts;
}

+ (void)load;
+ (id)sharedDebugUtilities;
+ (const char *)crashReporterInfo;
- (id)init;
- (void)dealloc;
- (void)setSampleToolOutputPath:(id)fp8;
- (BOOL)startSampleToolWithIdentifier:(id)fp8;
- (BOOL)startSampleTool;
- (BOOL)stopSampleTool;
- (void)setSharkToolOutputBase:(id)fp8;
- (void)startProfiling:(id)fp8;
- (void)stopProfiling:(id)fp8;
- (BOOL)startSharkToolWithIdentifier:(id)fp8;
- (BOOL)startSharkTool;
- (BOOL)stopSharkTool;
- (void)navigateToNextStressTestPage:(id)fp8;
- (void)stressTestPageLoading:(id)fp8;
- (void)startStressTest;
- (void)stopStressTest;
- (BOOL)isStressTestRunning;
- (void)incrementResourceCount;
- (double)stressUpTime;
- (unsigned int)stressPageCount;
- (unsigned int)stressResourceCount;
- (void)toggleStressTest:(id)fp8;
- (BOOL)validate_toggleStressTest:(id)fp8;
- (void)toggleSuppressAlerts:(id)fp8;
- (BOOL)validate_toggleSuppressAlerts:(id)fp8;
- (void)toggleWatchdog:(id)fp8;
- (BOOL)validate_toggleWatchdog:(id)fp8;
- (id)experimentalFeaturesSubmenuItem;
- (void)_populateDebugMenu;
- (void)createDebugMenu;
- (void)menuNeedsUpdate:(id)fp8;
- (BOOL)menuHasKeyEquivalent:(id)fp8 forEvent:(id)fp12 target:(id *)fp16 action:(SEL *)fp20;
- (void)startStopwatchWithIdentifier:(id)fp8;
- (void)stopStopwatchWithIdentifier:(id)fp8;
- (double)stopwatchRunTimeWithIdentifier:(id)fp8;
- (void)maybeQuitAfterTestCompleted;
- (BOOL)shouldSuppressAlerts;
- (void)setShouldSuppressAlerts:(BOOL)fp8;
- (void)startWatchdog;
- (void)stopWatchdog;
- (void)checkInWithWatchdog:(id)fp8;
- (BOOL)validateUserInterfaceItem:(id)fp8;

@end

