/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTimer;

@interface DiskArbitrationHelper2 : NSObject
{
    struct __DASession *_session;
    NSTimer *_diskArbTimer;
    BOOL _diskArbDone;
    int _diskArbResult;
}

+ (id)helper;
- (id)init;
- (void)dealloc;
- (long)synchronousWaitIdleWithTimeout:(double)fp8;
- (long)synchronousEject:(id)fp8 withTimeout:(double)fp12;
- (long)synchronousUnmountDisk:(id)fp8 force:(BOOL)fp12 whole:(BOOL)fp16 withTimeout:(double)fp20;
- (long)synchronousUnmount:(id)fp8 force:(BOOL)fp12 withTimeout:(double)fp16;
- (long)synchronousUnmount:(id)fp8 force:(BOOL)fp12 whole:(BOOL)fp16 withTimeout:(double)fp20;
- (void)_diskArbTimedOut:(id)fp8;
- (void)_setDiskArbDone:(BOOL)fp8;
- (void)_setDiskArbResult:(int)fp8;

@end

