/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DownloadProgressEntry.h"

@interface DownloadProgressEntry (DownloadProgressEntryInternal)
- (void)_startThreadWithFunction:(void *)fp8;
- (BOOL)_openDiskImageFile;
- (void)_updateDiskImageStatus:(id)fp8;
- (void)_diskImageAttachmentEnded:(id)fp8;
- (BOOL)_openGZipFile;
- (BOOL)_openBOMFile;
- (void)_setBOMCopier:(struct _BOMCopier *)fp8;
- (void)_BOMCopyEnded:(id)fp8;
- (void)_GZipDecompressionEnded:(id)fp8;
- (BOOL)_openInstallerPackage;
- (void)_observeWidgetInstallationNotification;
- (void)_dashboardDidInstallWidget:(id)fp8;
- (BOOL)_openDashboardWidget;
- (BOOL)_addCertificateToKeyChain;
- (int)_openArchive;
- (BOOL)_open;
- (BOOL)_moveFilesFromBundle;
- (int)_autoOpen;
- (id)_postDownloadFile;
- (id)_postDownloadPath;
- (void)_updatePath:(id)fp8 ofFile:(id)fp12;
- (id)_allFiles;
- (void)_postPathDidChangeNotification;
- (BOOL)_hasAnyFiles;
- (id)_downloadPath;
- (id)_bundlePath;
- (id)_downloadPathForJNLP;
- (id)_legalFilenameForDirectoryPath:(id)fp8 filename:(id)fp12;
- (void)_addPostDownloadFiles:(id)fp8;
- (void)_addUnarchivedFilesFromResults:(id)fp8;
- (void)_addPostDownloadFileWithPath:(id)fp8;
- (BOOL)_canFinishDownloadWithoutReloading;
- (id)_cancelledError;
- (void)_forgetPostDownloadFile:(id)fp8;
- (void)_forgetAllPostDownloadFiles;
- (void)_forgetAllFiles;
- (void)dealloc;
- (void)_setDownload:(id)fp8;
- (void)_setRequest:(id)fp8;
- (void)_setStartDate:(id)fp8;
- (void)_setDownloadStage:(int)fp8 shouldSendNotification:(BOOL)fp12;
- (void)_setResumeInformation:(id)fp8;
- (BOOL)_notEnoughFreeDiskSpaceAtDirectoryPath:(id)fp8;
- (id)_createDownloadBundleInDirectory:(id)fp8 withFilename:(id)fp12;
- (void)_endWithPostDownloadError:(id)fp8;
- (BOOL)_deleteFilesAndBundle;
- (void)setDone:(BOOL)fp8;
- (void)_startPostProcessingIfDone;
- (void)_updateIcon;
@end

