/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ResourceProgressEntry.h"

@class DownloadFile, NSDate, NSDictionary, NSMutableArray, NSString, NSURLDownload, NSURLRequest, NSURLResponse;

@interface DownloadProgressEntry : ResourceProgressEntry
{
    NSURLDownload *_download;
    NSURLRequest *_request;
    NSURLResponse *_response;
    DownloadFile *_downloadFile;
    NSMutableArray *_postDownloadFiles;
    NSString *_directoryPath;
    NSString *_identifier;
    NSDictionary *_resumeInformation;
    struct _BOMCopier *_BOMCopier;
    NSDate *_startDate;
    BOOL _openWhenDone;
    BOOL _allowOverwrite;
    BOOL _observingWidgetInstallationNotification;
    int _downloadStage;
    long long _realBytesExpected;
    long long _bytesLoadedAtStart;
    int _iconNumber;
    long _lastBytesPerSecond;
}

- (id)initWithRequest:(id)fp8 bytesLoaded:(long long)fp12 bytesExpected:(long long)fp20 error:(id)fp28 download:(id)fp32 downloadFile:(id)fp36 postDownloadFile:(id)fp40 downloadPath:(id)fp44 postDownloadPath:(id)fp48 identifier:(id)fp52 mayOpenWhenDone:(BOOL)fp56 allowOverwrite:(BOOL)fp60;
- (id)initWithDictionary:(id)fp8;
- (id)initWithDownload:(id)fp8 mayOpenWhenDone:(BOOL)fp12 allowOverwrite:(BOOL)fp16;
- (id)createDownloadBundleWithFilename:(id)fp8;
- (id)currentFile;
- (id)dictionaryRepresentation;
- (id)downloadFile;
- (id)identifier;
- (BOOL)saveStateToPList;
- (void)setDownloadFileWithPath:(id)fp8;
- (void)setResponse:(id)fp8 bytesLoaded:(long long)fp12;
- (id)response;
- (id)URL;
- (BOOL)aliasFileExists;
- (BOOL)fileExists;
- (id)currentPath;
- (id)filename;
- (void)setDirectoryPath:(id)fp8;
- (BOOL)open;
- (void)resume;
- (BOOL)reveal;
- (void)stop;
- (BOOL)allowOverwrite;
- (BOOL)canAttemptOpen;
- (BOOL)canAttemptResume;
- (BOOL)canAttemptReveal;
- (BOOL)canStop;
- (BOOL)canResumeOrReload;
- (BOOL)isIdle;
- (BOOL)isBusy;
- (void)setBytesLoaded:(long long)fp8;
- (void)setBytesExpected:(long long)fp8;
- (long long)bytesExpected;
- (long long)bytesLoadedSinceStart;
- (long)bytesPerSecond;
- (long)secondsRemaining;
- (int)downloadStage;
- (void)setDownloadStage:(int)fp8;
- (BOOL)notEnoughFreeDiskSpaceAtCurrentPath;

@end

