/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface DownloadFile : NSObject
{
    NSString *_initialDownloadPath;
    int _type;
    struct AliasRecord **_alias;
    BOOL _isAliasOrSymlink;
    BOOL _isDiskImageVolume;
    BOOL _isSubFile;
    BOOL _isTrashed;
    NSDictionary *_securityAssessment;
    NSArray *_temporaryFiles;
    BOOL _isApproved;
    BOOL _areTemporaryFilesApproved;
}

+ (id)filesForUnarchivedFileAtPath:(id)fp8;
- (id)_MIMETypeFromExtension;
- (BOOL)_isMIMEType:(id)fp8;
- (BOOL)_isBOM;
- (BOOL)_isDiskImage;
- (BOOL)_isGZIP;
- (id)aliasData;
- (void)setAlias:(struct AliasRecord **)fp8;
- (void)setAliasData:(id)fp8;
- (void)_setInitialDownloadPath:(id)fp8;
- (void)setPath:(id)fp8;
- (id)initWithPath:(id)fp8;
- (id)initWithAliasData:(id)fp8 pathString:(id)fp12;
- (void)dealloc;
- (id)aliasedOrOriginalPath;
- (id)path;
- (BOOL)isArchive;
- (BOOL)isBOM;
- (BOOL)isDiskImage;
- (BOOL)isGZIP;
- (int)type;
- (void)setType:(int)fp8;
- (void)setTypeWithEncoding:(id)fp8;
- (BOOL)isDiskImageVolume;
- (void)setIsDiskImageVolume:(BOOL)fp8;
- (BOOL)isSubFile;
- (void)setIsSubFile:(BOOL)fp8;
- (BOOL)isTrashed;
- (void)setIsTrashed:(BOOL)fp8;
- (BOOL)isMovableOrRemovable;
- (id)description;
- (id)securityAssessment;
- (void)resetSecurityAssessment;
- (BOOL)isRiskSafeOrUnknown;

@end

