/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class BarBackground, DownloadViewController, EtchedStringView, NSControl, NSMutableArray, NSTextField, WebDynamicScrollBarsView;

@interface DownloadWindowController : NSWindowController
{
    WebDynamicScrollBarsView *_scrollView;
    DownloadViewController *_viewController;
    BarBackground *_barBackground;
    NSTextField *_totalTextField;
    NSControl *_clearControl;
    EtchedStringView *_totalStringView;
    BOOL _waitingToShowTerminationSheet;
    NSMutableArray *_entriesToPrompt;
    NSMutableArray *_corruptDownloadsToReport;
    NSMutableArray *_invalidPathsToPrompt;
}

+ (id)sharedDownloadWindowController;
- (void)awakeFromNib;
- (id)initWithWindowNibName:(id)fp8;
- (void)_setTotalField;
- (void)_setClearControlState;
- (void)windowDidLoad;
- (struct _NSRect)windowWillUseStandardFrame:(id)fp8 defaultFrame:(struct _NSRect)fp12;
- (void)downloadsDidChange:(id)fp8;
- (void)downloadDidStart:(id)fp8;
- (void)downloadEntryStageChanged:(id)fp8;
- (void)clear:(id)fp8;
- (void)_runTerminationSheet;
- (void)terminationSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_runCorruptDownloadForSecureDownloadProgressEntry:(id)fp8;
- (void)corruptDownloadSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_runInvalidDownloadSheetForPath:(id)fp8;
- (void)_runQueuedAlertSheet;
- (void)windowDidEndSheet:(id)fp8;
- (void)askToTerminateWhileDownloading;
- (void)promptForDownloadProgressEntry:(id)fp8 assessment:(id)fp12;
- (void)reportInsufficientDiskSpaceSheetForDownload:(id)fp8;
- (void)reportCorruptDownloadForSecureDownloadProgressEntry:(id)fp8;
- (void)reportInvalidDownloadFileErrorForPath:(id)fp8;

@end

