/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DownloadMonitor.h"

@interface DownloadMonitor (DownloadMonitorInternal)
- (void)_noteDownloadsChanged;
- (void)_insertEntry:(id)fp8 atIndex:(unsigned int)fp12 withNotification:(BOOL)fp16 removeOld:(BOOL)fp20;
- (void)_addEntry:(id)fp8 withNotification:(BOOL)fp12;
- (id)_createSecureEntryForRequest:(id)fp8 allowOverwrite:(BOOL)fp12;
- (id)_createEntryForDownload:(id)fp8 allowOverwrite:(BOOL)fp12;
- (id)_createEntryForRequest:(id)fp8 allowOverwrite:(BOOL)fp12;
- (id)_downloadHistoryFile;
- (void)_loadDownloadHistoryIfNeeded;
- (void)_removeEntries:(id)fp8 withNotification:(BOOL)fp12;
- (void)_download:(id)fp8 entry:(id)fp12 didFailWithError:(id)fp16;
@end

