/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSString;

@interface EtchedStringView : NSView
{
    NSString *_string;
    NSString *_helpString;
    BOOL _isCentered;
}

+ (id)font;
+ (id)replaceTextField:(id)fp8;
+ (id)lightColor;
+ (id)darkColor;
- (void)dealloc;
- (id)font;
- (id)string;
- (void)setString:(id)fp8;
- (id)accessibilityHelpString;
- (void)setAccessibilityHelpString:(id)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isCentered;
- (void)setCentered:(BOOL)fp8;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)accessibilityIsIgnored;

@end

