/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSButtonCell.h"

@class NSColor;

@interface EtchedStringButtonCell : NSButtonCell
{
    BOOL _isTextCentered;
    int _textTruncation;
    NSColor *_bottomColor;
    NSColor *_topColor;
    BOOL _usesGradientText;
}

+ (id)font;
+ (id)_defaultTopColor;
+ (id)_defaultBottomColor;
- (id)initTextCell:(id)fp8;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)setBottomColor:(id)fp8;
- (id)bottomColor;
- (void)setTopColor:(id)fp8;
- (id)topColor;
- (struct _NSRect)textRectForFrame:(struct _NSRect)fp8;
- (id)attributedTitle;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)setTextTruncation:(int)fp8;
- (int)textTruncation;
- (void)setTextCentered:(BOOL)fp8;
- (BOOL)isTextCentered;
- (BOOL)usesGradientText;
- (void)setUsesGradientText:(BOOL)fp8;
- (BOOL)_needRedrawOnWindowChangedKeyState;

@end

