/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RolloverTextButton.h"

@class NSString;

@interface ExtendedValidationCertificateButton : RolloverTextButton
{
    NSString *_fullTitle;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (id)fullTitle;
- (void)setFullTitle:(id)fp8;

@end

