/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class FadingOverlay;

@interface FadingOverlayView : NSView
{
    FadingOverlay *_fadingOverlay;
    float _fractionFadedIn;
}

+ (float)maximumOverlayAlpha;
- (void)dealloc;
- (void)detachFromFadingOverlay;
- (void)drawRect:(struct _NSRect)fp8;
- (float)fractionFadedIn;
- (id)initWithFadingOverlay:(id)fp8;
- (id)fadingOverlay;
- (void)setFractionFadedIn:(float)fp8;
- (void)setHolesNeedUpdateInRect:(struct _NSRect)fp8;
- (void)targetWindowDidEndLiveResize;
- (void)targetWindowWillStartLiveResize;

@end

