/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RolloverTextButton.h"

@class NSMenu, WebBookmark;

@interface FavoriteButton : RolloverTextButton
{
    WebBookmark *_bookmark;
    NSMenu *_contentsMenu;
    BOOL _drawForDragging;
    BOOL _ignoreModifiers;
    BOOL _showUnreadRSSCount;
    BOOL _menuOpen;
}

+ (void)_updateCellClass;
+ (id)draggedButton;
+ (void)setDraggedButton:(id)fp8;
+ (id)font;
- (void)registerForDraggedTypes;
- (void)_setAttributes;
- (id)initWithFrame:(struct _NSRect)fp8;
- (id)initWithBookmark:(id)fp8 frame:(struct _NSRect)fp12 showUnreadRSSCounts:(BOOL)fp28;
- (id)bookmarkSource;
- (void)dealloc;
- (void)setTitle:(id)fp8;
- (id)bookmark;
- (BOOL)automaticallyOpensInTabs;
- (void)setBookmark:(id)fp8;
- (id)_tabLocation;
- (void)_goToBookmark;
- (void)_goToAllInTabsCombiningNewsFeeds:(id)fp8;
- (void)_goToAllInTabs:(id)fp8;
- (void)_goToInNewTab:(id)fp8;
- (void)_goToInNewWindow:(id)fp8;
- (void)_titleChangeSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)_editTitle:(id)fp8;
- (void)_editAddress:(id)fp8;
- (void)_editContents:(id)fp8;
- (void)_revealFavorite:(id)fp8;
- (void)_copyBookmark:(id)fp8;
- (id)menu;
- (BOOL)hasContentsMenu;
- (id)contentsMenu;
- (BOOL)_shouldDrawDragged;
- (void)_setShouldDrawDragged:(BOOL)fp8;
- (void)drawForDraggingImageInRect:(struct _NSRect)fp8;
- (void)_bookmarksReloaded:(id)fp8;
- (void)startObservingBookmarkReloads;
- (void)stopObservingBookmarkReloads;
- (void)performDragFromEvent:(id)fp8;
- (BOOL)mouseDownIsInMenuArrow:(id)fp8;
- (BOOL)canDragHorizontally:(BOOL)fp8 fromMouseDown:(id)fp12;
- (BOOL)shouldShowContentsMenuFromEvent:(id)fp8 waitedForDragDelay:(BOOL)fp12;
- (void)popUpContentsMenu;
- (BOOL)isMenuOpen;
- (void)moveDown:(id)fp8;
- (void)moveUp:(id)fp8;
- (void)performClick:(id)fp8;
- (void)performClickIgnoringModifiers:(id)fp8;
- (void)activateButtonAndPopUpContentsMenu;
- (void)mouseDown:(id)fp8;
- (void)otherMouseDown:(id)fp8;
- (void)rightMouseDown:(id)fp8;
- (unsigned int)draggingSourceOperationMaskForLocal:(BOOL)fp8;
- (void)deleteFolderSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)confirmDeletingFolder;
- (void)deleteAfterDrag;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
- (id)bookmarksFromPasteboard:(id)fp8;
- (int)numberOfBookmarksOnPasteboard:(id)fp8;
- (unsigned int)determineDragOperation:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingExited:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (BOOL)canAcceptDroppedBookmarkAtPoint:(struct _NSPoint)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)acceptDroppedBookmark:(id)fp8;
- (id)_hitTest:(const struct _NSPoint *)fp8 dragTypes:(id)fp12;

@end

