/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RolloverTextButtonCell.h"

@class NSArray;

@interface FavoriteButtonCell : RolloverTextButtonCell
{
    int _indicator;
    BOOL _shouldDrawDragged;
    BOOL _isTrackingMouseDown;
    NSArray *_accessibilityAttributes;
    NSArray *_accessibilityActions;
}

+ (id)squareImage;
+ (id)highlightedSquareImage;
+ (id)triangleImage;
+ (id)highlightedTriangleImage;
- (void)dealloc;
- (id)indicatorImage;
- (struct _NSSize)cellSize;
- (struct _NSRect)titleRectForBounds:(struct _NSRect)fp8;
- (struct _NSRect)imageRectForBounds:(struct _NSRect)fp8;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)setIndicator:(int)fp8;
- (int)indicator;
- (void)accessibilityPerformAction:(id)fp8;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (id)accessibilityActionNames;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (BOOL)accessibilityIsIgnored;
- (void)setShouldDrawDragged:(BOOL)fp8;
- (BOOL)_shouldDrawDragged;
- (BOOL)_shouldDrawBezel;
- (BOOL)showsBorderOnlyWhileMouseInside;
- (void)setTrackingMouseDown:(BOOL)fp8;
- (BOOL)isTrackingMouseDown;

@end

