/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RolloverTextButtonCellOld.h"

@interface FavoriteButtonCellOld : RolloverTextButtonCellOld
{
    int _indicator;
}

+ (id)squareImage;
+ (id)highlightedSquareImage;
+ (id)triangleImage;
+ (id)highlightedTriangleImage;
- (id)indicatorImage;
- (struct _NSSize)cellSize;
- (struct _NSRect)imageRectForBounds:(struct _NSRect)fp8;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)setIndicator:(int)fp8;
- (int)indicator;
- (void)accessibilityPerformAction:(id)fp8;

@end

