/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSObject<FileLockerDelegate>, NSString;

@interface FileLocker : NSObject
{
    NSString *_path;
    NSString *_hostname;
    NSObject<FileLockerDelegate> *_delegate;
    double _timeout;
    BOOL _locked;
}

- (BOOL)isOnLocalHost;
- (id)computeHostname;
- (id)initWithPath:(id)fp8 delegate:(id)fp12 timeout:(double)fp16;
- (void)dealloc;
- (id)path;
- (id)lockDirectoryPath;
- (id)lockFilePath;
- (id)lockFileContentsDictionary;
- (void)removeLockFile;
- (void)writeLockFile;
- (BOOL)matchesHostNameFromLockDictionary:(id)fp8;
- (BOOL)lockIsNotValid:(id)fp8;
- (int)actionForApparentlyAbandonedLock:(id)fp8 onAttempt:(int)fp12;
- (int)lock;
- (void)unlock;

@end

