/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BannerWithOverlay.h"

@class BrowserCoachMarkController, NSArray, NSButton, NSMutableArray, NSSearchField, NSSegmentedControl, NSString, NSTextField, WebDataSource;

@interface FindBanner : BannerWithOverlay
{
    NSSearchField *searchField;
    NSSegmentedControl *nextPreviousControl;
    NSButton *doneButton;
    NSTextField *statusField;
    BrowserCoachMarkController *_coachMarkController;
    WebDataSource *_highlightedDataSource;
    NSString *_highlightedString;
    unsigned int _matchCount;
    NSArray *_textRects;
    NSMutableArray *_scopeButtons;
    float _initialSearchFieldRightEdge;
    int _lastFindPasteboardChangeCount;
    id _searchTarget;
    BOOL _nextReturnShouldPerformFind;
    BOOL _isLinkedWithFindPasteboard;
    BOOL _displayedMatchesLimited;
    BOOL _textWasEditedSinceLastSearch;
}

+ (int)bannerSortOrder;
+ (BOOL)overlayIgnoresMouseEvents;
- (id)initWithWebView:(id)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (id)bannerNibName;
- (void)didInstallBannerView;
- (void)fadingOverlayNeedsUpdateInRect:(struct _NSRect)fp8;
- (void)hideOverlay;
- (void)viewBelowBannerWasResizedFromFrame:(struct _NSRect)fp8 animationProgress:(float)fp24 installing:(BOOL)fp28;
- (void)willUninstallBannerView;
- (void)cancelSelectionHighlightAnimation;
- (void)initiateSelectionHighlightAnimation;
- (void)findFromNextPreviousControl:(id)fp8;
- (void)findFromSearchField:(id)fp8;
- (void)findNext:(id)fp8;
- (void)findPrevious:(id)fp8;
- (id)addScopeButtonWithTitle:(id)fp8 target:(id)fp12 action:(SEL)fp16 tag:(int)fp20;
- (void)removeAllScopeButtons;
- (id)scopeButtons;
- (BOOL)showsNextAndPreviousButtons;
- (void)setShowsNextAndPreviousButtons:(BOOL)fp8;
- (BOOL)showsDoneButton;
- (void)setShowsDoneButton:(BOOL)fp8;
- (BOOL)control:(id)fp8 textView:(id)fp12 doCommandBySelector:(SEL)fp16;
- (void)controlTextDidChange:(id)fp8;
- (void)focusSearchField;
- (id)searchField;
- (BOOL)readyToFind;
- (id)holesInFadingOverlay:(id)fp8;
- (BOOL)isLinkedWithFindPasteboard;
- (void)reset;
- (void)setIsLinkedWithFindPasteboard:(BOOL)fp8;
- (void)dismissOverlayIfContainsMouseDown:(id)fp8;
- (void)updateHighlightedMatches;

@end

