/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FindBanner.h"

@interface FindBanner (FileInternal)
- (id)_selectionSourceInWebView;
- (void)_adjustLayout;
- (void)_animateSelectedText;
- (BOOL)_canHighlightAllMatches;
- (void)_clearHighlightedMatches;
- (void)_clearSelectionInWebView;
- (BOOL)_findWithDirection:(BOOL)fp8 caseSensitive:(BOOL)fp12 beepOnFailure:(BOOL)fp16 animateOnSuccess:(BOOL)fp20;
- (void)_highlightAllMatchesAllowingOverlay:(BOOL)fp8;
- (id)_imageForBannerControlWithBaseName:(id)fp8;
- (void)_makeSearchFieldFirstResponder;
- (void)_resetHighlightedMatches;
- (id)_searchString;
- (void)_setStatus:(id)fp8;
- (void)_startObservingWindowAndBannerView;
- (id)_statusStringFromMatchCount;
- (void)_stopObservingWindowAndBannerView;
- (void)_updateFindPasteboardFromSearchField;
- (void)_updateHighlightedMatchesAllowingOverlay:(BOOL)fp8;
- (void)_updateNextAndPreviousButtons;
- (void)_updateSearchFieldFromFindPasteboard;
- (void)_windowDidUpdate:(id)fp8;
@end

