/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class DOMElement, DOMHTMLInputElement, NSMutableArray, NSMutableDictionary, WebFrame;

@interface FormAutoFiller : NSObject
{
    WebFrame *_frame;
    DOMElement *_form;
    int _formType;
    DOMHTMLInputElement *_usernameElement;
    DOMHTMLInputElement *_passwordElement;
    NSMutableArray *_autoFilledControls;
    NSMutableDictionary *_fieldsFilledFromAB;
    NSMutableArray *_continuationFields;
    BOOL _hasAutoFilled;
}

+ (id)_markAutoFilledColor;
+ (id)autoFillerForFrame:(id)fp8 form:(id)fp12 create:(BOOL)fp16;
+ (id)matchForControl:(id)fp8 rep:(id)fp12 fieldLabels:(id)fp16 useFieldName:(BOOL)fp20 foundByPageScan:(char *)fp24;
+ (id)abMatchInFrame:(id)fp8 form:(id)fp12 fieldName:(id)fp16;
+ (BOOL)isContinuationField:(id)fp8 inFrame:(id)fp12 form:(id)fp16;
+ (void)recordABMatch:(id)fp8 inFrame:(id)fp12 form:(id)fp16 fieldName:(id)fp20;
+ (void)clearAutoFillStateForFrame:(id)fp8;
+ (void)clearAutoFilledTextField:(id)fp8 inFrame:(id)fp12 form:(id)fp16;
+ (int)indexOfItemInSelectElement:(id)fp8 forSynonyms:(id)fp12;
+ (id)radioButtonGroupContaining:(id)fp8 inFormElements:(id)fp12;
+ (int)indexOfItemInRadioButtonGroup:(id)fp8 forSynonyms:(id)fp12;
+ (id)fieldNameForAutoFillOfControl:(id)fp8 rep:(id)fp12 respectHTMLAutocompleteAttribute:(BOOL)fp16;
- (id)init;
- (void)dealloc;
- (id)visibleControlsInForm;
- (void)_scanElements;
- (int)formType;
- (id)usernameElement;
- (id)passwordElement;
- (int)_itemInSelectElement:(id)fp8 forMatch:(id)fp12;
- (id)_decomposeStreetAddress:(id)fp8 style:(int)fp12;
- (void)_insertABValue:(id)fp8 inTextFieldElement:(id)fp12 match:(id)fp16 fieldName:(id)fp20;
- (int)_reflectMultiFieldMatch:(id)fp8 inControls:(id)fp12 currIndex:(unsigned int)fp16 fieldName:(id)fp20 isPhoneNumber:(BOOL)fp24;
- (int)_reflectAutoFillMatch:(id)fp8 inControls:(id)fp12 currIndex:(int)fp16 fieldName:(id)fp20;
- (BOOL)hasAutoFilled;
- (BOOL)autoFill;
- (void)autoFillAddressStartingAtControl:(id)fp8 match:(id)fp12;
- (int)autoFillPhoneOrZipStartingAtControl:(id)fp8 match:(id)fp12;
- (void)recordABMatch:(id)fp8 fieldName:(id)fp12;
- (void)recordABContinuationField:(id)fp8;
- (void)clearAutoFilledTextField:(id)fp8;

@end

