/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface FormToABBinder : NSObject
{
    NSDictionary *_abPointers;
    NSArray *_fieldLabels;
    NSDictionary *_synonyms;
}

+ (void)loadBinders;
+ (void)clearBinders;
+ (id)abPointerForControl:(id)fp8 rep:(id)fp12 useFieldName:(BOOL)fp16;
+ (id)synonymsForMatch:(id)fp8;
- (void)_indexMapping:(id)fp8;
- (id)initWithPath:(id)fp8;
- (void)dealloc;
- (id)abPointerForControl:(id)fp8 rep:(id)fp12 useFieldName:(BOOL)fp16 foundByPageScan:(char *)fp20;
- (id)synonymsForMatch:(id)fp8;

@end

