/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionController.h"

@class DOMElement, DOMHTMLInputElement, NSString;

@interface FormCompletionController : CompletionController
{
    DOMHTMLInputElement *_element;
    NSString *_fieldName;
    DOMElement *_form;
    BOOL _isLoginForm;
}

+ (BOOL)previousDataCompletionEnabled;
+ (void)setPreviousDataCompletionEnabled:(BOOL)fp8;
+ (BOOL)shouldSaveFormData;
+ (BOOL)addressBookCompletionEnabled;
+ (void)setAddressBookCompletionEnabled:(BOOL)fp8;
+ (BOOL)passwordCompletionEnabled;
+ (void)setPasswordCompletionEnabled:(BOOL)fp8;
+ (BOOL)shouldSaveUsernamesAndPasswords;
+ (void)verifyKeychainAccessWithWebView:(id)fp8;
+ (id)_cryptData:(id)fp8 encode:(BOOL)fp12;
+ (void)_loadCompletionDB;
+ (void)_pruneCompletionDB;
+ (void)_reapABMarker:(id)fp8 forFrame:(id)fp12 fieldName:(id)fp16;
+ (void)_saveCompletionDB:(id)fp8;
+ (void)_saveCompletionDBSoon;
+ (void)_appWillTerminate:(id)fp8;
+ (id)domainsWithPreviousData;
+ (void)clearPreviousDataForDomain:(id)fp8;
+ (void)clearPreviousDataDatabase;
+ (BOOL)_frame:(id)fp8 sourceFrame:(id)fp12 willSubmitLoginForm:(id)fp16 withValues:(id)fp20 autoFiller:(id)fp24 submissionListener:(id)fp28;
+ (void)_passwordSheetDismissed:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
+ (void)_frame:(id)fp8 sourceFrame:(id)fp12 willSubmitRegularForm:(id)fp16 withValues:(id)fp20;
+ (void)frame:(id)fp8 sourceFrame:(id)fp12 willSubmitForm:(id)fp16 withValues:(id)fp20 submissionListener:(id)fp24;
+ (unsigned int)_indexOfMarkerInMatches:(id)fp8 matchingABMatch:(id)fp12;
+ (id)_abSingleValue:(id)fp8 key:(id)fp12;
+ (id)_abValuesForProperty:(id)fp8 key:(id)fp12 label:(id)fp16;
+ (void)_addABMatchesToArray:(id)fp8 forString:(id)fp12 atABPointer:(id)fp16;
+ (void)_addPreviousDataMatchesToArray:(id)fp8 forString:(id)fp12 frame:(id)fp16 fieldName:(id)fp20;
+ (id)_credentialMatchesForString:(id)fp8 frame:(id)fp12;
+ (id)_matchesForString:(id)fp8 frame:(id)fp12 fieldName:(id)fp16 control:(id)fp20;
+ (id)currentFormInFrame:(id)fp8;
+ (id)firstFormInFrame:(id)fp8;
+ (id)currentOrFirstFrameAndForm:(id *)fp8 inWebView:(id)fp12;
+ (BOOL)_autoFillPasswordInFrame:(id)fp8 autoFiller:(id)fp12;
+ (BOOL)autoFillInWebView:(id)fp8;
+ (id)preFillForm:(id)fp8 inFrame:(id)fp12;
+ (void)preFillInWebFrame:(id)fp8;
+ (BOOL)credentialIsNeverSaveMarker:(id)fp8;
+ (void)clearAutoFillStateForFrame:(id)fp8;
- (id)sourceFieldFont;
- (struct _NSRect)sourceFieldFrame;
- (id)deepestViewContainingSourceField;
- (id)sourceFieldString;
- (void)setSourceFieldString:(id)fp8;
- (struct _NSRange)sourceFieldSelectedRange;
- (void)performSourceFieldAction;
- (void)replaceSourceFieldCharactersInRange:(struct _NSRange)fp8 withString:(id)fp16 selectingFromIndex:(int)fp20;
- (id)queryResultsForString:(id)fp8 startingMatch:(unsigned int *)fp12;
- (id)initWithDOMElement:(id)fp8 webFrame:(id)fp12;
- (void)dealloc;
- (id)webFrame;
- (float)_widestMatchWidth;
- (struct _NSRect)windowFrame;
- (void)buildUI;
- (void)sourceFieldTextDidChange;
- (BOOL)doSourceFieldCommandBySelector:(SEL)fp8;
- (BOOL)textField:(id)fp8 shouldHandleEvent:(id)fp12;
- (BOOL)shouldSuppressAutocompleteForPartialString:(id)fp8;
- (void)reflectSelectedRow;
- (void)reflectFinalSelectedRow;
- (unsigned int)maxStringLength;
- (id)intermediateMatchingStringForResult:(id)fp8;
- (id)finalMatchingStringForResult:(id)fp8;
- (BOOL)leavingFieldReflectsFinalString;
- (BOOL)returnDoesActionWhenShowingDropDown;
- (BOOL)showsDropDownForSingleMatch;

@end

