/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FormDelegate.h"

@interface FormDelegate (FileInternal)
- (void)_didEditFormElement:(id)fp8 inFrame:(id)fp12;
- (BOOL)_shouldIgnoreFormTextChangesInFrame:(id)fp8;
- (void)_clearEditedFormsInFrame:(id)fp8;
@end

