/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "WebFormDelegate-Protocol.h"

@class BrowserDocument, FormCompletionController, NSMutableDictionary;

@interface FormDelegate : NSObject <WebFormDelegate>
{
    FormCompletionController *_completionController;
    BrowserDocument *_document;
    NSMutableDictionary *_editedForms;
}

- (void)dealloc;
- (void)frame:(id)fp8 sourceFrame:(id)fp12 willSubmitForm:(id)fp16 withValues:(id)fp20 submissionListener:(id)fp24;
- (void)textDidChangeInTextArea:(id)fp8 inFrame:(id)fp12;
- (void)textDidChangeInTextField:(id)fp8 inFrame:(id)fp12;
- (void)textFieldDidBeginEditing:(id)fp8 inFrame:(id)fp12;
- (void)textFieldDidEndEditing:(id)fp8 inFrame:(id)fp12;
- (BOOL)textField:(id)fp8 doCommandBySelector:(SEL)fp12 inFrame:(id)fp16;
- (BOOL)textField:(id)fp8 shouldHandleEvent:(id)fp12 inFrame:(id)fp16;
- (id)initWithDocument:(id)fp8;
- (void)dataSourceHasChangedForFrame:(id)fp8;
- (BOOL)formWasEdited;
- (void)formWillHide;
- (void)frameLayoutHasChanged:(id)fp8;
- (void)setDocument:(id)fp8;

@end

