/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "Activity-Protocol.h"
#import "ActivityWithChildren-Protocol.h"
#import "CancellableActivity-Protocol.h"

@class NSError, NSMutableArray, ResourceProgressEntry, WebFrame;

@interface FrameProgressEntry : NSObject <Activity, ActivityWithChildren, CancellableActivity>
{
    WebFrame *_frame;
    ResourceProgressEntry *_provisionalMainResourceEntry;
    NSError *_provisionalError;
    ResourceProgressEntry *_committedMainResourceEntry;
    NSMutableArray *_committedChildren;
    NSError *_committedError;
    BOOL _committedChildrenSorted;
}

+ (BOOL)_isDocumentHTMLForDataSource:(id)fp8;
+ (id)entryWithFrame:(id)fp8;
- (id)_initWithFrame:(id)fp8;
- (void)dealloc;
- (id)mainResourceEntry;
- (void)_setCommittedError:(id)fp8;
- (void)_setProvisionalError:(id)fp8;
- (void)_setCommittedMainResourceEntry:(id)fp8;
- (void)_setProvisionalMainResourceEntry:(id)fp8;
- (void)provisionalDataSourceWasCommitted;
- (void)setError:(id)fp8 forDataSource:(id)fp12;
- (void)addChild:(id)fp8 forDataSource:(id)fp12;
- (void)trackSubresource:(id)fp8 forDataSource:(id)fp12;
- (void)trackSubframe:(id)fp8 fromDataSource:(id)fp12;
- (void)titleChangedForSubframe:(id)fp8;
- (id)error;
- (BOOL)useSingletonChildForDisplay;
- (unsigned int)numberOfChildren;
- (unsigned int)_numberOfChildrenOfDataSource:(id)fp8;
- (id)childAtIndex:(unsigned int)fp8;
- (id)_childAtIndex:(unsigned int)fp8 ofDataSource:(id)fp12;
- (unsigned int)errorCount;
- (void)resetProvisionalLoad;
- (id)entryForFrame:(id)fp8;
- (int)activityStageOfCommittedChildren;
- (int)stage;
- (id)frame;
- (id)URL;
- (id)_urlStringForTitle;
- (id)title;
- (id)_childrenStatusSummary;
- (id)statusString;
- (void)cancel:(id)fp8;
- (int)displayOrder;
- (void)sortChildren;
- (void)download;
- (void)open;

@end

