/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BookmarkSource.h"

#import "SpotlightDataSource-Protocol.h"

@class HistoryTextCache, HistoryThumbnailCache, NSMenu, NSMutableDictionary, NSMutableSet, NSUndoManager, WebHistory;

@interface GlobalHistory : BookmarkSource <SpotlightDataSource>
{
    WebHistory *_webHistory;
    struct __CFDateFormatter *_dateFormatter;
    HistoryTextCache *_textCache;
    HistoryThumbnailCache *_thumbnailCache;
    NSUndoManager *_undoManager;
    BOOL _performingUndoableAction;
    NSMenu *_historyMenu;
    unsigned int _builtInHistoryMenuItemsCount;
    BOOL _savePending;
    NSMutableSet *_pendingSpotlightCacheAdditions;
    NSMutableDictionary *_pendingSpotlightCacheAdditionsWithFullText;
    NSMutableSet *_pendingSpotlightCacheDeletions;
    BOOL _deleteEntireSpotlightCache;
}

+ (id)historyURL;
+ (id)sharedGlobalHistory;
- (id)init;
- (void)dealloc;
- (void)setUndoManager:(id)fp8;
- (id)undoManager;
- (BOOL)validateUserInterfaceItem:(id)fp8;
- (void)cachePageTextForWebView:(id)fp8;
- (void)cacheThumbnailForWebView:(id)fp8;
- (id)thumbnailForURLString:(id)fp8;
- (id)URLStringMatchesFromCachedPageTextForString:(id)fp8;
- (BOOL)menuHasKeyEquivalent:(id)fp8 forEvent:(id)fp12 target:(id *)fp16 action:(SEL *)fp20;
- (void)menuNeedsUpdate:(id)fp8;
- (id)allItemsForSpotlightDataType:(id)fp8;
- (id)itemsToAddForSpotlightDataType:(id)fp8;
- (id)itemsToDeleteForSpotlightDataType:(id)fp8;
- (void)resetAdditionsAndDeletionsForSpotlightDataType:(id)fp8;
- (void)updateDidEndForSpotlightDataType:(id)fp8;
- (void)updateWillBeginForSpotlightDataType:(id)fp8;
- (id)addressStringForContentItem:(id)fp8;
- (id)bookmarkFromContentItem:(id)fp8;
- (id)bookmarkSourceImage;
- (id)bookmarksFromContentItems:(id)fp8;
- (BOOL)canDeleteContents;
- (BOOL)contentItemCanHaveChildren:(id)fp8;
- (id)contentItemsToInitiallyExpand;
- (id)child:(unsigned int)fp8 ofContentItem:(id)fp12;
- (void)deleteContentItems:(id)fp8 withUndoManager:(id)fp12;
- (id)imageForContentItem:(id)fp8;
- (unsigned int)numberOfChildrenOfContentItem:(id)fp8;
- (id)parentOfContentItem:(id)fp8;
- (id)titleStringForContentItem:(id)fp8;
- (void)clearHistory;
- (BOOL)hasAnyHistoryItems;
- (void)savePendingChangesBeforeTermination;
- (void)setHistoryAgeLimitFromPreferences;
- (void)setHistoryMenu:(id)fp8;
- (void)updateDisplayTitleForHistoryItem:(id)fp8;
- (id)webHistory;

@end

