/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GlobalHistory.h"

@interface GlobalHistory (FileInternal)
- (void)_addHistoryEntry:(id)fp8 toMenu:(id)fp12;
- (void)_addHistoryItemsFromEnumerator:(id)fp8 toSpotlightCacheArray:(id)fp12;
- (void)_addHistoryItemsToSpotlightCacheSoon:(id)fp8;
- (BOOL)_addItemsForDate:(id)fp8 toMenu:(id)fp12 skip:(unsigned int)fp16 limit:(unsigned int)fp20;
- (id)_addSubmenu:(id)fp8 withTitle:(id)fp12;
- (void)_appendHistoryToMenu;
- (void)_clearHistoryFromMenu:(id)fp8;
- (void)_deleteHistoryItemsFromSpotlightCacheSoon:(id)fp8;
- (id)_displayedTitleForEntry:(id)fp8;
- (void)_entriesChanged;
- (id)_entriesFromMixedItems:(id)fp8;
- (void)_forgetCachedInfoAboutHistoryItemsFromNotification:(id)fp8;
- (void)_receivedAllItemsRemovedNotification:(id)fp8;
- (void)_receivedHistoryLoadedNotification:(id)fp8;
- (void)_receivedItemsAddedNotification:(id)fp8;
- (void)_receivedItemsDeletedNotification:(id)fp8;
- (void)_receivedItemsDiscardedWhileLoadingNotification:(id)fp8;
- (int)_recentHistoryLimit;
- (void)_registerForHistoryNotifications;
- (void)_removeEntries:(id)fp8;
- (void)_removeHistoryFromMenu;
- (void)_savePendingChanges;
- (id)_stringForCalendarDate:(id)fp8;
- (void)_takeLocationFromHistoryEntry:(id)fp8;
- (id)_textCache;
- (id)_thumbnailCache;
- (void)_undoRemoveEntries:(id)fp8;
- (void)_updateHistoryMenu;
- (BOOL)validate__takeLocationFromHistoryEntry:(id)fp8;
- (BOOL)validate__clearHistoryFromMenu:(id)fp8;
@end

