/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionController.h"

@class NSString;

@interface GoogleSuggestionController : CompletionController
{
    NSString *_suggestion;
    NSString *_searchString;
}

- (void)dealloc;
- (id)queryResultsForString:(id)fp8 startingMatch:(unsigned int *)fp12;
- (void)reflectSelectedRow;
- (BOOL)canDeselectAllMatches;
- (id)suggestion;
- (id)searchString;
- (void)_setSuggestion:(id)fp8 forSearchString:(id)fp12;
- (id)_sniffedSuggestionFromWebView:(id)fp8;
- (void)sniffForSuggestionInWebView:(id)fp8 withSearchString:(id)fp12;

@end

