/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, NSMutableDictionary, NSTimer;

@interface Heartbeat : NSObject
{
    NSLock *_clientsLock;
    NSMutableDictionary *_windowToClients;
    NSTimer *_timer;
    double _birthDate;
    BOOL _running;
}

+ (id)sharedHeartbeat;
- (id)init;
- (void)_heartbeat;
- (void)_startHeartbeatRunLoop;
- (void)addHeartbeatView:(id)fp8;
- (void)removeHeartbeatView:(id)fp8;
- (id)clients;

@end

