/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "HistoryThumbnailView.h"

@interface HistoryThumbnailView (FileInternal)
- (id)_fallbackString;
- (id)_fallbackStringAttributes;
- (void)_drawFallbackString;
- (void)_historyThumbnailDidChange:(id)fp8;
- (struct _NSRect)_imageBoundingRect;
- (void)_refreshImage;
- (void)_resetFallbackString;
- (void)_setImage:(id)fp8;
@end

