/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "HistoryThumbnailCache.h"

@interface HistoryThumbnailCache (FileInternal)
- (id)_filenameForThumbnailWithURLString:(id)fp8;
- (id)_filePathForThumbnailWithURLString:(id)fp8;
- (void)_postThumbnailChangedNotificationForURLString:(id)fp8;
- (id)_thumbnailsDirectoryPath;
@end

