/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSAttributedString, NSImage, NSString;

@interface HistoryThumbnailView : NSView
{
    NSImage *_image;
    NSString *_URLString;
    NSAttributedString *_fallbackString;
}

- (void)dealloc;
- (void)drawRect:(struct _NSRect)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)setURLString:(id)fp8;
- (id)URLString;

@end

