/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "HistoryTextCache.h"

@interface HistoryTextCache (FileInternal)
- (void)_cancelFlushTimer;
- (void)_detachFlushThread;
- (void)_flushSoon;
- (void)_runFlushThread;
- (void)_initializeSearchIndexCreatingIfNecessary:(BOOL)fp8;
- (BOOL)_needsCompaction;
- (BOOL)_removeCachedPageTextForURLStringWithoutFlushing:(id)fp8;
- (void)_setNeedsCompaction:(BOOL)fp8;
@end

