/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "FileLockerDelegate-Protocol.h"

@class NSConditionLock, NSString, NSTimer;

@interface HistoryTextCache : NSObject <FileLockerDelegate>
{
    struct __SKIndex *_searchIndexRef;
    NSString *_searchIndexFilePath;
    NSConditionLock *_flushCountConditionLock;
    NSTimer *_flushTimer;
    BOOL _needsCompaction;
}

- (id)cachePageTextForWebView:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)flushNow;
- (void)removeCachedPageTextForURLString:(id)fp8;
- (void)removeCachedPageTextForWebHistoryItems:(id)fp8;
- (void)removeAllCachedPageText;
- (id)URLStringMatchesFromCachedPageTextForString:(id)fp8;
- (int)fileLocker:(id)fp8 actionForApparentlyAbandonedLock:(id)fp12 onAttempt:(int)fp16;
- (void)fileLocker:(id)fp8 lockWasStolen:(id)fp12;

@end

