/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDocument.h"

@class FindBanner, WebDataSource, WebResource;

@interface HTMLSourceDocument : NSDocument
{
    WebDataSource *_dataSource;
    WebResource *_resource;
    FindBanner *_findBanner;
    BOOL _isSaving;
    BOOL _isSaved;
}

- (id)initWithDataSource:(id)fp8;
- (id)initWithResource:(id)fp8;
- (void)close;
- (void)dealloc;
- (void)makeWindowControllers;
- (id)dataRepresentationOfType:(id)fp8;
- (void)saveDocumentTo:(id)fp8;
- (id)fileName;
- (id)fileType;
- (id)displayName;
- (id)controller;
- (id)controllerWebView;
- (id)dataSource;
- (id)resource;
- (void)setDataSource:(id)fp8;
- (void)setResource:(id)fp8;
- (BOOL)isSaved;
- (void)browserDocumentLoadingFinished:(id)fp8;
- (BOOL)canMakeTextLarger;
- (BOOL)canMakeTextSmaller;
- (BOOL)canMakeTextStandardSize;
- (void)makeTextLarger:(id)fp8;
- (void)makeTextSmaller:(id)fp8;
- (void)makeTextStandardSize:(id)fp8;
- (void)safari_printDocument:(id)fp8;
- (BOOL)validateUserInterfaceItem:(id)fp8;
- (void)printShowingPrintPanel:(BOOL)fp8;
- (id)currentBanners;
- (id)viewBelowBanner:(id)fp8;
- (void)banner:(id)fp8 viewBelow:(id)fp12 wasResizedFromFrame:(struct _NSRect)fp16 animationProgress:(float)fp32 installing:(BOOL)fp36;
- (BOOL)findBanner:(id)fp8 doSearchFieldCommandBySelector:(SEL)fp12;
- (void)bannerWillUninstall:(id)fp8;
- (void)showFindPanel:(id)fp8;
- (void)findNext:(id)fp8;
- (void)findPrevious:(id)fp8;
- (void)hideFindBanner:(id)fp8;

@end

