/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SearchableWebView.h"

@interface HTMLSourceWebView : SearchableWebView
{
}

- (id)webView:(id)fp8 contextMenuItemsForElement:(id)fp12 defaultMenuItems:(id)fp16;
- (unsigned int)webView:(id)fp8 dragDestinationActionMaskForDraggingInfo:(id)fp12;

@end

