/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WindowController.h"

@class SearchableWebView;

@interface HTMLSourceController : WindowController
{
    SearchableWebView *webView;
}

- (void)dealloc;
- (void)updateMinimumFontSize;
- (BOOL)window:(id)fp8 willHandleMouseDownEvent:(id)fp12;
- (void)windowDidLoad;
- (id)webView;
- (void)webPreferencesDidChange:(id)fp8;
- (void)setString:(id)fp8;
- (void)selectLineAtIndex:(int)fp8;
- (id)targetForSearch;
- (void)close;

@end

