/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TextCell.h"

@class NSImage;

@interface ImageAndTextCell : TextCell
{
    NSImage *_leftImage;
    NSImage *_rightImage;
    unsigned int _leftMargin;
}

- (id)initTextCell:(id)fp8;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)setLeftImage:(id)fp8;
- (id)leftImage;
- (void)setRightImage:(id)fp8;
- (id)rightImage;
- (void)setLeftMargin:(unsigned int)fp8;
- (unsigned int)leftMargin;
- (void)getLeftImageFrame:(struct _NSRect *)fp8 rightImageFrame:(struct _NSRect *)fp12 andTextFrame:(struct _NSRect *)fp16 fromCellFrame:(struct _NSRect)fp20;
- (struct _NSRect)leftImageFrameFromCellFrame:(struct _NSRect)fp8;
- (struct _NSRect)rightImageFrameFromCellFrame:(struct _NSRect)fp8;
- (struct _NSRect)textFrameFromCellFrame:(struct _NSRect)fp8;
- (void)editWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 event:(id)fp36;
- (void)selectWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 start:(int)fp36 length:(int)fp40;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (struct _NSSize)cellSize;

@end

