/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTask;

@interface ISyncController : NSObject
{
    id _delegate;
    NSTask *_checkSyncInProgressTask;
    NSTask *_checkCanSynchronizeBookmarksTask;
    NSTask *_checkSynchronizesBookmarksTask;
    NSTask *_setSynchronizesBookmarksTask;
    BOOL _syncInProgress;
    BOOL _canSynchronizeBookmarks;
    BOOL _synchronizesBookmarks;
}

+ (id)safariTool;
+ (id)runSafariToolWithArguments:(id)fp8;
+ (void)registerSyncClient;
+ (void)initiateBookmarksSync;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (id)monitorSafariToolWithArgument:(id)fp8;
- (BOOL)isSyncInProgress;
- (void)setSyncInProgress:(BOOL)fp8;
- (BOOL)canISyncSynchronizeBookmarks;
- (void)setCanSynchronizeBookmarks:(BOOL)fp8;
- (void)setSetSynchronizesBookmarksTask:(id)fp8;
- (void)setISyncSynchronizesBookmarks:(BOOL)fp8;
- (BOOL)iSyncSynchronizesBookmarks;
- (void)setSynchronizesBookmarks:(BOOL)fp8;
- (void)setCheckSyncInProgressTask:(id)fp8;
- (void)setCheckCanSynchronizeBookmarksTask:(id)fp8;
- (void)setCheckSynchronizesBookmarksTask:(id)fp8;
- (void)checkSyncInProgress;
- (void)checkCanSynchronizeBookmarks;
- (void)checkSynchronizesBookmarks;
- (void)taskDidExit:(id)fp8;
- (void)synchronizationDidStart:(id)fp8;
- (void)synchronizationDidFinish:(id)fp8;
- (void)synchronizedDataClassesDidChange:(id)fp8;
- (void)refreshStatus;
- (BOOL)userHasDotMacAccount;
- (id)init;
- (void)dealloc;

@end

