/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface KeyValuePair : NSObject
{
    id key;
    id value;
    unsigned int hash;
}

+ (id)pair;
+ (id)pairWithKey:(id)fp8 value:(id)fp12;
- (id)initWithKey:(id)fp8 value:(id)fp12;
- (void)dealloc;
- (void)setPairKey:(id)fp8;
- (void)setPairValue:(id)fp8;
- (id)pairKey;
- (id)pairValue;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;

@end

