/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSArray, NSEvent, NSMutableArray, NSTimer;

@interface ListView : NSView
{
    NSMutableArray *_views;
    NSMutableArray *_selectedViews;
    NSArray *_selectedViewsAfterMouseDown;
    id _delegate;
    unsigned int _mouseDownIndex;
    unsigned int _lastDragIndex;
    NSTimer *_autoscrollTimer;
    NSEvent *_autoscrollTriggerEvent;
}

+ (id)stripeColorForRow:(int)fp8;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)awakeFromNib;
- (void)dealloc;
- (void)_fillRect:(struct _NSRect)fp8 forRow:(int)fp24;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (BOOL)acceptsFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (id)selectedViews;
- (id)views;
- (BOOL)setSelected:(BOOL)fp8 forView:(id)fp12;
- (void)setSelected:(BOOL)fp8 fromArray:(id)fp12;
- (void)setSelected:(BOOL)fp8 fromIndex:(unsigned int)fp12 toIndex:(unsigned int)fp16;
- (void)deselectAll;
- (id)hitTest:(struct _NSPoint)fp8;
- (id)_viewForEventIgnoringX:(id)fp8;
- (id)_viewForEvent:(id)fp8;
- (BOOL)isViewSelected:(id)fp8;
- (unsigned int)_firstSelectedIndex;
- (unsigned int)_lastSelectedIndex;
- (void)selectOnlyView:(id)fp8;
- (void)_startAutoscrollTimer:(id)fp8;
- (void)_stopAutoscrollTimer;
- (void)_autoscroll;
- (void)updateSelectionsForView:(id)fp8 inResponseToEvent:(id)fp12;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)mouseDragged:(id)fp8;
- (void)keyDown:(id)fp8;
- (id)menuForEvent:(id)fp8;
- (void)selectAll:(id)fp8;
- (BOOL)validateUserInterfaceItem:(id)fp8;
- (void)_resize;
- (void)setFrame:(struct _NSRect)fp8;
- (void)retile;
- (void)insertView:(id)fp8 atIndex:(unsigned int)fp12;
- (void)removeView:(id)fp8;
- (void)moveView:(id)fp8 toIndex:(unsigned int)fp12;
- (float)listHeight;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingExited:(id)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (void)draggingEnded:(id)fp8;
- (void)windowDidBecomeOrResignKey:(id)fp8;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityAttributeNames;
- (id)_visibleChildren;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (void)accessibilitySetValue:(id)fp8 forAttribute:(id)fp12;

@end

