/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "Activity-Protocol.h"
#import "ActivityWithChildren-Protocol.h"
#import "CancellableActivity-Protocol.h"

@class BrowserWebView, FrameProgressEntry, NSTimer;

@interface LoadProgressMonitor : NSObject <Activity, ActivityWithChildren, CancellableActivity>
{
    FrameProgressEntry *_mainEntry;
    BrowserWebView *_webView;
    NSTimer *_statusUpdateTimer;
    BOOL _havePreviouslyCommitted;
}

- (id)initWithWebView:(id)fp8;
- (void)dealloc;
- (void)_setMainEntry:(id)fp8;
- (void)reset;
- (id)mainEntry;
- (void)close;
- (id)_busyStatus;
- (id)_statusSummary;
- (void)_cancelUpdateStatusTimer;
- (void)_updateStatusNow;
- (void)_updateStatusTimerCallback:(id)fp8;
- (void)_updateStatusSoon;
- (id)_monitorProvisionalDataSourceForFrame:(id)fp8;
- (void)monitorFrame:(id)fp8;
- (void)committedFrame:(id)fp8;
- (void)titleChangedForFrame:(id)fp8;
- (void)finishedLoadingFrame:(id)fp8;
- (void)setError:(id)fp8 forDataSource:(id)fp12;
- (id)title;
- (id)URL;
- (void)open;
- (void)download;
- (id)statusString;
- (int)stage;
- (unsigned int)numberOfChildren;
- (id)childAtIndex:(unsigned int)fp8;
- (void)cancel:(id)fp8;
- (int)displayOrder;
- (void)sortChildren;
- (void)webView:(id)fp8 didLoadResourceFromMemoryCache:(id)fp12 response:(id)fp16 length:(int)fp20 fromDataSource:(id)fp24;
- (id)webView:(id)fp8 identifierForInitialRequest:(id)fp12 fromDataSource:(id)fp16;
- (id)webView:(id)fp8 resource:(id)fp12 willSendRequest:(id)fp16 redirectResponse:(id)fp20 fromDataSource:(id)fp24;
- (void)webView:(id)fp8 resource:(id)fp12 didReceiveAuthenticationChallenge:(id)fp16 fromDataSource:(id)fp20;
- (void)webView:(id)fp8 resource:(id)fp12 didReceiveResponse:(id)fp16 fromDataSource:(id)fp20;
- (void)webView:(id)fp8 resource:(id)fp12 didReceiveContentLength:(unsigned int)fp16 fromDataSource:(id)fp20;
- (void)webView:(id)fp8 resource:(id)fp12 didFinishLoadingFromDataSource:(id)fp16;
- (void)webView:(id)fp8 resource:(id)fp12 didFailLoadingWithError:(id)fp16 fromDataSource:(id)fp20;
- (void)launchApplicationSheetEnded:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)pluginErrorSheetEnded:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)webView:(id)fp8 plugInFailedWithError:(id)fp12 dataSource:(id)fp16;

@end

