/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "LocationChangeHandler.h"

@interface LocationChangeHandler (Errors)
- (id)specializedTitleForError:(id)fp8;
- (id)failingURLFromError:(id)fp8 andDataSource:(id)fp12;
- (id)specializedMessageForError:(id)fp8 dataSource:(id)fp12;
- (id)genericTitleForError:(id)fp8;
- (id)genericMessageForError:(id)fp8 dataSource:(id)fp12;
- (int)errorPageTemplateForError:(id)fp8;
- (id)loadErrorURL;
- (void)setLoadErrorURL:(id)fp8;
- (void)displayOrRememberLocationChangeError:(id)fp8 forDataSource:(id)fp12;
@end

