/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class BrowserWebView, NSTimer, NSURL, PageCurlController, WebHistoryItem;

@interface LocationChangeHandler : NSObject
{
    BrowserWebView *_webView;
    NSURL *_loadErrorURL;
    WebHistoryItem *_previousHistoryItem;
    NSTimer *_pageInfoCacheTimer;
    BOOL _installedWindowScriptObjects;
    PageCurlController *_pageCurlController;
    NSTimer *_pageCurlAnimationTimer;
    struct RefPtr<SafeBrowsingObserverMac> _safeBrowsingObserver;
}

+ (void)startedLoadingFrame:(id)fp8;
+ (void)finishedLoadingFrame:(id)fp8;
- (void)_continueLoadingSite;
- (void)_warnAboutUnsafeSiteWithSecurityInfo:(id)fp8;
- (void)_cancelCheckForFraudulentWebsites;
- (void)_checkForFraudulentWebsitesWithURL:(id)fp8;
- (void)_fraudulentWebsiteCheckCompletedForURL:(id)fp8 withAssessment:(int)fp12 fromMultipleServices:(BOOL)fp16;
- (id)initWithWebView:(id)fp8;
- (void)dealloc;
- (id)previousHistoryItem;
- (void)setPreviousHistoryItem:(id)fp8;
- (void)close;
- (id)_mainFrame;
- (id)_loadMonitor;
- (void)webView:(id)fp8 windowScriptObjectAvailable:(id)fp12;
- (void)webView:(id)fp8 didStartProvisionalLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didReceiveServerRedirectForProvisionalLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didCommitLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didReceiveTitle:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didReceiveIcon:(id)fp12 forFrame:(id)fp16;
- (void)continueHTTPSConnectionSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)continueHTTPSConnectionWithIdentitySheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (BOOL)handleCertificateError:(id)fp8 forDataSource:(id)fp12;
- (void)handleError:(id)fp8 forDataSource:(id)fp12 willTryFallbackURLs:(char *)fp16;
- (void)webView:(id)fp8 locationChangeDone:(id)fp12 forDataSource:(id)fp16;
- (void)webView:(id)fp8 didFailProvisionalLoadWithError:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didChangeLocationWithinPageForFrame:(id)fp12;
- (void)webView:(id)fp8 willPerformClientRedirectToURL:(id)fp12 delay:(double)fp16 fireDate:(id)fp24 forFrame:(id)fp28;
- (void)webView:(id)fp8 didCancelClientRedirectForFrame:(id)fp12;
- (void)webView:(id)fp8 willCloseFrame:(id)fp12;
- (void)webView:(id)fp8 didFinishDocumentLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didFirstLayoutInFrame:(id)fp12;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

