/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TextFieldWithControls.h"

@class NSImage, WebBookmark;

@interface LocationTextField : TextFieldWithControls
{
    BOOL needsToDisplayIcon;
    NSImage *icon;
    WebBookmark *_draggingBookmark;
    int _RSSButtonState;
}

- (void)dealloc;
- (void)displayIcon;
- (void)finishInitialization;
- (void)displayIconIfNecessary;
- (void)setRSSButtonState:(int)fp8;
- (int)RSSButtonState;
- (void)displayIconAfterDelay;
- (void)setIcon:(id)fp8;
- (id)icon;
- (id)proxyIconDraggingImageWithTitle:(id)fp8;
- (BOOL)isIconMouseDownEvent:(id)fp8;
- (BOOL)acceptsFirstResponder;
- (BOOL)acceptsFirstMouse:(id)fp8;
- (BOOL)shouldDelayWindowOrderingForEvent:(id)fp8;
- (void)mouseDown:(id)fp8;
- (id)namesOfPromisedFilesDroppedAtDestination:(id)fp8;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (BOOL)isOpaque;

@end

