/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSImage;

@interface MorphingDragImageView : NSView
{
    NSImage *startImage;
    NSImage *endImage;
    float progress;
}

- (void)dealloc;
- (id)startImage;
- (void)setStartImage:(id)fp8;
- (id)endImage;
- (void)setEndImage:(id)fp8;
- (void)setProgress:(float)fp8;
- (void)drawRect:(struct _NSRect)fp8;

@end

