/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class MorphingDragImageView, NSAnimation, NSImage, NSPasteboard, NSString, NSView, NSWindow;

@interface MorphingDragImageController : NSObject
{
    NSImage *originalImage;
    struct _NSSize maxImageSize;
    struct _NSPoint originalViewLocation;
    NSPasteboard *dragPasteboard;
    id dragSource;
    NSView *sourceView;
    NSWindow *dragWindow;
    MorphingDragImageView *dragImageView;
    NSAnimation *morphAnimation;
    NSAnimation *slideBackAnimation;
    struct CGPoint slideBackStartTranslation;
    struct CGPoint slideBackEndTranslation;
    BOOL dragDone;
    NSWindow *windowUnderMouse;
    id <MorphingDragImageDropTarget> targetUnderMouse;
    BOOL _targetAcceptsDrag;
    BOOL mouseOverSystemWindow;
    NSString *runLoopMode;
    BOOL scheduledRedisplay;
}

+ (void)dragImage:(id)fp8 maximumSize:(struct _NSSize)fp12 fromView:(id)fp20 at:(struct _NSPoint)fp24 pasteboard:(id)fp32 source:(id)fp36 inMode:(id)fp40;
- (void)dealloc;
- (void)morphToDragImage:(id)fp8;
- (id)dragWindow;
- (void)animationDidEnd:(id)fp8;

@end

