/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MorphingDragImageController.h"

@interface MorphingDragImageController (Internal)
- (void)_scheduleRedisplay;
- (void)_redisplayWindows;
- (void)_dragImage:(id)fp8 maximumSize:(struct _NSSize)fp12 fromView:(id)fp20 at:(struct _NSPoint)fp24 pasteboard:(id)fp32 source:(id)fp36 inMode:(id)fp40;
- (void)_prepareForDragWithImage:(id)fp8;
- (void)_runDrag;
- (id)_runLoopMode;
- (void)_handleEvent:(id)fp8;
- (void)_handleMouseDragged;
- (void)_handleFlagsChanged;
- (void)_handleMouseUp;
- (void)_applicationDidResignActive;
- (void)_dragComplete;
- (void)_animateMorphWindow;
- (void)_animateSlideBack;
- (id)_dragInfoForTargetUnderMouse;
- (id)_dragInfoForNoTargetUnderMouse;
- (void)_findWindowUnderMouse:(id *)fp8 level:(int *)fp12 viewUnderMouse:(id *)fp16;
- (void)_setWindowUnderMouse:(id)fp8;
- (void)_setTargetUnderMouse:(id)fp8;
- (void)_sendMovedToPointOnScreenToDragSource;
- (void)_morphToDragImage:(id)fp8 force:(BOOL)fp12;
@end

