/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MorphingDragImageDropTarget <NSObject>
- (unsigned int)morphingDragImage:(id)fp8 draggingEntered:(id)fp12;
- (unsigned int)morphingDragImage:(id)fp8 draggingUpdated:(id)fp12;
- (void)morphingDragImage:(id)fp8 draggingExited:(id)fp12;
- (BOOL)morphingDragImage:(id)fp8 performDragOperation:(id)fp12;
@end

