/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface MultipartForm : NSObject
{
    NSMutableArray *attachments;
    NSString *messageBoundary;
    NSString *attachmentBoundary;
    NSString *contentTypeHeaderValue;
}

+ (void)initialize;
- (id)init;
- (void)addFormData:(id)fp8 content:(id)fp12;
- (void)addFile:(id)fp8 file:(id)fp12;
- (void)addFiles:(id)fp8 files:(id)fp12;
- (id)contentTypeHeaderValue;
- (id)encodeMultipartForm;
- (void)dealloc;

@end

