/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, NSString;

@interface MultipartFormFile : NSObject
{
    NSString *fileName;
    NSData *content;
    NSString *contentType;
    int encoding;
}

- (id)initWithFileName:(id)fp8 content:(id)fp12 contentType:(id)fp16 encoding:(int)fp20;
- (id)fileName;
- (id)content;
- (id)contentType;
- (int)encoding;
- (void)dealloc;

@end

