/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSDraggingInfo-Protocol.h"

@class NSImage, NSPasteboard, NSWindow;

@interface MutableDraggingInfo : NSObject <NSDraggingInfo>
{
    NSWindow *draggingDestinationWindow;
    unsigned int draggingSourceOperationMask;
    struct _NSPoint draggingLocation;
    struct _NSPoint draggedImageLocation;
    NSImage *draggedImage;
    NSPasteboard *draggingPasteboard;
    id draggingSource;
}

- (void)dealloc;
- (id)draggingDestinationWindow;
- (void)setDraggingDestinationWindow:(id)fp8;
- (unsigned int)draggingSourceOperationMask;
- (void)setDraggingSourceOperationMask:(unsigned int)fp8;
- (struct _NSPoint)draggingLocation;
- (void)setDraggingLocation:(struct _NSPoint)fp8;
- (struct _NSPoint)draggedImageLocation;
- (void)setDraggedImageLocation:(struct _NSPoint)fp8;
- (id)draggedImage;
- (void)setDraggedImage:(id)fp8;
- (id)draggingPasteboard;
- (void)setDraggingPasteboard:(id)fp8;
- (id)draggingSource;
- (void)setDraggingSource:(id)fp8;
- (int)draggingSequenceNumber;
- (void)slideDraggedImageTo:(struct _NSPoint)fp8;
- (id)namesOfPromisedFilesDroppedAtDestination:(id)fp8;

@end

