/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTimer;

@interface NetworkController : NSObject
{
    struct __SCDynamicStore *_store;
    NSTimer *_notificationTimer;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)init;
- (BOOL)launchNetworkDiagnosticsForUnreachableURL:(id)fp8;
- (void)_postNetworkChangeNotification:(id)fp8;

@end

