/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSButton, NSPopUpButton, NSTextField, WebBookmark;

@interface NewBookmarksController : NSWindowController
{
    NSPopUpButton *locationPopUp;
    NSTextField *promptField;
    NSTextField *titleField;
    NSButton *addToSafariCheckbox;
    NSButton *addToMailCheckbox;
    NSButton *acceptButton;
    WebBookmark *_bookmark;
    BOOL _titleOnly;
    id _secondaryDelegate;
}

- (id)initWithBookmark:(id)fp8 titleOnly:(BOOL)fp12 secondaryDelegate:(id)fp16;
- (void)dealloc;
- (id)windowNibName;
- (void)acceptNewBookmark:(id)fp8;
- (void)cancelNewBookmark:(id)fp8;
- (void)toggleAddToSafari:(id)fp8;
- (void)toggleAddToMail:(id)fp8;
- (void)awakeFromNib;
- (id)popUp;
- (id)bookmark;
- (id)secondaryDelegate;
- (BOOL)shouldAddBookmarkToSafari;
- (BOOL)shouldAddBookmarkToMail;

@end

