/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSButtonCell.h"

@interface NSButtonCell (BrowserControlExtras)
- (void)updateNonAppearancePropertiesToMatchButtonCell:(id)fp8;
- (void)updateToMatchButtonCell:(id)fp8;
- (id)initWithButtonCell:(id)fp8 andType:(unsigned int)fp12;
- (struct _NSRect)drawGradientTitle:(id)fp8 withFrame:(struct _NSRect)fp12 inView:(id)fp28;
@end

