/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSColor.h"

@interface NSColor (BrowserExtras)
+ (id)_safari_etchedBoldTextColor;
+ (id)_safari_backgroundTabBoldTextColor;
+ (id)_safari_etchedNonBoldTextColor;
+ (id)_safari_etchedTextHighlightColor;
+ (void)configureColorMenu:(id)fp8;
+ (id)createSwatchForColor:(id)fp8;
+ (id)colorWithCGColorRef:(struct CGColor *)fp8;
+ (id)colorWithIntValue:(int)fp8;
- (int)intValue;
@end

