/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (BrowserExtras)
- (int)indexOfCharacterInCString:(const char *)fp8;
- (int)indexOfCharacterInCString:(const char *)fp8 startOffset:(int)fp12;
- (int)indexOfCString:(const char *)fp8;
- (int)indexOfCString:(const char *)fp8 startOffset:(int)fp12;
- (int)indexOfByteString:(const char *)fp8 length:(int)fp12;
- (int)indexOfByteString:(const char *)fp8 length:(int)fp12 startOffset:(int)fp16;
- (id)certificateFromMultipartData;
@end

