/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (BrowserAdditions)
- (id)_safari_stringForKey:(id)fp8;
- (id)_safari_numberForKey:(id)fp8;
- (id)_safari_dataForKey:(id)fp8;
- (void)_safari_setObject:(id)fp8 forUncopiedKey:(id)fp12;
@end

