/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSEvent.h"

@interface NSEvent (BrowserExtras)
+ (BOOL)mouseButtonIsDown;
- (id)eventByChangingKeyEventToCharacters:(id)fp8;
- (id)eventByChangingMouseLocation:(struct _NSPoint)fp8;
- (unsigned short)firstCharacter;
- (unsigned short)firstCharacterIgnoringModifiers;
- (BOOL)isCommandHomeKeyDown;
- (BOOL)isCommandPeriodKeyDown;
- (BOOL)isCommandLeftArrowKeyDown;
- (BOOL)isCommandRightArrowKeyDown;
- (unsigned short)characterCodeWithCarbonModifiers:(unsigned long)fp8;
- (BOOL)isCommandEqualBelowPlusKeyDown;
- (BOOL)isCommandUnderscoreAboveMinusKeyDown;
- (BOOL)isContextMenuEvent;
- (BOOL)isMiddleButtonEvent;
@end

