/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSFileManager.h"

@interface NSFileManager (BrowserNSFileManagerExtras)
- (BOOL)moveDownloadedPath:(id)fp8 toPath:(id)fp12;
- (id)pathForSingleItemAtPath:(id)fp8;
- (BOOL)unmountDevNodeAtPath:(id)fp8;
- (BOOL)unmountVolumeAtPath:(id)fp8;
@end

