/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMenu.h"

@interface NSMenu (TextEncodingSupport)
- (void)addItemToMenuForEncoding:(unsigned long)fp8 withTarget:(id)fp12 action:(SEL)fp16;
- (void)addStandardTextEncodingMenuItemsWithTarget:(id)fp8 action:(SEL)fp12 preferredEncoding:(unsigned long)fp16;
@end

