/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMenu.h"

@interface NSMenu (DebugExtras)
- (id)addItemWithTitle:(id)fp8 target:(id)fp12 action:(SEL)fp16 keyEquivalent:(id)fp20;
@end

