/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (BrowserContextMenu)
- (id)addMenuItemWithTag:(int)fp8 fromArray:(id)fp12;
- (id)addMenuItemWithTitle:(id)fp8 action:(SEL)fp12;
- (id)addMenuItemWithTag:(int)fp8 fromArray:(id)fp12 newAction:(SEL)fp16 newTarget:(id)fp20 newRepresentedObject:(id)fp24;
@end

