/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableData.h"

@interface NSMutableData (BrowserExtras)
- (void)appendFormat:(id)fp8;
- (void)appendEncodedString:(unsigned int)fp8 format:(id)fp12 arguments:(char *)fp16;
- (void)appendEncodedString:(unsigned int)fp8 format:(id)fp12;
@end

