/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (BrowserNSArrayExtras)
- (BOOL)removeUselessMenuItemSeparators;
- (id)_safari_recursivelyMakeObjectsPerformSelector:(SEL)fp8 withObject:(id)fp12;
@end

