/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSOutlineView.h"

@interface NSOutlineView (BrowserNSOutlineViewExtras)
- (float)columnWidthForCellWidth:(float)fp8 atRow:(int)fp12;
- (int)findParentRowOfRow:(int)fp8;
- (void)expandItems:(id)fp8;
- (id)expandedItems;
- (int)lastRowForAnyItemInHierarchicalSelection;
@end

