/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSScrollView.h"

@interface NSScrollView (BrowserNSScrollViewExtras)
- (struct _NSSize)frameSizeForContentSize:(struct _NSSize)fp8;
- (void)scrollVerticallyIfNotAtBottomBy:(float)fp8;
@end

