/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSSplitView.h"

@interface NSSplitView (BrowserExtras)
- (void)tileHorizontallyWithWidthRatio:(float)fp8 minimumItemWidth:(float)fp12;
- (void)tileVerticallyWithHeight:(float)fp8 forSubview:(id)fp12;
- (float)widthRatio;
@end

