/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (BrowserNumberFormattingAdditions)
+ (id)stringRepresentationForBytes:(long long)fp8 requireDecimal:(BOOL)fp16;
+ (id)stringRepresentationForBytes:(long long)fp8;
+ (id)stringRepresentationForBytes:(long long)fp8 ofTotal:(long long)fp16 requireDecimal:(BOOL)fp24;
+ (id)stringRepresentationForBytes:(long long)fp8 ofTotal:(long long)fp16;
@end

