/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextView.h"

@interface NSTextView (BrowserNSTextViewExtras)
- (BOOL)canTakeFindStringFromSelection;
- (void)takeFindStringFromSelection:(id)fp8;
- (BOOL)validate_takeFindStringFromSelection:(id)fp8;
@end

