/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextField.h"

@interface NSTextField (BrowserNSTextFieldExtras)
- (id)safeCurrentEditor;
- (id)safeStringValue;
- (void)safeSetStringValue:(id)fp8;
- (BOOL)hasNonWhitespaceCharacters;
- (BOOL)isFirstResponder;
- (BOOL)convertCommandReturnOrEnterToNewline:(id)fp8;
@end

