/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSToolbar.h"

@interface NSToolbar (BrowserNSToolbarExtras)
- (void)autoSaveConfigurationNow;
- (void)setKeyboardLoopNeedsUpdating:(BOOL)fp8;
- (int)indexOfFirstItemWithIdentifier:(id)fp8;
- (id)toolbarClipView;
@end

