/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@interface NSView (SlidingExtras)
- (struct _NSRect)slidingFrame;
- (void)setSlidingFrame:(struct _NSRect)fp8;
- (void)setFrameWithRedraw:(struct _NSRect)fp8;
@end

