/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindow.h"

@interface NSWindow (BrowserNSWindowExtras)
- (struct _NSSize)constrainProposedFrameSize:(struct _NSSize)fp8;
- (struct _NSRect)standardFrameForProposedSize:(struct _NSSize)fp8;
- (id)scaledBackground;
- (id)texturePattern;
- (BOOL)firstResponderIsDescendantOf:(id)fp8;
- (id)imageForRect:(struct _NSRect)fp8;
- (struct CGImage *)createCGImageForRect:(struct _NSRect)fp8 excludingChildWindows:(id)fp24;
- (BOOL)makeNonDeferred;
- (void)setBottomBorderThickness:(float)fp8 showingSeparator:(BOOL)fp12;
@end

