/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWorkspace.h"

@interface NSWorkspace (DownloadProgressEntryNSWorkspaceExtras)
- (id)pathForApplicationWithIdentifier:(id)fp8 andMinimumVersion:(id)fp12;
- (BOOL)isFileAtPath:(id)fp8 ownedByApplicationAtPath:(id)fp12;
@end

