/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSNumberFormatter.h"

@interface NumberFormatter : NSNumberFormatter
{
    BOOL _strict;
}

- (BOOL)isStrict;
- (void)setStrict:(BOOL)fp8;
- (BOOL)isPartialStringValid:(id *)fp8 proposedSelectedRange:(struct _NSRange *)fp12 originalString:(id)fp16 originalSelectedRange:(struct _NSRange)fp20 errorDescription:(id *)fp28;

@end

