/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSButtonCell.h"

@interface OldSearchScopeButtonCell : NSButtonCell
{
    BOOL _mouseInside;
    struct _NSSize _titleSize;
}

- (id)initTextCell:(id)fp8;
- (void)setTitle:(id)fp8;
- (BOOL)isPressed;
- (BOOL)isSelected;
- (BOOL)_needsRedrawOnMouseInsideChange;
- (BOOL)_shouldShowRollovers;
- (BOOL)_enablesOnWindowChangedKeyState;
- (BOOL)isEnabled;
- (id)_highlightTextColor;
- (id)_normalTextColor;
- (id)_textAttributes;
- (id)_textWithShadowAttributes;
- (id)attributedTitle;
- (BOOL)_getButtonImageParts:(id *)fp8:(id *)fp12:(id *)fp16;
- (float)buttonHeight;
- (struct _NSSize)cellSizeForBounds:(struct _NSRect)fp8;
- (struct _NSRect)titleRectForBounds:(struct _NSRect)fp8;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)mouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;
- (BOOL)_needRedrawOnWindowChangedKeyState;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

