/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSButton, NSString, NSTextView;

@interface OtherUserAgentSheetController : NSWindowController
{
    NSString *_userAgentString;
    NSTextView *userAgentTextView;
    NSButton *acceptButton;
}

- (id)initWithUserAgentString:(id)fp8;
- (void)dealloc;
- (id)windowNibName;
- (void)updateAcceptButton;
- (void)awakeFromNib;
- (void)textDidChange:(id)fp8;
- (BOOL)textView:(id)fp8 doCommandBySelector:(SEL)fp12;
- (id)userAgentString;
- (void)acceptUserAgentString:(id)fp8;
- (void)cancelUserAgentString:(id)fp8;

@end

