/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSOutlineView.h"

@class NSTimer;

@interface OutlineViewPlus : NSOutlineView
{
    BOOL _lockSelection;
    BOOL _acceptsFirstMouse;
    int _doubleClickTimerAction;
    NSTimer *_doubleClickTimer;
    int _clickedRow;
    int _clickedColumn;
}

- (void)dealloc;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)keyDown:(id)fp8;
- (void)deselectRow:(int)fp8;
- (void)selectRow:(int)fp8 byExtendingSelection:(BOOL)fp12;
- (BOOL)selectionShouldChangeFromMouseDownInRow:(int)fp8 tableColumn:(id)fp12;
- (BOOL)shouldEditOnDoubleClick:(id)fp8 inRow:(int)fp12 tableColumn:(id)fp16;
- (BOOL)shouldEditOnSingleClick:(id)fp8 inRow:(int)fp12 tableColumn:(id)fp16;
- (BOOL)_userCanEditTableColumn:(id)fp8 row:(int)fp12;
- (void)_performDoubleClickTimerAction:(id)fp8;
- (id)dragImageForRowsWithIndexes:(id)fp8 tableColumns:(id)fp12 event:(id)fp16 offset:(struct _NSPoint *)fp20;
- (int)_rowFromEvent:(id)fp8;
- (int)_columnFromEvent:(id)fp8;
- (void)mouseDown:(id)fp8;
- (unsigned int)draggingSourceOperationMaskForLocal:(BOOL)fp8;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
- (void)setAcceptsFirstMouse:(BOOL)fp8;
- (BOOL)acceptsFirstMouse:(id)fp8;
- (void)sizeToFit;
- (id)menuForEvent:(id)fp8;
- (void)drawGridInClipRect:(struct _NSRect)fp8;

@end

