/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "Overlay.h"

@interface Overlay (FileInternal)
- (struct _NSRect)_computeOverlayWindowFrame;
- (void)_repositionOverlayWindow;
@end

