/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSURL;

@interface PageLoad : NSObject
{
    NSURL *URL;
    NSDate *startDate;
    NSDate *endDate;
    int status;
    CDAnonymousStruct2 heapBefore;
    CDAnonymousStruct2 heapAfter;
}

+ (id)pageLoadWithURL:(id)fp8;
- (id)initWithURL:(id)fp8;
- (id)URL;
- (void)start:(id)fp8;
- (void)finish:(id)fp8;
- (double)loadTime;
- (int)status;
- (id)statusString;
- (CDAnonymousStruct2)heapBefore;
- (CDAnonymousStruct2)heapAfter;
- (CDAnonymousStruct2)heapDelta;
- (void)clear;
- (id)description;
- (void)dealloc;

@end

