/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class BrowserDocument, NSMutableArray, PageLoadTestLogger, WebView;

@interface PageLoadTestRunner : NSObject
{
    NSObject *delegate;
    PageLoadTestLogger *testLogger;
    BOOL running;
    NSMutableArray *commands;
    NSMutableArray *pageLoadArray;
    int repetitions;
    BrowserDocument *document;
    WebView *webView;
    unsigned int currentPage;
    int currentRepetition;
    BOOL goingBack;
    double totalTime;
    int pagesTimed;
    double totalSquareRootsOfTime;
    double longestTime;
    int cacheClearDirective;
    int profilingDirective;
    int windowType;
    BOOL checkForWorldLeaks;
    double savedDefaultTimeoutInterval;
}

+ (BOOL)shouldPerformAutomatedPageLoadTest;
+ (void)performAutomatedPageLoadTest;
+ (void)addLeakToArray:(id)fp8 count:(int)fp12 name:(id)fp16;
+ (BOOL)closingBrowserWindowsForWorldLeakTest;
+ (id)worldLeaksString;
+ (CDAnonymousStruct2)heapStatistics;
- (void)setSingleTestURL:(id)fp8;
- (void)runOneCommand;
- (void)runTestCommands:(id)fp8;
- (int)loadTestSuite:(id)fp8;
- (int)loadBundleTestSuiteFile:(id)fp8;
- (int)loadTestSuiteFile:(id)fp8;
- (id)init;
- (void)dealloc;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (id)pageLoadArray;
- (id)currentPageLoad;
- (BOOL)running;
- (void)clearCacheWithURL:(id)fp8;
- (void)createWebView;
- (void)goToPage;
- (void)closeBrowserWindows;
- (BOOL)finishCheckingForWorldLeaks;
- (void)closeBrowserWindowsAndFinishCheckingForWorldLeaks;
- (void)checkForWorldLeaksSoon;
- (BOOL)checkForWorldLeaksNow;
- (void)testDone;
- (void)repetitionDone;
- (void)goBack;
- (void)goToNextPage;
- (void)goToPreviousPage;
- (BOOL)canGoToNextPage;
- (BOOL)canGoToPreviousPage;
- (void)setProfilingDirective:(int)fp8;
- (void)resetPageLoads;
- (void)startTest;
- (void)start;
- (void)startGoBackTest;
- (void)stop;
- (void)addPageLoadTime:(double)fp8;
- (double)totalTime;
- (double)longestTime;
- (double)meanTime;
- (double)squareMeanRootTime;
- (void)setCacheClearDirective:(int)fp8;
- (int)cacheClearDirective;
- (void)pageLoadStarted:(id)fp8;
- (void)pageLoadDone:(id)fp8;
- (void)pageLoadPossiblyStarted:(id)fp8;
- (void)pageLoadPossiblyDone:(id)fp8;
- (void)setRepetitions:(int)fp8;
- (int)repetitions;
- (int)currentRepetition;
- (CDAnonymousStruct2)heapBefore;
- (CDAnonymousStruct2)heapAfter;
- (CDAnonymousStruct2)heapDelta;
- (void)setCheckForWorldLeaks:(BOOL)fp8;
- (void)shuffle;
- (void)setCurrentPage:(int)fp8;
- (void)webView:(id)fp8 didStartProvisionalLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (int)windowType;
- (void)setWindowType:(int)fp8;

@end

