/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "ReopensAtLaunch-Protocol.h"

@class NSButton, NSComboBox, NSMutableArray, NSPopUpButton, NSTextField, PageLoadTestRunner, PageLoadTestTableView;

@interface PageLoadTestController : NSWindowController <ReopensAtLaunch>
{
    NSPopUpButton *testModePopupButton;
    NSComboBox *testSuiteComboBox;
    NSButton *startStopButton;
    PageLoadTestTableView *pageLoadTableView;
    NSTextField *statusLabel;
    NSTextField *averageLabel;
    NSTextField *rmsLabel;
    NSTextField *memoryUseLabel;
    NSPopUpButton *windowTypePopUpButton;
    NSPopUpButton *cacheDirectivePopUpButton;
    NSPopUpButton *repetitionsPopUpButton;
    NSButton *hideWindowDuringTestButton;
    NSButton *checkForWorldLeaksButton;
    NSPopUpButton *profilingToolPopUpButton;
    NSTextField *repetitionMessage;
    NSButton *goToNextButton;
    NSButton *goToPreviousButton;
    PageLoadTestRunner *testRunner;
    NSMutableArray *testSuiteList;
    NSMutableArray *singleURLList;
    int testMode;
    BOOL readyToGoBack;
    BOOL doGoBackTest;
    BOOL doingGoBackTest;
}

+ (id)sharedPageLoadTestController;
+ (void)reopen;
- (id)init;
- (void)dealloc;
- (void)updateViews;
- (void)windowDidLoad;
- (void)loadSingleURL:(id)fp8;
- (void)changeTestMode:(id)fp8;
- (void)comboBoxAction:(id)fp8;
- (void)loadTestSuite:(id)fp8;
- (void)startStopTest:(id)fp8;
- (void)setCacheClearDirective:(id)fp8;
- (void)toggleHideWindowDuringTest:(id)fp8;
- (void)toggleCheckForWorldLeaks:(id)fp8;
- (void)setProfilingDirective:(id)fp8;
- (void)setWindowType:(id)fp8;
- (id)windowNibName;
- (int)numberOfRowsInTableView:(id)fp8;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (int)numberOfItemsInComboBox:(id)fp8;
- (id)comboBox:(id)fp8 objectValueForItemAtIndex:(int)fp12;
- (unsigned int)comboBox:(id)fp8 indexOfItemWithStringValue:(id)fp12;
- (void)pageLoadTestRunnerStartedPageLoad:(id)fp8;
- (void)pageLoadTestRunnerFinishedPageLoad:(id)fp8;
- (void)pageLoadTestRunnerStartedTest:(id)fp8;
- (void)pageLoadTestRunnerFinishedTest:(id)fp8;
- (void)pageLoadTestRunner:(id)fp8 detectedWorldLeak:(id)fp12;
- (void)windowWillClose:(id)fp8;
- (void)cut:(id)fp8;
- (void)copy:(id)fp8;
- (void)paste:(id)fp8;
- (void)delete:(id)fp8;
- (void)selectAll:(id)fp8;
- (void)showWindow:(id)fp8;
- (void)changeRepetitions:(id)fp8;
- (void)goToNextPage:(id)fp8;
- (void)goToPreviousPage:(id)fp8;
- (void)refresh:(id)fp8;
- (BOOL)validateUserInterfaceItem:(id)fp8;
- (void)didCloseWebViews:(id)fp8;
- (void)webViewsDidClose;
- (void)shuffle;
- (void)setCurrentItem;

@end

