/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SheetWithTableController.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary;

@interface PasswordsEditor : SheetWithTableController
{
    NSDictionary *_credentialsByProtectionSpace;
    NSMutableArray *_flattenedCredentials;
    NSMutableDictionary *_credentialToProtectionSpaceMap;
    BOOL _ignoreNotifications;
}

- (id)protectionSpaceForCredential:(id)fp8;
- (id)addressStringForCredential:(id)fp8;
- (void)resetCredentials;
- (void)credentialsChanged:(id)fp8;
- (void)startMonitoringCredentials;
- (void)stopMonitoringCredentials;
- (void)dealloc;
- (void)showSheetInWindow:(id)fp8;
- (void)hideSheet:(id)fp8;
- (void)removeSelectedItems:(id)fp8;
- (int)numberOfRowsInTableView:(id)fp8;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;

@end

