/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "EtchedStringButtonCell.h"

@interface PlasticButtonCell : EtchedStringButtonCell
{
}

+ (id)updateCellForButton:(id)fp8;
+ (id)topTextColorWhenDisabled;
- (struct _NSRect)textRectForFrame:(struct _NSRect)fp8;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

