/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

@interface PreferencesModule : NSPreferencesModule
{
}

- (id)imageForPreferenceNamed:(id)fp8;
- (id)highResolutionImageName;
- (void)openHelpPage:(id)fp8;
- (id)helpAnchor;
- (void)removeViews:(id)fp8 collapsingSpaceBetweenRemovedView:(id)fp12 andLowerView:(id)fp16 inModule:(int)fp20;

@end

