/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSViewController.h"

#import "NSPrintPanelAccessorizing-Protocol.h"

@class NSButton;

@interface PrintingAccessoryViewController : NSViewController <NSPrintPanelAccessorizing>
{
    NSButton *printBackgroundsCheckbox;
    NSButton *printHeadersAndFootersCheckbox;
}

+ (id)sharedController;
- (void)updateViews;
- (void)setRepresentedObject:(id)fp8;
- (BOOL)printBackgrounds;
- (BOOL)printHeadersAndFooters;
- (id)keyPathsForValuesAffectingPreview;
- (id)localizedSummaryItems;
- (void)setPrintBackgrounds:(BOOL)fp8;
- (void)setPrintHeadersAndFooters:(BOOL)fp8;
- (void)togglePrintBackgrounds:(id)fp8;
- (void)togglePrintHeadersAndFooters:(id)fp8;

@end

