/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSMatrix;

@interface ResetDialogController : NSWindowController
{
    NSMatrix *optionsMatrix;
}

+ (void)_deleteAllCookies;
+ (void)_removeAllCredentials;
+ (void)_resetWithOptions:(int)fp8;
+ (void)runModalDialog;
- (id)windowNibName;
- (int)_readOptionsMaskFromViews;
- (void)_updateViewsToMatchOptionsMask:(int)fp8;
- (void)windowDidLoad;
- (void)cancel:(id)fp8;
- (void)confirm:(id)fp8;
- (void)showHelp:(id)fp8;

@end

