/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "Activity-Protocol.h"

@class FrameProgressEntry, NSError, NSString, NSURL;

@interface ResourceProgressEntry : NSObject <Activity>
{
    NSError *_error;
    NSURL *_URL;
    NSString *_URLString;
    long long _bytesLoaded;
    long long _bytesExpected;
    int count;
    int resultCode;
    BOOL _done;
    FrameProgressEntry *_parent;
}

- (id)initWithURL:(id)fp8 bytesLoaded:(long long)fp12 bytesExpected:(long long)fp20 error:(id)fp28 parent:(id)fp32 statusCode:(int)fp36 done:(BOOL)fp40;
- (void)dealloc;
- (void)resetParent;
- (void)_valueChange;
- (id)error;
- (void)setError:(id)fp8;
- (long long)bytesLoaded;
- (void)setBytesLoaded:(long long)fp8;
- (long long)bytesExpected;
- (void)setBytesExpected:(long long)fp8;
- (int)count;
- (void)setCount:(int)fp8;
- (int)statusCode;
- (void)setStatusCode:(int)fp8;
- (id)title;
- (id)URL;
- (void)setURL:(id)fp8;
- (id)busyStatus;
- (int)stage;
- (id)statusString;
- (int)displayOrder;
- (void)setDone:(BOOL)fp8;
- (void)open;
- (void)download;

@end

