/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RolloverTrackingButton.h"

@class NSImage;

@interface RolloverImageButton : RolloverTrackingButton
{
    NSImage *_rolloverImage;
}

- (void)_setAttributes;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)awakeFromNib;
- (void)dealloc;
- (void)setRolloverImage:(id)fp8;
- (id)rolloverImage;
- (void)drawRect:(struct _NSRect)fp8;

@end

