/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "EtchedStringButtonCell.h"

@interface RolloverTextButtonCellOld : EtchedStringButtonCell
{
    BOOL _drawsLightText;
}

+ (id)bottomColorForDarkText;
+ (id)topColorForDarkText;
+ (id)bottomColorForLightText;
+ (id)topColorForLightText;
- (struct _NSSize)cellSize;
- (struct _NSRect)textRectForFrame:(struct _NSRect)fp8;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)setDrawsLightText:(BOOL)fp8;
- (BOOL)drawsLightText;

@end

