/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RolloverTrackingButton.h"

@interface RolloverTextButton : RolloverTrackingButton
{
}

+ (void)_updateCellClass;
+ (id)font;
- (id)description;
- (void)_setAttributes;
- (id)initWithFrame:(struct _NSRect)fp8;
- (id)init;
- (void)setTitle:(id)fp8;
- (BOOL)usesGradientText;
- (void)setUsesGradientText:(BOOL)fp8;
- (void)sizeToFit;

@end

