/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSButtonCell.h"

@interface RolloverTextButtonCell : NSButtonCell
{
    BOOL _usesGradientText;
}

- (BOOL)_shouldDrawBezel;
- (struct _NSRect)drawTitle:(id)fp8 withFrame:(struct _NSRect)fp12 inView:(id)fp28;
- (BOOL)usesGradientText;
- (void)setUsesGradientText:(BOOL)fp8;
- (BOOL)shouldDrawFocusRing;

@end

