/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BookmarkSource.h"

@class NSArray;

@interface RSSBookmarksController : BookmarkSource
{
    NSArray *_bookmarks;
}

+ (id)sharedController;
- (void)dealloc;
- (void)refreshContents;
- (BOOL)canDeleteContents;
- (id)child:(unsigned int)fp8 ofContentItem:(id)fp12;
- (unsigned int)numberOfChildrenOfContentItem:(id)fp8;
- (id)addressStringForContentItem:(id)fp8;
- (id)titleStringForContentItem:(id)fp8;
- (BOOL)menuHasKeyEquivalent:(id)fp8 forEvent:(id)fp12 target:(id *)fp16 action:(SEL *)fp20;
- (id)bookmarkSourceMenuTitle;
- (id)bookmarkSourceImage;
- (BOOL)isFilteredFromOtherSources;

@end

