/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PreferencesModule.h"

@class DefaultWebAppPopUpController, NSButton, NSPopUpButton;

@interface RSSPreferences : PreferencesModule
{
    NSButton *subscribeRSSBookmarksInMenuCheckbox;
    NSButton *subscribeRSSBookmarksInBarCheckbox;
    NSButton *colorizeUnreadArticlesCheckbox;
    NSPopUpButton *defaultRSSReaderPopUp;
    NSPopUpButton *updateIntervalPopUp;
    NSPopUpButton *removalIntervalPopUp;
    NSPopUpButton *unreadPolicyPopUp;
    DefaultWebAppPopUpController *_defaultRSSReaderController;
}

+ (void)defaultFeedHandlerChanged;
+ (BOOL)SafariIsNotDefaultFeedURLHandler;
- (id)preferencesNibName;
- (void)toggleRSSBookmarksInMenuAreSubscribed:(id)fp8;
- (void)toggleRSSBookmarksInBarAreSubscribed:(id)fp8;
- (void)toggleColorizeUnreadArticles:(id)fp8;
- (void)takeDefaultRSSReaderFrom:(id)fp8;
- (void)takeUpdateIntervalFrom:(id)fp8;
- (void)takeRemovalIntervalFrom:(id)fp8;
- (void)removeAllArticlesConfirmationDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)removeAllArticles:(id)fp8;
- (void)takeUnreadPolicyFrom:(id)fp8;
- (void)awakeFromNib;
- (void)updateColorViews;
- (void)updateViews;
- (void)initializeFromDefaults;
- (void)dealloc;
- (BOOL)isResizable;
- (id)helpAnchor;

@end

