/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSAlert.h"

@interface SafariAlert : NSAlert
{
    int _modalResult;
}

- (int)runSheetAppModalForWindow:(id)fp8;

@end

