/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSSearchField.h"

@class NSString;

@interface SearchField : NSSearchField
{
    NSString *_searchTextToolTip;
    NSString *_cancelToolTip;
    NSString *_recentSearchesToolTip;
    NSString *_snapBackToolTip;
    int _searchTextToolTipTag;
    int _cancelToolTipTag;
    int _recentSearchesToolTipTag;
    int _snapBackToolTipTag;
    BOOL _toolTipRectanglesUpToDate;
    BOOL _inTextDidEndEditing;
    BOOL _becomingFirstResponder;
}

+ (void)initialize;
- (id)initWithCoder:(id)fp8;
- (void)dealloc;
- (id)snapBackCell;
- (void)setIsShowingSnapBack:(BOOL)fp8;
- (BOOL)isShowingSnapBack;
- (BOOL)performKeyEquivalent:(id)fp8;
- (BOOL)becomeFirstResponder;
- (void)selectText:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (void)setSearchTextToolTip:(id)fp8;
- (id)searchTextToolTip;
- (void)setCancelToolTip:(id)fp8;
- (id)cancelToolTip;
- (void)setSnapBackToolTip:(id)fp8;
- (id)snapBackToolTip;
- (void)setRecentSearchesToolTip:(id)fp8;
- (id)recentSearchesToolTip;
- (void)removeAllToolTips;
- (void)setFrameOrigin:(struct _NSPoint)fp8;
- (void)setFrameSize:(struct _NSSize)fp8;
- (id)toolTip;
- (void)resetCursorRects;
- (id)view:(id)fp8 stringForToolTip:(int)fp12 point:(struct _NSPoint)fp16 userData:(void *)fp24;

@end

