/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebView.h"

@class FindBanner;

@interface SearchableWebView : WebView
{
    FindBanner *_findInPageBanner;
    BOOL _closed;
}

- (void)_close;
- (id)findInPageBanner;
- (BOOL)isShowingFindInPageBanner;
- (BOOL)canShowFindInPageBanner;
- (BOOL)canHideFindInPageBanner;
- (BOOL)currentPageIsSearchable;
- (void)dealloc;
- (id)initWithFrame:(struct _NSRect)fp8 frameName:(id)fp24 groupName:(id)fp28;
- (void)awakeFromNib;
- (void)viewDidMoveToWindow;
- (void)webView:(id)fp8 didDrawRect:(struct _NSRect)fp12;
- (void)webView:(id)fp8 didScrollDocumentInFrameView:(id)fp12;

@end

