/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SecurityPreferences.h"

@interface SecurityPreferences (FileInternal)
- (void)acceptCookiesPreferenceChanged:(id)fp8;
- (void)blockPopUpsConfirmationDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)populateDatabasesQuotaMenu;
- (void)toggleBooleanPreference:(id)fp8;
- (void)updateCookiesViews;
- (void)updateDatabaseViews;
- (void)updateJavaScriptViews;
- (void)antiPhishingServiceUpdated:(const struct SNotification *)fp8;
- (id)_approximateTimeStringForDuration:(double)fp8;
- (void)updateAntiPhishingStatusImage;
- (struct SafeBrowsingLastUpdateObserver *)_lastUpdateObserver;
- (void)_lastSuccessfulUpdateTimeForService:(id)fp8 lastUpdate:(double)fp12;
- (void)updateAntiPhishingViews;
- (void)showAntiPhishingStatus;
- (void)hideAntiPhishingStatus;
- (void)updateEverything;
- (void)updateMiscellaneousSecurityViews;
@end

