/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebDownload.h"

@class SecureDownloadProgressEntry;

@interface SecureDownload : WebDownload
{
    SecureDownloadProgressEntry *_entry;
}

- (id)initWithRequest:(id)fp8 delegate:(id)fp12 entry:(id)fp16;
- (id)initWithResumeInformation:(id)fp8 delegate:(id)fp12 path:(id)fp16 entry:(id)fp20;
- (void)connection:(id)fp8 didReceiveData:(id)fp12 lengthReceived:(long long)fp16;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)setEntry:(id)fp8;

@end

