/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PreferencesModule.h"

@class AcceptedCookies, AcceptedDatabases, AcceptedServices, NSButton, NSImageView, NSMatrix, NSPopUpButton, NSTextField, NSTimer;

@interface SecurityPreferences : PreferencesModule
{
    NSButton *javaScriptEnabledCheckbox;
    NSButton *blockPopUpsCheckbox;
    NSButton *javaEnabledCheckbox;
    NSButton *pluginsEnabledCheckbox;
    NSMatrix *cookiePolicyMatrix;
    NSButton *showCookiesButton;
    AcceptedCookies *cookiesEditor;
    NSPopUpButton *databaseQuotaPopUp;
    NSButton *showDatabasesButton;
    AcceptedDatabases *databasesEditor;
    NSButton *askBeforeSubmittingInsecureFormsCheckbox;
    NSTextField *antiPhishingLabel;
    NSButton *antiPhishingEnabled;
    NSButton *showServicesButton;
    NSTextField *antiPhishingStatusLabel;
    NSImageView *antiPhishingStatusImageView;
    AcceptedServices *servicesEditor;
    int cookiePolicy;
    BOOL m_showingAntiPhishingStatus;
    BOOL m_didUpdateAntiPhishingStatus;
    struct OwnPtr<SObjCNotifier> m_notifier;
    struct RefPtr<SafeBrowsingLastUpdateObserver> _lastUpdateObserver;
    NSTimer *_statusUpdateTimer;
}

- (void)awakeFromNib;
- (void)initializeFromDefaults;
- (BOOL)isResizable;
- (void)moduleWasInstalled;
- (void)moduleWillBeRemoved;
- (id)helpAnchor;
- (void)showCookies:(id)fp8;
- (void)showDatabases:(id)fp8;
- (void)takeCookiePolicyFrom:(id)fp8;
- (void)takeDatabaseSiteQuotaFrom:(id)fp8;
- (void)toggleAntiPhishingEnabled:(id)fp8;
- (void)showServices:(id)fp8;
- (void)toggleAskBeforeSubmittingInsecureForms:(id)fp8;
- (void)toggleJavaEnabled:(id)fp8;
- (void)toggleJavaScriptEnabled:(id)fp8;
- (void)toggleJavaScriptCanOpenWindows:(id)fp8;
- (void)togglePluginsEnabled:(id)fp8;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

