/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSURL;

@interface SecurityInfo : NSObject
{
    NSURL *url;
    int urlSecurityAssessment;
    BOOL hasWarnedUser;
    BOOL usesMultipleProviders;
}

- (void)dealloc;
- (id)description;
- (id)assessedURL;
- (void)setAssessedURL:(id)fp8;
- (int)urlSecurityAssessment;
- (void)setURLSecurityAssessment:(int)fp8;
- (BOOL)isKnownToBeUnsafe;
- (BOOL)hasWarnedUser;
- (void)setHasWarnedUser:(BOOL)fp8;
- (BOOL)usesMultipleProviders;
- (void)setUsesMultipleProviders:(BOOL)fp8;

@end

