/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DownloadProgressEntry.h"

@class NSArray, NSMutableData, NSURLConnection, NSURLRequest, NSURLResponse;

@interface SecureDownloadProgressEntry : DownloadProgressEntry
{
    struct OpaqueSecureDownload *_secureDownload;
    NSURLConnection *_ticketDownloadConnection;
    NSURLResponse *_ticketResponse;
    NSURLRequest *_ticketRequest;
    NSMutableData *_ticketData;
    NSArray *_downloadURLs;
    BOOL _ticketDownloaded;
}

- (id)initWithDictionary:(id)fp8;
- (id)initWithRequest:(id)fp8 mayOpenWhenDone:(BOOL)fp12 allowOverwrite:(BOOL)fp16;
- (void)dealloc;
- (id)dictionaryRepresentation;
- (id)filename;
- (id)createDownloadBundleWithFilename:(id)fp8;
- (void)resume;
- (void)_setDownload:(id)fp8;
- (id)_newWebDownloadResumedAtPath:(id)fp8;
- (id)_newWebDownload;
- (void)_fetchTicket;
- (id)_ticketPath;
- (long long)bytesExpected;
- (struct OpaqueSecureDownload *)secureDownload;
- (void)reportCorruptDownload;
- (void)reportInvalidTicket;
- (void)deleteDownload;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveAuthenticationChallenge:(id)fp12;
- (id)connection:(id)fp8 willCacheResponse:(id)fp12;

@end

