/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SheetRequest.h"

@class NSString;

@interface SimpleSheetRequest : SheetRequest
{
    NSString *_title;
    NSString *_message;
    NSString *_label;
    NSString *_helpAnchor;
}

+ (id)simpleSheetRequestWithTitle:(id)fp8 message:(id)fp12 label:(id)fp16 helpAnchor:(id)fp20;
- (void)dealloc;
- (id)initWithTitle:(id)fp8 message:(id)fp12 label:(id)fp16 helpAnchor:(id)fp20;
- (void)displaySheet;
- (id)title;
- (id)message;
- (id)label;

@end

