/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, WebSecurityOrigin;

@interface SiteDatabase : NSObject
{
    NSString *_identifier;
    NSString *_displayName;
    WebSecurityOrigin *_securityOrigin;
    unsigned int _size;
}

- (id)initWithIdentifier:(id)fp8;
- (void)dealloc;
- (void)setDisplayName:(id)fp8;
- (id)displayName;
- (id)identifier;
- (void)setSize:(unsigned int)fp8;
- (unsigned int)size;
- (void)setSecurityOrigin:(id)fp8;
- (id)securityOrigin;
- (int)compareByDisplayName:(id)fp8;

@end

