/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSView;

@interface SlidingView : NSObject
{
    NSView *view;
    struct _NSRect startFrame;
    struct _NSRect endFrame;
    double startTime;
    double duration;
}

- (id)initWithStartFrame:(struct _NSRect)fp8 endFrame:(struct _NSRect)fp24 duration:(double)fp40;
- (struct _NSRect)endFrame;
- (struct _NSRect)frameForTime:(double)fp8;

@end

