/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface SlidingAnimation : NSObject
{
    id _delegate;
    NSMutableDictionary *_views;
    BOOL _sliding;
    BOOL _paused;
}

- (id)init;
- (void)dealloc;
- (void)updateViewPosition:(id)fp8 forTime:(double)fp12;
- (void)updateTimer;
- (void)showNextFrame;
- (void)setDestinationForView:(id)fp8 to:(struct _NSRect)fp12 duration:(double)fp28;
- (void)sendViewToDestination:(id)fp8;
- (struct _NSRect)destinationForView:(id)fp8;
- (void)stopView:(id)fp8;
- (void)stop;
- (void)setDelegate:(id)fp8;
- (void)pause;
- (void)resume;

@end

