/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BarBackground.h"

@class ClippedItemsIndicator, NSMutableArray, SlidingAnimation;

@interface SlidingViewsBar : BarBackground
{
    unsigned int _dragSourceIndexIfMoving;
    unsigned int _dropIndex;
    float _draggedItemWidth;
    NSMutableArray *_buttons;
    ClippedItemsIndicator *_clipIndicator;
    SlidingAnimation *_animation;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (unsigned int)lastNonSlidingViewIndex;
- (float)maxButtonXWithoutClipIndicator;
- (float)maxButtonXWithClipIndicator;
- (float)maxButtonX;
- (float)minButtonX;
- (float)minSlidingViewX;
- (struct _NSRect)_constrainProposedButtonFrame:(struct _NSRect)fp8;
- (float)paddingBetweenButtons;
- (float)buttonBottomOffset;
- (void)reorderedSlidingView:(id)fp8;
- (void)draggedSlidingView:(id)fp8;
- (void)refreshButtons;
- (unsigned int)dropIndexFromDraggingInfo:(id)fp8;
- (unsigned int)dropIndexFromLocalPoint:(struct _NSPoint)fp8;
- (void)slideButtonsIntoPlace;
- (void)setDropIndex:(unsigned int)fp8;
- (id)_lastDraggedEventFollowing:(id)fp8;
- (id)_lastDraggedOrUpEventFollowing:(id)fp8;
- (void)reorderSlidingView:(id)fp8 fromMouseDownEvent:(id)fp12;
- (void)pauseAnimation;
- (void)resumeAnimation;
- (float)widthOfDraggingInfo:(id)fp8;
- (float)slidingWidthForView:(id)fp8;
- (unsigned int)updateDropTarget:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (void)draggingExited:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingEnded:(id)fp8;
- (void)moveSlidingViewToCurrentDropIndex:(id)fp8;

@end

