/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSImage;

@interface SlidingImageView : NSView
{
    NSImage *_stableImage;
    NSImage *_movingImage;
    NSImage *_shadow;
    BOOL _slidesUpwards;
    float _slideAmount;
    struct _NSSize _shadowSize;
}

- (void)dealloc;
- (struct _NSRect)movingImageTargetRectIncludingShadowRect:(BOOL)fp8;
- (struct _NSRect)stableImageTargetRect;
- (struct _NSRect)shadowRect;
- (void)drawRect:(struct _NSRect)fp8;
- (id)stableImage;
- (void)setStableImage:(id)fp8;
- (id)movingImage;
- (void)createShadow;
- (void)setMovingImage:(id)fp8;
- (BOOL)slidesUpwards;
- (void)setSlidesUpwards:(BOOL)fp8;
- (float)slideAmount;
- (void)setSlideAmount:(float)fp8;
- (BOOL)isOpaque;

@end

