/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSMutableArray;

@interface SpinningProgressIndicator : NSView
{
    BOOL _delayedStartup;
    BOOL _isSpinning;
    BOOL _backgroundNeedsUpdate;
    BOOL _isPaused;
    unsigned int _lastImageIndex;
    id _delegate;
    NSMutableArray *_images;
}

+ (void)stopSpinningAll;
+ (void)setUpWindowPosing;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)_addWindowFlushObserver;
- (void)_removeWindowFlushObserver;
- (void)dealloc;
- (void)_startSpinning;
- (void)_stopSpinning;
- (void)setFrameOrigin:(struct _NSPoint)fp8;
- (void)windowDidFlush;
- (BOOL)_recompositeImages;
- (void)drawImageAtIndex:(unsigned int)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)startSpinning;
- (void)stopSpinning;
- (BOOL)isSpinning;
- (BOOL)isDisplaying;
- (void)pauseSpinning;
- (void)resumeSpinning;
- (void)setDelegate:(id)fp8;
- (void)backgroundImageNeedsUpdate;
- (BOOL)heartbeatWithBirthDate:(double)fp8 currentDate:(double)fp16 context:(id)fp24;

@end

