/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface SpotlightDataTypeHandler : NSObject
{
    NSString *_type;
    id <SpotlightDataSource> _dataSource;
    id <SpotlightDataWriter> _dataWriter;
    NSArray *_itemsToDelete;
    NSArray *_itemsToAdd;
    BOOL _fullUpdatePending;
    BOOL _deleteOldCacheFiles;
}

- (id)initWithDataSource:(id)fp8 writer:(id)fp12 type:(id)fp16;
- (id)dataSource;
- (id)dataWriter;
- (id)type;
- (id)itemsToAdd;
- (void)setItemsToAdd:(id)fp8;
- (id)itemsToDelete;
- (void)setItemsToDelete:(id)fp8;
- (BOOL)isFullUpdatePending;
- (void)setFullUpdatePending:(BOOL)fp8;
- (BOOL)shouldDeleteOldCacheFiles;
- (void)setShouldDeleteOldCacheFiles:(BOOL)fp8;
- (void)dealloc;

@end

