/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SpotlightBookmarksWriter.h"

@interface SpotlightBookmarksWriter (FileInternal)
- (void)_writeCacheFileForBookmark:(id)fp8 inDirectory:(id)fp12;
- (void)_removeCacheFileForBookmark:(id)fp8 inDirectory:(id)fp12;
@end

