/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SpotlightHistoryWriter.h"

@interface SpotlightHistoryWriter (FileInternal)
- (void)_deleteCacheFileForItem:(id)fp8;
- (id)_filenameForItem:(id)fp8;
- (void)_forgetTrackedFilenameForItem:(id)fp8;
- (id)_generateTrackedFilenameForItem:(id)fp8;
- (id)_pathForFilename:(id)fp8;
- (id)_pathForItem:(id)fp8;
- (id)_pathForMappingFile;
- (void)_setCacheFilesDirectory:(id)fp8;
- (id)_trackedFilenameForItem:(id)fp8;
- (id)_trackedFilenames;
- (void)_updateMappingFile;
- (void)_writeCacheFileForItem:(id)fp8;
@end

