/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface SpotlightCacheController : NSObject
{
    BOOL _updateInProgress;
    BOOL _needsUpdate;
    BOOL _kickingOffUpdaterThread;
    BOOL _updateImmediately;
    NSMutableDictionary *_handlers;
    NSMutableDictionary *_fileExtensions;
}

+ (id)sharedController;
- (BOOL)fileIsSpotlightCacheFile:(id)fp8;
- (void)fullUpdateNeededForType:(id)fp8;
- (void)fullUpdateNeededForType:(id)fp8 immediately:(BOOL)fp12;
- (void)partialUpdateNeededForType:(id)fp8;
- (void)partialUpdateNeededForType:(id)fp8 immediately:(BOOL)fp12;
- (void)registerSpotlightDataSource:(id)fp8 andWriter:(id)fp12 forType:(id)fp16;
- (void)setSafariIsBusy:(BOOL)fp8;
- (id)URLToVisitFromSpotlightCacheFile:(id)fp8;
- (void)dealloc;

@end

