/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "SpotlightDataWriter-Protocol.h"

@interface SpotlightBookmarksWriter : NSObject <SpotlightDataWriter>
{
}

- (void)deleteSpotlightCacheFilesForItems:(id)fp8 ofDataType:(id)fp12 inDirectory:(id)fp16;
- (void)addSpotlightCacheFilesForItems:(id)fp8 ofDataType:(id)fp12 inDirectory:(id)fp16;
- (id)fileExtensionForDataType:(id)fp8;
- (id)URLToVisitFromSpotlightCacheFile:(id)fp8 ofDataType:(id)fp12;

@end

