/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface Stopwatch : NSObject
{
    double startTime;
    double finishTime;
}

- (void)start;
- (void)finish;
- (double)runTime;

@end

