/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "SynBookmark-Protocol.h"

@class NSMutableArray;

@interface SynBookmarksTemporaryList : NSObject <SynBookmark>
{
    NSMutableArray *_children;
}

- (id)init;
- (void)dealloc;
- (id)title;
- (id)URLString;
- (id)UUID;
- (id)children;
- (void)addBookmark:(id)fp8;

@end

