/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class SafariSyndication;

@interface SyndicationController : NSObject
{
    BOOL _syndicationEnabled;
    BOOL _articleUpdatesEnabled;
    SafariSyndication *_safariSyndication;
}

+ (id)sharedController;
- (id)safariSyndication;
- (void)initializeSyndication;
- (BOOL)articleUpdatesAreEnabled;
- (void)setArticleUpdatesEnabled:(BOOL)fp8;
- (BOOL)anyLocationsAreSubscribed;
- (void)adjustSubscribedLocationsToReflectUpdateInterval;
- (void)adjustUpdateIntervalToReflectSubscribedLocations;
- (void)setArticleRemovalInterval:(int)fp8;
- (int)articleRemovalInterval;
- (void)setArticleUpdateInterval:(int)fp8;
- (int)articleUpdateInterval;
- (void)removeArticles;
- (BOOL)clickToMarkArticlesRead;
- (void)setClickToMarkArticlesRead:(BOOL)fp8;
- (BOOL)colorUnreadArticles;
- (void)setColorUnreadArticles:(BOOL)fp8;
- (void)setUnreadArticleTitleHighlightColor:(id)fp8;
- (id)unreadArticleTitleHighlightColor;
- (id)feedURLFromArticleFile:(id)fp8;
- (id)feedsInURL:(id)fp8;
- (id)feedURLFromURL:(id)fp8;
- (id)feedURLFromDOM:(id)fp8 baseURL:(id)fp12;
- (id)feedLinksOrURLsFromDOM:(id)fp8 baseURL:(id)fp12;
- (id)feedURLFromWebBookmark:(id)fp8;
- (id)homePageOfFeed:(id)fp8;
- (void)sendAllUnreadCounts;
- (void)setDelegate:(id)fp8;
- (void)setSafariIsBusy:(BOOL)fp8;
- (id)unfilteredSyndicationURL:(id)fp8;
- (void)updateBookmarks:(id)fp8 andSubscriptions:(id)fp12;
- (BOOL)syndicationIsEnabled;
- (void)setSyndicationEnabled:(BOOL)fp8;

@end

