/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SlidingViewsBar.h"

#import "MorphingDragImageDropTarget-Protocol.h"

@class BrowserWindowController, NSImage, NSLock, NSTabView, TabButton;

@interface TabBarView : SlidingViewsBar <MorphingDragImageDropTarget>
{
    BrowserWindowController *browserWindowController;
    NSTabView *tabView;
    NSImage *_windowBackgroundImage;
    NSLock *_windowBackgroundImageLock;
    BOOL _areCloseButtonsVisible;
    BOOL _suspendButtonRemoval;
    TabButton *_tabSelectedBeforeTabDrag;
}

+ (id)darkTintColor;
- (id)firstTopBorderLineColor;
- (id)secondTopBorderLineColor;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)setFrameSize:(struct _NSSize)fp8;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)viewDidMoveToWindow;
- (BOOL)mouseDownCanMoveWindow;
- (void)mouseDown:(id)fp8;
- (id)menuForEvent:(id)fp8;
- (float)maxButtonXWithoutClipIndicator;
- (float)maxButtonXWithClipIndicator;
- (float)minSlidingViewX;
- (float)maxSlidingViewX;
- (float)minButtonX;
- (void)reorderSlidingView:(id)fp8 fromMouseDownEvent:(id)fp12;
- (void)reorderedSlidingView:(id)fp8;
- (void)draggedSlidingView:(id)fp8;
- (void)refreshButtons;
- (unsigned int)updateDropTarget:(id)fp8;
- (float)widthOfDraggingInfo:(id)fp8;
- (float)slidingWidthForView:(id)fp8;
- (void)replaceTabView:(id)fp8;
- (id)windowBackgroundImage;
- (void)performDragOperationForTabViewItem:(id)fp8 draggingInfo:(id)fp12;
- (unsigned int)indexOfTabViewItem:(id)fp8;
- (id)selectedTabViewItem;
- (void)selectTabViewItem:(id)fp8;
- (void)detachTab:(id)fp8 event:(id)fp12 withOldSelectedTab:(id)fp16;
- (void)detachTabAndPositionUnderCursor:(id)fp8 sourceView:(id)fp12;
- (void)browserTabViewItemLabelChanged:(id)fp8;
- (struct _NSSize)dragImageSizeForTab:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (void)animation:(id)fp8 didSlideView:(id)fp12;
- (void)tabView:(id)fp8 willSelectTabViewItem:(id)fp12;
- (void)tabView:(id)fp8 didSelectTabViewItem:(id)fp12;
- (void)tabViewDidChangeNumberOfTabViewItems:(id)fp8;
- (id)menuItemsForClippedItemsIndicator:(id)fp8;
- (unsigned int)morphingDragImage:(id)fp8 draggingEntered:(id)fp12;
- (unsigned int)morphingDragImage:(id)fp8 draggingUpdated:(id)fp12;
- (void)morphingDragImage:(id)fp8 draggingExited:(id)fp12;
- (BOOL)morphingDragImage:(id)fp8 performDragOperation:(id)fp12;

@end

