/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RolloverTrackingButton.h"

@class BrowserTabViewItem, NSImage, NSImageView, NSString, NSWindow, RolloverImageButton, SpinningProgressIndicator;

@interface TabButton : RolloverTrackingButton
{
    BrowserTabViewItem *_tabViewItem;
    RolloverImageButton *_closeButton;
    SEL _closeAction;
    SpinningProgressIndicator *_progressIndicator;
    NSImageView *_errorIndicator;
    int _leftSeparatorMode;
    int _rightSeparatorMode;
    struct _NSRect _stackingFrame;
    NSImage *_backgroundImage;
    BOOL _initializedFontsAndImages;
    BOOL _drawsDetached;
    BOOL _windowBackgroundMightBeStale;
    NSString *_toolTip;
    int _toolTipTag;
    NSImage *_tabDragImage;
    NSImage *_miniWindowDragImage;
    struct _NSRect _miniWindowStartFrame;
    struct _NSRect _miniWindowEndFrame;
    NSWindow *_miniWindowDragWindow;
    NSWindow *_miniWindowBrowserWindow;
    struct CGAffineTransform _originalBrowserTransform;
}

+ (void)initialize;
+ (void)_loadImages;
+ (BOOL)isTabDrag:(id)fp8;
+ (BOOL)isMiniWindowDrag:(id)fp8;
+ (float)squishFactorForMiniWindowDragImage;
+ (id)lightSeparatorLineColor;
+ (id)darkSeparatorLineColor;
+ (id)rolloverColor;
+ (id)bottomColorForFrontTabText;
+ (id)topColorForFrontTabText;
+ (id)bottomColorForBackTabText;
+ (id)topColorForBackTabText;
- (void)_setCloseButtonImages;
- (id)closeButton;
- (void)_initializeFontsAndImages;
- (id)initWithFrame:(struct _NSRect)fp8 tabViewItem:(id)fp24;
- (void)dealloc;
- (id)_tabBarView;
- (void)_drawSeparatorAtXOrigin:(float)fp8 inRect:(struct _NSRect)fp12 dark:(BOOL)fp28;
- (void)_drawSeparatorsInRect:(struct _NSRect)fp8;
- (void)_drawRolloverColorInRect:(struct _NSRect)fp8;
- (void)_drawWindowBackgroundFromFrame:(struct _NSRect)fp8 operation:(unsigned int)fp24;
- (id)_backgroundImage;
- (void)windowBackgroundDidChange;
- (id)backgroundImageForProgressIndicator:(id)fp8;
- (float)_leftTextMargin;
- (struct _NSRect)_textRect;
- (float)quiescentTextWidth;
- (void)setDrawsDetached:(BOOL)fp8;
- (id)tabDragImage;
- (id)miniWindowDragImage;
- (void)drawRect:(struct _NSRect)fp8;
- (void)viewDidMoveToWindow;
- (void)setStackingFrame:(struct _NSRect)fp8;
- (struct _NSRect)stackingFrame;
- (struct _NSRect)slidingFrame;
- (void)setSlidingFrame:(struct _NSRect)fp8;
- (void)setState:(int)fp8;
- (void)setLeftSeparatorMode:(int)fp8;
- (void)setRightSeparatorMode:(int)fp8;
- (void)setCloseAction:(SEL)fp8;
- (id)tabViewItem;
- (void)closeTab:(id)fp8;
- (unsigned int)lastMouseDownModifierFlagsForCloseButton;
- (id)menuForEvent:(id)fp8;
- (void)mouseDown:(id)fp8;
- (BOOL)mouseDownCanMoveWindow;
- (void)mouseEnteredOrExited:(BOOL)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (void)morphingDragImage:(id)fp8 movedToPointOnScreen:(struct _NSPoint)fp12;
- (void)morphingDragImage:(id)fp8 wasDroppedAtPointOnScreen:(struct _NSPoint)fp12;
- (void)morphingDragImageEnded:(id)fp8;
- (void)_setNeedsDisplayAfterProgressChange:(float)fp8;
- (void)_startProgressAnimation;
- (void)_stopProgressAnimation;
- (void)_setShowingProgressIndicator:(BOOL)fp8 immediately:(BOOL)fp12;
- (void)setShowingProgressIndicator:(BOOL)fp8;
- (BOOL)isShowingProgressIndicator;
- (void)pauseProgressIndication;
- (void)resumeProgressIndication;
- (void)showSheetRequestIcon:(id)fp8;
- (id)sheetRequestIcon;
- (id)hitTest:(struct _NSPoint)fp8;
- (void)destroy;
- (void)setToolTip:(id)fp8;
- (void)resetCursorRects;

@end

