/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TabButton.h"

@interface TabButton (Internal)
+ (id)_imageForEmptyWindowOfSize:(struct _NSSize)fp8;
+ (id)_toolTipTextAttributes;
- (void)_backgroundImageNeedsUpdate;
- (id)_dragImageForImage:(id)fp8;
- (void)_growMiniWindowForDetachedTabWithDragController:(id)fp8;
- (void)_growMiniWindow:(id)fp8;
- (void)_updateToolTip;
- (void)_updateFrames;
@end

