/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTableView.h"

@interface TableViewPlus : NSTableView
{
    BOOL _startEditTimerOnMouseUp;
    BOOL _highlightsWithITunesStyleGradient;
    int _clickedRow;
    int _clickedColumn;
}

- (void)keyDown:(id)fp8;
- (BOOL)shouldEditOnDoubleClick:(id)fp8 inRow:(int)fp12 tableColumn:(id)fp16;
- (BOOL)shouldEditOnSingleClick:(id)fp8 inRow:(int)fp12 tableColumn:(id)fp16;
- (BOOL)_userCanEditTableColumn:(id)fp8 row:(int)fp12;
- (void)_editClickedCell:(id)fp8;
- (void)_cancelEditOnMouseUp;
- (id)dragImageForRowsWithIndexes:(id)fp8 tableColumns:(id)fp12 event:(id)fp16 offset:(struct _NSPoint *)fp20;
- (int)_rowFromEvent:(id)fp8;
- (int)_columnFromEvent:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)sizeToFit;
- (id)menuForEvent:(id)fp8;
- (unsigned int)draggingSourceOperationMaskForLocal:(BOOL)fp8;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
- (BOOL)highlightsWithITunesStyleGradient;
- (void)setHighlightsWithITunesStyleGradient:(BOOL)fp8;
- (void)drawRect:(struct _NSRect)fp8;

@end

