/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class BrowserDocument, BrowserWebView;

@interface TabLocation : NSObject
{
    BrowserWebView *_webView;
    BrowserDocument *_document;
}

+ (id)tabLocationWithBrowserDocument:(id)fp8 browserWebView:(id)fp12;
- (id)initWithBrowserDocument:(id)fp8 browserWebView:(id)fp12;
- (void)dealloc;
- (id)browserDocument;
- (id)browserWebView;

@end

