/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTableHeaderView.h"

@class NSDictionary;

@interface TableHeaderView : NSTableHeaderView
{
    NSDictionary *_referenceColumnWidths;
    BOOL _noSeparatorLines;
}

+ (id)updateHeaderViewForTableView:(id)fp8;
- (void)dealloc;
- (void)setReferenceColumnWidths:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)resetReferenceColumnWidths;
- (id)referenceColumnWidths;
- (BOOL)drawsSeparatorLines;
- (void)setDrawsSeparatorLines:(BOOL)fp8;
- (BOOL)_drawingEndSeparator;

@end

