/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextView.h"

@interface TextFieldEditor : NSTextView
{
    BOOL _pasteReplacesLineEndingsWithSpaces;
}

- (id)init;
- (BOOL)pasteReplacesLineEndingsWithSpaces;
- (void)setPasteReplacesLineEndingsWithSpaces:(BOOL)fp8;
- (void)replaceCarriageReturnsAfterPaste;
- (void)paste:(id)fp8;

@end

