/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextField.h"

@class NSImage, NSString;

@interface TextFieldWithControls : NSTextField
{
    NSImage *_leftCapImage;
    NSImage *_rightCapImage;
    NSImage *_middleImage;
    NSImage *_leftProgressImage;
    NSImage *_rightProgressImage;
    NSImage *_middleProgressImage;
    NSImage *_leftButtonImage;
    NSImage *_rightButtonImage;
    NSImage *_rightButtonHighlightedImage;
    NSImage *_rightButton2Image;
    NSImage *_rightButton2HighlightedImage;
    NSImage *_backgroundImage;
    BOOL _showLeftButton;
    BOOL _showRightButton;
    BOOL _showRightButton2;
    BOOL _rightButtonIsHighlighted;
    BOOL _rightButton2IsHighlighted;
    BOOL _shouldRedrawBackgroundImage;
    BOOL _usesProgressBar;
    BOOL _canShowProgressBarNow;
    BOOL _inTextDidEndEditing;
    BOOL _becomingFirstResponder;
    struct _NSSize _leftCapSize;
    struct _NSSize _rightCapSize;
    struct _NSSize _middleSize;
    struct _NSRect _leftButtonFrame;
    struct _NSSize _rightButtonSize;
    struct _NSSize _rightButton2Size;
    float _rightButtonYOffset;
    float _rightButton2YOffset;
    float _rightButtonLeftMargin;
    float _rightButton2LeftMargin;
    float _rightButtonRightMargin;
    float _rightButton2RightMargin;
    float _rightButtonSqueeze;
    struct _NSRect _rightButtonFrame;
    struct _NSRect _rightButton2Frame;
    NSString *_leftButtonToolTip;
    NSString *_middleToolTip;
    NSString *_rightButtonToolTip;
    NSString *_rightButton2ToolTip;
    int _leftButtonToolTipTag;
    int _middleToolTipTag;
    int _rightButtonToolTipTag;
    int _rightButton2ToolTipTag;
    BOOL _toolTipRectanglesUpToDate;
    NSString *_leftButtonDescription;
    NSString *_rightButtonDescription;
    NSString *_rightButton2Description;
    BOOL _leftButtonIsAccessible;
    BOOL _rightButtonIsAccessible;
    BOOL _rightButton2IsAccessible;
    double _progressValue;
    BOOL _usePieProgressIndicator;
}

- (void)finishInitialization;
- (void)selectText:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct _NSRect)fp8;
- (id)initWithCoder:(id)fp8;
- (float)leftSideMaxX;
- (void)removeAllToolTips;
- (float)rightButtonsWidth;
- (void)updateToolTips;
- (float)widthWithoutCaps;
- (float)progressBarWidthWithoutCaps;
- (float)progressBarMaxX;
- (id)backgroundImage;
- (void)setBackgroundImageNeedsRedraw;
- (void)setFrameOrigin:(struct _NSPoint)fp8;
- (void)setFrameSize:(struct _NSSize)fp8;
- (BOOL)isDirtyOutsideOfRect:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (struct _NSRect)leftButtonHitTestFrame;
- (struct _NSRect)rightButtonHitTestFrame;
- (struct _NSRect)rightButton2HitTestFrame;
- (struct _NSRect)rightButtonImageFrame;
- (struct _NSRect)rightButton2ImageFrame;
- (void)setRightButtonIsHighlightedAndFlush:(BOOL)fp8 firstButton:(BOOL)fp12;
- (void)mouseDownInRightButton:(id)fp8 firstButton:(BOOL)fp12;
- (void)mouseDown:(id)fp8;
- (id)accessibilityHelpStringForLeftButton;
- (id)accessibilityHelpStringForRightButton;
- (id)accessibilityHelpStringForRightButton2;
- (id)accessibilityDescriptionForLeftButton;
- (void)setAccessibilityDescriptionForLeftButton:(id)fp8;
- (id)accessibilityDescriptionForRightButton;
- (void)setAccessibilityDescriptionForRightButton:(id)fp8;
- (id)accessibilityDescriptionForRightButton2;
- (void)setAccessibilityDescriptionForRightButton2:(id)fp8;
- (BOOL)leftButtonIsAccessible;
- (void)setLeftButtonIsAccessible:(BOOL)fp8;
- (BOOL)rightButtonIsAccessible;
- (void)setRightButtonIsAccessible:(BOOL)fp8;
- (BOOL)rightButton2IsAccessible;
- (void)setRightButton2IsAccessible:(BOOL)fp8;
- (void)trackMenuInRightButton2:(id)fp8;
- (void)performLeftButtonAction;
- (void)performRightButtonAction;
- (void)performRightButton2Action;
- (BOOL)performKeyEquivalent:(id)fp8;
- (void)resetCursorRects;
- (BOOL)isShowingRightButton;
- (BOOL)isShowingRightButton2;
- (void)setIsShowingRightButton:(BOOL)fp8 firstButton:(BOOL)fp12;
- (void)setIsShowingRightButton:(BOOL)fp8;
- (void)setIsShowingRightButton2:(BOOL)fp8;
- (void)setKeyboardFocusRingNeedsDisplayInRect:(struct _NSRect)fp8;
- (void)setLeftButtonToolTip:(id)fp8;
- (void)setToolTip:(id)fp8;
- (id)toolTip;
- (void)setRightButtonToolTip:(id)fp8;
- (void)setRightButton2ToolTip:(id)fp8;
- (id)view:(id)fp8 stringForToolTip:(int)fp12 point:(struct _NSPoint)fp16 userData:(void *)fp24;
- (void)setLeftCapImage:(id)fp8;
- (void)setRightCapImage:(id)fp8;
- (void)setMiddleImage:(id)fp8;
- (void)setLeftProgressImage:(id)fp8;
- (void)setRightProgressImage:(id)fp8;
- (void)setMiddleProgressImage:(id)fp8;
- (void)setLeftButtonImage:(id)fp8 withOrigin:(struct _NSPoint)fp12;
- (void)setRightButtonImage:(id)fp8 withVerticalOffset:(float)fp12 leftMargin:(float)fp16 rightMargin:(float)fp20 rightSqueeze:(float)fp24;
- (void)setRightButtonHighlightedImage:(id)fp8;
- (void)setRightButton2Image:(id)fp8 withVerticalOffset:(float)fp12 leftMargin:(float)fp16 rightMargin:(float)fp20;
- (void)setRightButton2HighlightedImage:(id)fp8;
- (id)leftButtonImage;
- (id)rightButtonImage;
- (id)rightButtonHighlightedImage;
- (id)rightButton2Image;
- (id)rightButton2HighlightedImage;
- (BOOL)isShowingProgressBar;
- (BOOL)usesProgressBar;
- (void)setCanShowProgressBarNow:(BOOL)fp8;
- (void)setUsesProgressBar:(BOOL)fp8;
- (void)setUsesPieProgressIndicator:(BOOL)fp8;
- (double)progressBarValue;
- (void)setProgressBarValue:(double)fp8;
- (BOOL)isOpaque;
- (void)startSpinningToString:(id)fp8 upwards:(BOOL)fp12;
- (void)finishSpinning;
- (void)setSpinAmount:(float)fp8;
- (float)spinAmount;
- (BOOL)acceptsFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)setEditable:(BOOL)fp8;

@end

