/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSString;

@interface TextFieldWithControlsCell : NSTextFieldCell
{
    BOOL _showRightButton;
    BOOL _showRightButton2;
    float _borderTop;
    float _borderBottom;
    float _borderLeft;
    float _borderRight;
    float _leftButtonMaxX;
    float _rightButtonReservedWidth;
    float _rightButtonSqueeze;
    float _rightButton2ReservedWidth;
    float _spinAmount;
    BOOL _spinUpwards;
    NSString *_spinSourceString;
    NSString *_accessibilityDescription;
}

- (id)init;
- (void)dealloc;
- (struct _NSRect)textRectForFrame:(struct _NSRect)fp8;
- (struct _NSRect)_focusRingFrameForFrame:(struct _NSRect)fp8 cellFrame:(struct _NSRect)fp24;
- (void)selectWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 start:(int)fp36 length:(int)fp40;
- (void)editWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 event:(id)fp36;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (float)borderTop;
- (float)borderBottom;
- (float)borderLeft;
- (float)borderRight;
- (void)showRightButton:(BOOL)fp8;
- (void)showRightButton2:(BOOL)fp8;
- (void)setBorderTop:(float)fp8;
- (void)setBorderBottom:(float)fp8;
- (void)setBorderLeft:(float)fp8;
- (void)setBorderRight:(float)fp8;
- (void)setLeftButtonMaxX:(float)fp8;
- (void)setRightButtonReservedWidth:(float)fp8;
- (void)setRightButtonSqueeze:(float)fp8;
- (void)setRightButton2ReservedWidth:(float)fp8;
- (BOOL)isOpaque;
- (void)startSpinningToString:(id)fp8 upwards:(BOOL)fp12;
- (void)finishSpinning;
- (float)spinAmount;
- (void)setSpinAmount:(float)fp8;
- (BOOL)isSpinning;
- (id)accessibilityAttributeNames;
- (id)accessibilityDescription;
- (void)setAccessibilityDescription:(id)fp8;
- (id)textFieldWithControlsView;
- (id)accessibilityHelpStringForRightButton;
- (id)accessibilityHelpStringForRightButton2;
- (id)accessibilityHelpStringForLeftButton;
- (id)accessibilityDescriptionForRightButton;
- (id)accessibilityDescriptionForRightButton2;
- (id)accessibilityDescriptionForLeftButton;
- (BOOL)rightButtonIsAccessible;
- (BOOL)rightButton2IsAccessible;
- (BOOL)leftButtonIsAccessible;
- (void)performRightButton2Action;
- (void)performRightButtonAction;
- (void)performLeftButtonAction;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (id)accessibilityHitTest:(struct _NSPoint)fp8;
- (id)accessibilityHelpStringForChildInfo:(id)fp8;
- (struct _NSRect)accessibilityScreenRectForChild:(id)fp8;
- (id)accessibilityDescriptionForButtonInfo:(id)fp8;
- (BOOL)accessibilityButtonInfoIsEnabled:(id)fp8;
- (void)accessibilityPerformActionForButtonInfo:(id)fp8;

@end

