/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSString, NSTextFieldCell;

@interface TitleBarButton : NSView
{
    NSString *_title;
    NSTextFieldCell *_titleCell;
    BOOL _noDragRectComputed;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (struct _NSRect)titleRect;
- (struct _NSRect)titleRectInWindow;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isFlipped;
- (void)doNothing:(id)fp8;
- (void)goToMenuItemURL:(id)fp8;
- (void)showPathPopUpMenu;
- (BOOL)shouldShowPathPopUpMenuFromMouseDown:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)rightMouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (id)title;
- (void)flagsChanged:(id)fp8;
- (void)resetNoDragRect;
- (void)updateFrame;
- (void)updateFrameUsingAvailableSpace:(float)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)setFrame:(struct _NSRect)fp8 ignoringInternalGeometry:(BOOL)fp24;
- (void)viewDidEndLiveResize;
- (void)windowDidEndSheet:(id)fp8;
- (void)windowDidDeminiaturize:(id)fp8;
- (void)setTitle:(id)fp8;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)fp8;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (id)accessibilityActionNames;
- (id)accessibilityActionDescription:(id)fp8;
- (void)accessibilityPerformAction:(id)fp8;

@end

