/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class BrowserToolbarItem, BrowserWindowController, LocationTextField, NSButton, NSSegmentedControl, NSWindow, SearchField, SplitView;

@interface ToolbarController : NSObject
{
    BrowserWindowController *_browserWindowController;
    NSWindow *nibWindow;
    NSSegmentedControl *backForwardSegmentedControl;
    NSSegmentedControl *backForwardCustomizeSegmentedControl;
    NSSegmentedControl *textSizeSegmentedControl;
    NSSegmentedControl *textSizeCustomizeSegmentedControl;
    NSButton *stopOrReloadButton;
    NSButton *openInDashboardButton;
    NSButton *addBookmarkButton;
    NSButton *autoFillButton;
    NSButton *homeButton;
    SplitView *inputFieldsView;
    LocationTextField *locationField;
    SearchField *searchField;
    NSButton *reportBugButton;
    NSButton *printButton;
    NSButton *stopOrReloadCustomizeButton;
    SplitView *inputFieldsCustomizeView;
    BrowserToolbarItem *_backForwardItem;
    BrowserToolbarItem *_stopOrReloadItem;
    BrowserToolbarItem *_openInDashboardItem;
    BrowserToolbarItem *_addBookmarkItem;
    BrowserToolbarItem *_autoFillItem;
    BrowserToolbarItem *_homeItem;
    BrowserToolbarItem *_inputFieldsItem;
    BrowserToolbarItem *_textSizeItem;
    BrowserToolbarItem *_reportBugItem;
    BrowserToolbarItem *_printItem;
    BrowserToolbarItem *_backForwardCustomizeItem;
    BrowserToolbarItem *_stopOrReloadCustomizeItem;
    BrowserToolbarItem *_inputFieldsCustomizeItem;
    BrowserToolbarItem *_textSizeCustomizeItem;
    float _inputFieldsWidthRatio;
}

- (void)layOutInputFields;
- (void)updateToolbarSettings;
- (void)appendItemWithIdentifier:(id)fp8;
- (void)appendItemWithIdentifier:(id)fp8 accordingToDefault:(id)fp12;
- (void)convertOldDefaults;
- (void)insertOpenInDashboardItem;
- (void)insertMandatoryItems;
- (void)prepareBackForwardSegmentedControl:(id)fp8;
- (void)prepareTextSizeSegmentedControl:(id)fp8;
- (id)initWithBrowserWindowController:(id)fp8;
- (void)dealloc;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
- (id)backForwardSegmentedControl;
- (id)stopOrReloadButton;
- (id)locationField;
- (id)searchField;
- (BOOL)shouldShowGoogleSearch;
- (void)setShouldShowGoogleSearch:(BOOL)fp8;
- (BOOL)canShowInputFields;
- (BOOL)isBackForwardVisible;
- (void)_parentalControlsDidChange;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (float)splitView:(id)fp8 constrainMinCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (void)splitView:(id)fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (void)splitViewDidEndLiveResize:(id)fp8;

@end

