/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class WebBookmark;

@interface UndoRemoveInfo : NSObject
{
    WebBookmark *_bookmark;
    WebBookmark *_parent;
    int _index;
}

+ (id)infoWithBookmark:(id)fp8;
- (id)initWithBookmark:(id)fp8;
- (void)dealloc;

@end

