/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface URLCompletionItem : NSObject
{
    id _item;
    int _index;
    int _weight;
    int _urlType;
}

- (void)computeWeight:(double)fp8;
- (id)urlItem;
- (int)urlType;
- (int)weight;
- (int)index;
- (int)compare:(id)fp8;
- (id)initWithItem:(id)fp8 andIndex:(int)fp12 andTime:(double)fp16;
- (void)dealloc;

@end

