/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CompletionControllerForNSTextField.h"

@interface URLCompletionController : CompletionControllerForNSTextField
{
    int style;
}

+ (void)_tree_create;
+ (void)_tree_destroy;
+ (void)_tree_addItem:(id)fp8;
+ (void)_tree_deleteItem:(id)fp8;
+ (void)_tree_setCursorAtStart:(struct _TreeCursor *)fp8;
+ (id)_tree_findItem:(id)fp8 cursor:(struct _TreeCursor *)fp12;
+ (id)_tree_nextItemUsingCursor:(struct _TreeCursor *)fp8;
+ (void)_addBookmarkTree:(id)fp8;
+ (void)_removeBookmarkTree:(id)fp8;
+ (void)_loadDB;
+ (void)_registerForNotifications;
+ (void)_historyAdded:(id)fp8;
+ (void)_historyRemoved:(id)fp8;
+ (void)_reloadDB:(id)fp8;
+ (void)_bookmarksAdded:(id)fp8;
+ (void)_bookmarksRemoved:(id)fp8;
+ (void)_bookmarkWillChange:(id)fp8;
+ (void)_bookmarkDidChange:(id)fp8;
- (id)_queryStringForAbsoluteURL:(id)fp8 fullScan:(char *)fp12;
- (id)_queryStringForString:(id)fp8 fullScan:(char *)fp12;
- (id)queryResultsForString:(id)fp8 startingMatch:(unsigned int *)fp12;
- (id)queryStringFromPartialString:(id)fp8;
- (id)intermediateMatchingStringForResult:(id)fp8;
- (id)finalMatchingStringForResult:(id)fp8;

@end

