/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTimer;

@interface Watchdog : NSObject
{
    BOOL shouldStop;
    double watchdogInterval;
    NSTimer *watchdogTimer;
}

- (id)init;
- (id)sampleOutput;
- (void)handleHang;
- (void)runWatchdog;
- (void)start;
- (void)stop;
- (void)setWatchdogInterval:(double)fp8;
- (double)watchdogInterval;
- (void)checkIn;
- (void)dealloc;

@end

