/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSPreferences.h"

@interface WBPreferences : NSPreferences
{
    BOOL _isCancelling;
}

+ (id)preferencesModuleNameFromIdentifier:(int)fp8;
+ (void)_setCachedHomePage:(id)fp8;
+ (id)homePage;
+ (id)homeURL;
+ (void)setHomePage:(id)fp8;
+ (void)resetDownloadPath;
+ (id)_defaultDownloadPathCreatedIfNeeded;
+ (id)_computeDownloadPath;
+ (id)downloadPath;
+ (void)setDownloadPath:(id)fp8;
+ (BOOL)isSafeToOpenFileAtPath:(id)fp8;
+ (BOOL)askBeforeSubmittingInsecureForms;
+ (BOOL)runawayJavaScriptTimerEnabled;
+ (void)setRunawayJavaScriptTimerEnabled:(BOOL)fp8;
- (id)init;
- (BOOL)usesButtons;
- (void)cancel:(id)fp8;
- (BOOL)isCancelling;
- (unsigned int)validModesForFontPanel:(id)fp8;
- (void)changeFont:(id)fp8;
- (BOOL)windowShouldClose:(id)fp8;
- (void)windowWillClose:(id)fp8;

@end

