/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebBookmark.h"

@class NSString;

@interface WebBookmarkProxy : WebBookmark
{
    NSString *_title;
}

- (id)initWithTitle:(id)fp8 group:(id)fp12;
- (id)initFromDictionaryRepresentation:(id)fp8 topLevelOnly:(BOOL)fp12 withGroup:(id)fp16;
- (void)dealloc;
- (id)dictionaryRepresentation;
- (int)bookmarkType;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)icon;

@end

