/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebBookmark.h"

@class NSString;

@interface WebBookmarkLeaf : WebBookmark
{
    NSString *_URLString;
    NSString *_title;
}

- (id)initWithURLString:(id)fp8 title:(id)fp12 group:(id)fp16;
- (id)initFromDictionaryRepresentation:(id)fp8 topLevelOnly:(BOOL)fp12 withGroup:(id)fp16;
- (id)dictionaryRepresentation;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)icon;
- (int)bookmarkType;
- (BOOL)canOpenInTabs;
- (id)URLString;
- (void)setURLString:(id)fp8;
- (BOOL)_computeIsRSSBookmark;
- (id)description;

@end

