/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSError, WebBookmark;

@interface WebBookmarkImporter : NSObject
{
    WebBookmark *topBookmark;
    NSError *error;
}

- (id)unescapeHTML:(id)fp8;
- (id)initWithPath:(id)fp8;
- (id)topBookmark;
- (id)error;
- (void)dealloc;

@end

