/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebBookmark.h"

@class NSMutableArray, NSString;

@interface WebBookmarkList : WebBookmark
{
    NSString *_title;
    NSMutableArray *_list;
    BOOL _autoTab;
}

- (id)initWithIdentifier:(id)fp8 UUID:(id)fp12 group:(id)fp16;
- (id)initWithTitle:(id)fp8 group:(id)fp12;
- (id)initFromDictionaryRepresentation:(id)fp8 topLevelOnly:(BOOL)fp12 withGroup:(id)fp16;
- (id)dictionaryRepresentation;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)icon;
- (int)bookmarkType;
- (id)children;
- (id)rawChildren;
- (unsigned int)numberOfChildren;
- (unsigned int)_numberOfDescendants;
- (void)removeChild:(id)fp8;
- (void)insertChild:(id)fp8 atIndex:(unsigned int)fp12;
- (BOOL)canOpenInTabs;
- (BOOL)automaticallyOpensInTabs;
- (void)setAutomaticallyOpensInTabs:(BOOL)fp8;
- (BOOL)_computeIsRSSBookmark;

@end

