/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSError;

@interface WebBookmarkExporter : NSObject
{
    NSError *_error;
}

- (id)leadingWhiteSpaceForIndentLevel:(int)fp8;
- (id)escapeHTML:(id)fp8;
- (id)stringForBookmarkLeaf:(id)fp8 withIndentLevel:(int)fp12;
- (id)stringForBookmarkList:(id)fp8 withIndentLevel:(int)fp12;
- (id)stringForBookmark:(id)fp8 withIndentLevel:(int)fp12;
- (id)stringForBookmarks:(id)fp8 withIndentLevel:(int)fp12;
- (id)fileContentsWithBookmarks:(id)fp8;
- (id)initWithBookmarks:(id)fp8 path:(id)fp12;
- (void)dealloc;
- (id)error;

@end

