/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebClipBanner.h"

@interface WebClipBanner (FileInternal)
- (id)_browserWebView;
- (id)_croppingOverlayView;
- (void)_setCropRectForNewClip;
- (id)_documentView;
- (void)_mouseMoved:(id)fp8;
- (void)_setLastClippedNode:(id)fp8;
- (void)_startTrackingMouseMovement;
- (void)_stopTrackingMouseMovement;
- (void)_updateCropRectFromMouseMovedEvent:(id)fp8;
- (void)_updateCropRectFromClippedNode:(id)fp8 withDefaultScreenPoint:(struct _NSPoint)fp12;
@end

