/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BannerWithOverlay.h"

@class ClipFinder, ClippedNode, NSButton, NSTextField;

@interface WebClipBanner : BannerWithOverlay
{
    NSTextField *prompt;
    NSButton *cancelButton;
    NSButton *commitButton;
    ClipFinder *_clipFinder;
    ClippedNode *_lastClippedNode;
}

+ (id)bannerColor;
+ (int)bannerSortOrder;
+ (int)bannerHasBottomBorder;
+ (BOOL)overlayAppearsAutomatically;
+ (Class)overlayViewClass;
- (void)dealloc;
- (id)bannerNibName;
- (void)webViewDidMoveToWindow;
- (void)willAttachOverlay;
- (void)willDetachOverlay;
- (BOOL)croppingOverlayView:(id)fp8 interceptMouseDown:(id)fp12;
- (void)cancelCropMode:(id)fp8;
- (void)confirmCropMode:(id)fp8;
- (void)startReshapeMode:(id)fp8;

@end

