/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WebDocumentView <NSObject>
- (void)setDataSource:(id)fp8;
- (void)dataSourceUpdated:(id)fp8;
- (void)setNeedsLayout:(BOOL)fp8;
- (void)layout;
- (void)viewWillMoveToHostWindow:(id)fp8;
- (void)viewDidMoveToHostWindow;
@end

