/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WebDocumentSearching <NSObject>
- (BOOL)searchFor:(id)fp8 direction:(BOOL)fp12 caseSensitive:(BOOL)fp16 wrap:(BOOL)fp20;
@end

