/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebFrame.h"

@interface WebFrame (BrowserAdditions)
- (BOOL)isMainFrame;
- (id)_topFrame;
- (void)_collectFormFieldElementsIntoArray:(id)fp8 upToLimit:(unsigned int)fp12 onlyIncludeFocusedElements:(BOOL)fp16;
- (id)allFormFields;
- (BOOL)containsAnyFormFields;
- (BOOL)containsAnyFocusedFormFields;
- (BOOL)isOrphaned;
- (void)reloadIfParentallyRestricted;
@end

