/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WebIconMenuItem.h"

@interface WebIconMenuItem (FileInternal)
+ (void)_receivedIconChangedNotification:(id)fp8;
+ (void)_receivedAllIconsRemovedNotification:(id)fp8;
- (void)_resetWebIcon;
- (void)_startUpdatingIcon;
- (void)_stopUpdatingIcon;
@end

