/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMenuItem.h"

@class NSString;

@interface WebIconMenuItem : NSMenuItem
{
    NSString *_URLString;
}

+ (void)initialize;
- (id)initWithTitle:(id)fp8 action:(SEL)fp12 keyEquivalent:(id)fp16 URLString:(id)fp20;
- (void)dealloc;
- (void)setMenu:(id)fp8;

@end

