/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class GoogleSearchChannel;

@interface WebSearchManager : NSObject
{
    GoogleSearchChannel *_googleTextSearchChannel;
}

+ (id)sharedManager;
- (id)init;
- (void)dealloc;
- (id)URLWithSearchCriteria:(id)fp8;
- (BOOL)validSearchURL:(id)fp8;
- (id)localSearchStringFromWebSearchString:(id)fp8;

@end

