/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindow.h"

@class NSResponder;

@interface Window : NSWindow
{
    BOOL _unresizable;
    BOOL _firstResponderIsLocked;
    struct _NSSize _savedMinContentSize;
    struct _NSSize _savedMaxContentSize;
    NSResponder *_incomingFirstResponder;
}

- (void)dealloc;
- (void)close;
- (void)becomeKeyWindow;
- (BOOL)willHandleKeyEvent:(id)fp8;
- (void)sendEvent:(id)fp8;
- (void)_setFrameAfterMove:(struct _NSRect)fp8;
- (id)findFrontmostOtherWindowOfWidth:(float)fp8;
- (struct _NSRect)adjustedFrameForCascade:(struct _NSRect)fp8 fromWindow:(id)fp24;
- (struct _NSPoint)cascadeTopLeftFromPoint:(struct _NSPoint)fp8;
- (BOOL)isResizable;
- (void)setResizable:(BOOL)fp8;
- (BOOL)_safari_inLiveResize;
- (void)_endLiveResize;
- (BOOL)makeFirstResponder:(id)fp8;
- (BOOL)firstResponderIsLocked;
- (void)setFirstResponderIsLocked:(BOOL)fp8;
- (id)incomingOrCurrentFirstResponder;
- (void)setFrame:(struct _NSRect)fp8 display:(BOOL)fp24;
- (BOOL)validateUserInterfaceItem:(id)fp8;

@end

