/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTimer;

@interface WindowReopener : NSObject
{
    NSTimer *saveWindowsTimer;
}

+ (void)reopenWindows;
- (void)dealloc;
- (id)arrayOfWindowControllerNamesToReopenAtLaunch;
- (void)reopenWithArrayOfWindowControllerNames:(id)fp8;
- (void)saveWindows;
- (void)_reallySaveWindows;
- (void)windowWillClose:(id)fp8;
- (id)init;

@end

